import { Command } from "commander";
import { resolveBodyParam } from "../../utils.js";
import { sdkForProject } from "../../sdks.js";
import type { RequestParams } from "../../types.js";
import {
  actionRunner,
  commandDescriptions,
  cliConfig,
  parse,
  parseBool,
  parseInteger,
} from "../../parser.js";
import {
  promptForMissing,
  type PromptSpec,
  registerPromptSpecs,
} from "../../interactive.js";

export const consentManagerRecords = new Command("consent-manager-records")
  .description(
    commandDescriptions["consentManagerRecords"] ??
      `The evidence: one append-only record per visitor decision, pointing at the version and hash that was shown, with no IP address, no full user agent and no query string. Readable per browser, exportable for a DPO and summarized per purpose; the only mutation is unlinking a contact on an erasure request, and a prune removes records past their retention.`,
  )
  .configureHelp({
    helpWidth: process.stdout.columns || 80,
  });

const listSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one; it reads one back and puts it in the path of later calls.", type: "string", required: false },
  { key: "consentId", option: "--consent-id <consent-id>", name: "consent_id", description: "Filter to rows whose `consent_id` is exactly this value. The random uuid v4 in the visitor's own `rvx_consent` cookie. It chains one browser's decisions and nothing else — it is never handed to a tag, and a full withdrawal mints a new one.", type: "string", required: false },
  { key: "action", option: "--action <action>", name: "action", description: "Filter to rows whose `action` is exactly this value. What the visitor did: accept_all, reject_all, custom, vendor_grant, withdraw or renew.", type: "string", required: false, enum: ["accept_all","reject_all","custom","vendor_grant","withdraw","renew"] },
  { key: "surface", option: "--surface <surface>", name: "surface", description: "Filter to rows whose `surface` is exactly this value. Where they did it: first_layer, preferences, privacy_link or content_gate.", type: "string", required: false, enum: ["first_layer","preferences","privacy_link","content_gate"] },
  { key: "policyVersionId", option: "--policy-version-id <policy-version-id>", name: "policy_version_id", description: "Filter to rows whose `policy_version_id` is exactly this value. The published version the visitor was shown.", type: "string", required: false },
  { key: "policyNumber", option: "--policy-number <policy-number>", name: "policy_number", description: "Filter to rows whose `policy_number` is exactly this value. That version's number.", type: "integer", required: false },
  { key: "policySha256", option: "--policy-sha256 <policy-sha256>", name: "policy_sha256", description: "Filter to rows whose `policy_sha256` is exactly this value. That version's hash, copied in, so the record alone proves which text it points at.", type: "string", required: false },
  { key: "locale", option: "--locale <locale>", name: "locale", description: "Filter to rows whose `locale` is exactly this value. The language the visitor was shown.", type: "string", required: false },
  { key: "market", option: "--market <market>", name: "market", description: "Filter to rows whose `market` is exactly this value. The market this row belongs to, by code — '' (empty) is the shop as a whole. Taken from the `x-revenexx-market` header of the call that wrote it, never from a body.", type: "string", required: false },
  { key: "recordedAt", option: "--recorded-at <recorded-at>", name: "recorded_at", description: "Filter to rows whose `recorded_at` is exactly this value. When the server received the decision. This is the authoritative time.", type: "string", required: false },
  { key: "clientTs", option: "--client-ts <client-ts>", name: "client_ts", description: "Filter to rows whose `client_ts` is exactly this value. The visitor's clock when they decided, kept as a hint — a record retried on a later page view carries it.", type: "string", required: false },
  { key: "expiresAt", option: "--expires-at <expires-at>", name: "expires_at", description: "Filter to rows whose `expires_at` is exactly this value. When the decision lapses: the received time plus the version's consent lifetime. Retention of the newest record counts from here.", type: "string", required: false },
  { key: "userAgentClass", option: "--user-agent-class <user-agent-class>", name: "user_agent_class", description: "Filter to rows whose `user_agent_class` is exactly this value. The browser family and major version only — never the full user agent.", type: "string", required: false },
  { key: "pagePath", option: "--page-path <page-path>", name: "page_path", description: "Filter to rows whose `page_path` is exactly this value. The path the decision was made on, without query or fragment, so no campaign id is ever stored.", type: "string", required: false },
  { key: "contactId", option: "--contact-id <contact-id>", name: "contact_id", description: "Filter to rows whose `contact_id` is exactly this value. The signed-in B2B contact, taken from the identity the gateway injected — never from the body. Set to null on an erasure request; the rest of the record stays.", type: "string", required: false },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "Filter to rows whose `created_at` is exactly this value. When the row was created. Server-set.", type: "string", required: false },
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Page size (default 50, max 200). A larger value is clamped.", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Row offset (default 0).", type: "integer", required: false },
  { key: "order", option: "--order <order>", name: "order", description: "Sort by one column: 'column', 'column.asc' or 'column.desc'.", type: "string", required: false },
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
consentManagerRecords
  .command(`list`)
  .description(`Every record, filterable by column. There is no route that edits one — an update answers 405.`)
  .option(`--id <id>`, `Filter to rows whose \`id\` is exactly this value. The row's own id, generated by the database. A caller never sends one; it reads one back and puts it in the path of later calls.`)
  .option(`--consent-id <consent-id>`, `Filter to rows whose \`consent_id\` is exactly this value. The random uuid v4 in the visitor's own \`rvx_consent\` cookie. It chains one browser's decisions and nothing else — it is never handed to a tag, and a full withdrawal mints a new one.`)
  .option(`--action <action>`, `Filter to rows whose \`action\` is exactly this value. What the visitor did: accept_all, reject_all, custom, vendor_grant, withdraw or renew.`)
  .option(`--surface <surface>`, `Filter to rows whose \`surface\` is exactly this value. Where they did it: first_layer, preferences, privacy_link or content_gate.`)
  .option(`--policy-version-id <policy-version-id>`, `Filter to rows whose \`policy_version_id\` is exactly this value. The published version the visitor was shown.`)
  .option(`--policy-number <policy-number>`, `Filter to rows whose \`policy_number\` is exactly this value. That version's number.`, parseInteger)
  .option(`--policy-sha256 <policy-sha256>`, `Filter to rows whose \`policy_sha256\` is exactly this value. That version's hash, copied in, so the record alone proves which text it points at.`)
  .option(`--locale <locale>`, `Filter to rows whose \`locale\` is exactly this value. The language the visitor was shown.`)
  .option(`--market <market>`, `Filter to rows whose \`market\` is exactly this value. The market this row belongs to, by code — '' (empty) is the shop as a whole. Taken from the \`x-revenexx-market\` header of the call that wrote it, never from a body.`)
  .option(`--recorded-at <recorded-at>`, `Filter to rows whose \`recorded_at\` is exactly this value. When the server received the decision. This is the authoritative time.`)
  .option(`--client-ts <client-ts>`, `Filter to rows whose \`client_ts\` is exactly this value. The visitor's clock when they decided, kept as a hint — a record retried on a later page view carries it.`)
  .option(`--expires-at <expires-at>`, `Filter to rows whose \`expires_at\` is exactly this value. When the decision lapses: the received time plus the version's consent lifetime. Retention of the newest record counts from here.`)
  .option(`--user-agent-class <user-agent-class>`, `Filter to rows whose \`user_agent_class\` is exactly this value. The browser family and major version only — never the full user agent.`)
  .option(`--page-path <page-path>`, `Filter to rows whose \`page_path\` is exactly this value. The path the decision was made on, without query or fragment, so no campaign id is ever stored.`)
  .option(`--contact-id <contact-id>`, `Filter to rows whose \`contact_id\` is exactly this value. The signed-in B2B contact, taken from the identity the gateway injected — never from the body. Set to null on an erasure request; the rest of the record stays.`)
  .option(`--created-at <created-at>`, `Filter to rows whose \`created_at\` is exactly this value. When the row was created. Server-set.`)
  .option(`--limit <limit>`, `Page size (default 50, max 200). A larger value is clamped.`, parseInteger)
  .option(`--offset <offset>`, `Row offset (default 0).`, parseInteger)
  .option(`--order <order>`, `Sort by one column: 'column', 'column.asc' or 'column.desc'.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, consentId, action, surface, policyVersionId, policyNumber, policySha256, locale, market, recordedAt, clientTs, expiresAt, userAgentClass, pagePath, contactId, createdAt, limit, offset, order, filter } = await promptForMissing(
          _options,
          listSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/consent-manager/records`;
        const _payload: RequestParams = {};
        if (id !== undefined) {
          _payload[`id`] = id;
        }
        if (consentId !== undefined) {
          _payload[`consent_id`] = consentId;
        }
        if (action !== undefined) {
          _payload[`action`] = action;
        }
        if (surface !== undefined) {
          _payload[`surface`] = surface;
        }
        if (policyVersionId !== undefined) {
          _payload[`policy_version_id`] = policyVersionId;
        }
        if (policyNumber !== undefined) {
          _payload[`policy_number`] = policyNumber;
        }
        if (policySha256 !== undefined) {
          _payload[`policy_sha256`] = policySha256;
        }
        if (locale !== undefined) {
          _payload[`locale`] = locale;
        }
        if (market !== undefined) {
          _payload[`market`] = market;
        }
        if (recordedAt !== undefined) {
          _payload[`recorded_at`] = recordedAt;
        }
        if (clientTs !== undefined) {
          _payload[`client_ts`] = clientTs;
        }
        if (expiresAt !== undefined) {
          _payload[`expires_at`] = expiresAt;
        }
        if (userAgentClass !== undefined) {
          _payload[`user_agent_class`] = userAgentClass;
        }
        if (pagePath !== undefined) {
          _payload[`page_path`] = pagePath;
        }
        if (contactId !== undefined) {
          _payload[`contact_id`] = contactId;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        if (order !== undefined) {
          _payload[`order`] = order;
        }
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(consentManagerRecords.commands.at(-1)!, listSpecs, { method: "get" });
const createSpecs: PromptSpec[] = [
  { key: "action", option: "--action <action>", name: "action", description: "What the visitor did: accept_all, reject_all, custom, vendor_grant, withdraw or renew.", type: "string", required: true, enum: ["accept_all","reject_all","custom","vendor_grant","withdraw","renew"] },
  { key: "consentId", option: "--consent-id <consent-id>", name: "consent_id", description: "The random uuid v4 in the visitor's own `rvx_consent` cookie. It chains one browser's decisions and nothing else — it is never handed to a tag, and a full withdrawal mints a new one.", type: "string", required: true },
  { key: "locale", option: "--locale <locale>", name: "locale", description: "The language the visitor was shown; one the version holds.", type: "string", required: true },
  { key: "policyVersionId", option: "--policy-version-id <policy-version-id>", name: "policy_version_id", description: "The published version the visitor was shown.", type: "string", required: true },
  { key: "surface", option: "--surface <surface>", name: "surface", description: "Where they did it: first_layer, preferences, privacy_link or content_gate.", type: "string", required: true, enum: ["first_layer","preferences","privacy_link","content_gate"] },
  { key: "clientTs", option: "--client-ts <client-ts>", name: "client_ts", description: "The visitor's clock when they decided, kept as a hint — a record retried on a later page view carries it.", type: "string", required: false },
  { key: "decisions", option: "--decisions <decisions>", name: "decisions", description: "What was decided. Purposes and vendors by code, each granted, denied or objected. A consent purpose left out is stored denied.", type: "object", required: false },
  { key: "pagePath", option: "--page-path <page-path>", name: "page_path", description: "The page the decision was made on. Any query or fragment is cut off before storing.", type: "string", required: false },
  { key: "userAgentClass", option: "--user-agent-class <user-agent-class>", name: "user_agent_class", description: "The browser as family and major version. A longer value is reduced to that; a full user agent is never stored.", type: "string", required: false },
];
consentManagerRecords
  .command(`create`)
  .description(`Stores one decision under the version that was shown. Every purpose of that version is stored explicitly — a consent purpose left out is denied. The contact comes from the identity the gateway injected, never from the body. No IP address, full user agent or query string is stored, whatever the request carries. Two identical decisions in a row under one version answer the existing record with 200 and \`deduplicated: true\`.`)
  .option(`--action <action>`, `What the visitor did: accept_all, reject_all, custom, vendor_grant, withdraw or renew.`)
  .option(`--consent-id <consent-id>`, `The random uuid v4 in the visitor's own \`rvx_consent\` cookie. It chains one browser's decisions and nothing else — it is never handed to a tag, and a full withdrawal mints a new one.`)
  .option(`--locale <locale>`, `The language the visitor was shown; one the version holds.`)
  .option(`--policy-version-id <policy-version-id>`, `The published version the visitor was shown.`)
  .option(`--surface <surface>`, `Where they did it: first_layer, preferences, privacy_link or content_gate.`)
  .option(`--client-ts <client-ts>`, `The visitor's clock when they decided, kept as a hint — a record retried on a later page view carries it.`)
  .option(`--decisions <decisions>`, `What was decided. Purposes and vendors by code, each granted, denied or objected. A consent purpose left out is stored denied.`)
  .option(`--page-path <page-path>`, `The page the decision was made on. Any query or fragment is cut off before storing.`)
  .option(`--user-agent-class <user-agent-class>`, `The browser as family and major version. A longer value is reduced to that; a full user agent is never stored.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { action, consentId, locale, policyVersionId, surface, clientTs, decisions, pagePath, userAgentClass } = await promptForMissing(
          _options,
          createSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/consent-manager/records`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (action !== undefined) {
          _payload[`action`] = action;
        }
        if (clientTs !== undefined) {
          _payload[`client_ts`] = clientTs;
        }
        if (consentId !== undefined) {
          _payload[`consent_id`] = consentId;
        }
        if (decisions !== undefined) {
          _payload[`decisions`] = resolveBodyParam(decisions);
        }
        if (locale !== undefined) {
          _payload[`locale`] = locale;
        }
        if (pagePath !== undefined) {
          _payload[`page_path`] = pagePath;
        }
        if (policyVersionId !== undefined) {
          _payload[`policy_version_id`] = policyVersionId;
        }
        if (surface !== undefined) {
          _payload[`surface`] = surface;
        }
        if (userAgentClass !== undefined) {
          _payload[`user_agent_class`] = userAgentClass;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(consentManagerRecords.commands.at(-1)!, createSpecs, { method: "post" });
const historySpecs: PromptSpec[] = [
  { key: "consentId", option: "--consent-id <consent-id>", name: "consent_id", description: "The consent id from the visitor's cookie.", type: "string", required: true },
];
consentManagerRecords
  .command(`history`)
  .description(`Every record of one consent id, oldest first, each naming the version it was shown under.`)
  .option(`--consent-id <consent-id>`, `The consent id from the visitor's cookie.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { consentId } = await promptForMissing(
          _options,
          historySpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/consent-manager/records/by-consent/{consent_id}`.replace(`{consent_id}`, consentId);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(consentManagerRecords.commands.at(-1)!, historySpecs, { method: "get" });
const exportSpecs: PromptSpec[] = [
  { key: "from", option: "--from <from>", name: "from", description: "Start of the period, inclusive.", type: "string", required: false },
  { key: "to", option: "--to <to>", name: "to", description: "End of the period, exclusive.", type: "string", required: false },
  { key: "market", option: "--market <market>", name: "market", description: "Only this market ('' = the shop).", type: "string", required: false },
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Rows per call (max 1000).", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Continue from here.", type: "integer", required: false },
];
consentManagerRecords
  .command(`export`)
  .description(`The records received from \`from\` (inclusive) to \`to\` (exclusive), oldest first, as rows and as one CSV rendering. Every row names the version and hash it points to. At most 1000 rows per call; continue with \`next_offset\`.`)
  .option(`--from <from>`, `Start of the period, inclusive.`)
  .option(`--to <to>`, `End of the period, exclusive.`)
  .option(`--market <market>`, `Only this market ('' = the shop).`)
  .option(`--limit <limit>`, `Rows per call (max 1000).`, parseInteger)
  .option(`--offset <offset>`, `Continue from here.`, parseInteger)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { from, to, market, limit, offset } = await promptForMissing(
          _options,
          exportSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/consent-manager/records/export`;
        const _payload: RequestParams = {};
        if (from !== undefined) {
          _payload[`from`] = from;
        }
        if (to !== undefined) {
          _payload[`to`] = to;
        }
        if (market !== undefined) {
          _payload[`market`] = market;
        }
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(consentManagerRecords.commands.at(-1)!, exportSpecs, { method: "get" });
const pruneSpecs: PromptSpec[] = [
  { key: "dryRun", option: "--dry-run <dry-run>", name: "dry_run", description: "Defaults to true: report, delete nothing.", type: "boolean", required: false },
];
consentManagerRecords
  .command(`prune`)
  .description(`Deletes records that ended longer ago than \`proof_retention_days\` (never less than 365): superseded records from the time the same browser decided again, the newest one from its expiry. The newest record of a browser therefore stays while it is current. Previews unless \`dry_run: false\` is sent; the daily \`prune-records\` schedule runs it for real. Bounded per call — \`has_more\` says whether to call again.`)
  .option(
    `--dry-run [value]`,
    `Defaults to true: report, delete nothing.`,
    (value: string | undefined) =>
      value === undefined ? true : parseBool(value),
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { dryRun } = await promptForMissing(
          _options,
          pruneSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/consent-manager/records/prune`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (dryRun !== undefined) {
          _payload[`dry_run`] = dryRun;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(consentManagerRecords.commands.at(-1)!, pruneSpecs, { method: "post" });
const summarySpecs: PromptSpec[] = [
  { key: "market", option: "--market <market>", name: "market", description: "The market ('' = the shop).", type: "string", required: false },
  { key: "from", option: "--from <from>", name: "from", description: "Start, inclusive.", type: "string", required: false },
  { key: "to", option: "--to <to>", name: "to", description: "End, exclusive.", type: "string", required: false },
];
consentManagerRecords
  .command(`summary`)
  .description(`Granted, denied and objected counts per purpose and counts per action for one market (\`?market=\`, else \`x-revenexx-market\`, else the shop) and an optional period. A statistic: it carries no consent id, record id or contact.`)
  .option(`--market <market>`, `The market ('' = the shop).`)
  .option(`--from <from>`, `Start, inclusive.`)
  .option(`--to <to>`, `End, exclusive.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { market, from, to } = await promptForMissing(
          _options,
          summarySpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/consent-manager/records/summary`;
        const _payload: RequestParams = {};
        if (market !== undefined) {
          _payload[`market`] = market;
        }
        if (from !== undefined) {
          _payload[`from`] = from;
        }
        if (to !== undefined) {
          _payload[`to`] = to;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(consentManagerRecords.commands.at(-1)!, summarySpecs, { method: "get" });
const unlinkContactSpecs: PromptSpec[] = [
  { key: "contactId", option: "--contact-id <contact-id>", name: "contact_id", description: "The contact to unlink.", type: "string", required: true },
];
consentManagerRecords
  .command(`unlink-contact`)
  .description(`An erasure request for a signed-in contact: sets \`contact_id\` to null on every record of that contact and changes nothing else. The proof stays, because it is kept for legal claims (Art. 17 (3) e GDPR). The only mutation a record ever sees.`)
  .option(`--contact-id <contact-id>`, `The contact to unlink.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { contactId } = await promptForMissing(
          _options,
          unlinkContactSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/consent-manager/records/unlink-contact`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (contactId !== undefined) {
          _payload[`contact_id`] = contactId;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(consentManagerRecords.commands.at(-1)!, unlinkContactSpecs, { method: "post" });
const getSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The record.", type: "string", required: true, resource: { listPath: "/consent-manager/records", hasLimit: true } },
];
consentManagerRecords
  .command(`get`)
  .description(`One record.`)
  .option(`--id <id>`, `The record.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          getSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/consent-manager/records/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(consentManagerRecords.commands.at(-1)!, getSpecs, { method: "get" });
