import { Command } from "commander";
import { resolveBodyParam } from "../../utils.js";
import { sdkForProject } from "../../sdks.js";
import type { RequestParams } from "../../types.js";
import {
  actionRunner,
  commandDescriptions,
  cliConfig,
  parse,
  parseBool,
  parseInteger,
} from "../../parser.js";
import {
  confirmDestructive,
  promptForMissing,
  type PromptSpec,
  registerPromptSpecs,
} from "../../interactive.js";

export const documentsKinds = new Command("documents-kinds")
  .description(
    commandDescriptions["documentsKinds"] ??
      `What sort of record a document is, as a list the MERCHANT keeps. Four kinds arrive with the app because an order produces them — invoice, delivery note, credit note, return receipt — and every trade has more: a proforma invoice, a dunning letter, a works certificate. Nothing in this app branches on a kind, so a closed set bought no safety and would have cost a release per trade; \`documents.kind\` therefore publishes no enum, and a value the merchant added this morning is accepted at once. Three rules replace the foreign key these rows have on purpose not got: a \`code\` is fixed once created (it is what every document stores), a kind at least one document carries cannot be deleted, and the last kind cannot be deleted at all. Exactly one row is the default, and moving the flag is its own call. The same two vocabulary addresses every app serves answer these values with the title and tone a screen renders, alongside \`visibilities\`, whose set is the database CHECK and closed to a merchant because the app really does branch on it.`,
  )
  .configureHelp({
    helpWidth: process.stdout.columns || 80,
  });

const listSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.", type: "string", required: false },
  { key: "code", option: "--code <code>", name: "code", description: "Look one kind up by the code a document stores. Unique per tenant, so this resolves a code a caller already holds without paging the list.", type: "string", required: false },
  { key: "title", option: "--title <title>", name: "title", description: "Filter to rows whose `title` is exactly this value. What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in `labels`.", type: "string", required: false },
  { key: "description", option: "--description <description>", name: "description", description: "Filter to rows whose `description` is exactly this value. One sentence a person reads under the title — what this value is for. Optional.", type: "string", required: false },
  { key: "isDefault", option: "--is-default <is-default>", name: "is_default", description: "Filter to the default kind. Exactly one row carries the flag, so `true` answers one.", type: "boolean", required: false },
  { key: "tone", option: "--tone <tone>", name: "tone", description: "Filter to rows whose `tone` is exactly this value. The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'.", type: "string", required: false, enum: ["neutral","info","success","warning","danger"] },
  { key: "position", option: "--position <position>", name: "position", description: "Filter to rows whose `position` is exactly this value. Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order.", type: "integer", required: false },
  { key: "isSystem", option: "--is-system <is-system>", name: "is_system", description: "Filter by whether this app seeded the value. `false` is the set a merchant added themselves.", type: "boolean", required: false },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.", type: "string", required: false },
  { key: "updatedAt", option: "--updated-at <updated-at>", name: "updated_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was last written. Server-set — every route that changes this row stamps it.", type: "string", required: false },
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Page size (default 50, max 200). A larger value is clamped rather than refused.", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.", type: "integer", required: false },
  { key: "order", option: "--order <order>", name: "order", description: "Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.", type: "string", required: false },
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
documentsKinds
  .command(`list`)
  .description(`A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. This is the list \`documents.kind\` is validated against on every write, so it is the first thing to read when a document is refused as an unknown kind. It SEEDS on read: a tenant whose table is empty — one whose install announcement never arrived — is given the four kinds here rather than being told it has none and then being unable to file anything. Exactly one row carries \`is_default\`, and the read repairs that too, so a client may rely on finding one.`)
  .option(`--id <id>`, `Filter to rows whose \`id\` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.`)
  .option(`--code <code>`, `Look one kind up by the code a document stores. Unique per tenant, so this resolves a code a caller already holds without paging the list.`)
  .option(`--title <title>`, `Filter to rows whose \`title\` is exactly this value. What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in \`labels\`.`)
  .option(`--description <description>`, `Filter to rows whose \`description\` is exactly this value. One sentence a person reads under the title — what this value is for. Optional.`)
  .option(
    `--is-default [value]`,
    `Filter to the default kind. Exactly one row carries the flag, so \`true\` answers one.`,
    (value: string | undefined) =>
      value === undefined ? true : parseBool(value),
  )
  .option(`--tone <tone>`, `Filter to rows whose \`tone\` is exactly this value. The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'.`)
  .option(`--position <position>`, `Filter to rows whose \`position\` is exactly this value. Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order.`, parseInteger)
  .option(
    `--is-system [value]`,
    `Filter by whether this app seeded the value. \`false\` is the set a merchant added themselves.`,
    (value: string | undefined) =>
      value === undefined ? true : parseBool(value),
  )
  .option(`--created-at <created-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.`)
  .option(`--updated-at <updated-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When the row was last written. Server-set — every route that changes this row stamps it.`)
  .option(`--limit <limit>`, `Page size (default 50, max 200). A larger value is clamped rather than refused.`, parseInteger)
  .option(`--offset <offset>`, `Row offset for pagination (default 0). Page with \`page.total\` and \`page.hasMore\`.`, parseInteger)
  .option(`--order <order>`, `Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, code, title, description, isDefault, tone, position, isSystem, createdAt, updatedAt, limit, offset, order, filter } = await promptForMissing(
          _options,
          listSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/kinds`;
        const _payload: RequestParams = {};
        if (id !== undefined) {
          _payload[`id`] = id;
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (title !== undefined) {
          _payload[`title`] = title;
        }
        if (description !== undefined) {
          _payload[`description`] = description;
        }
        if (isDefault !== undefined) {
          _payload[`is_default`] = isDefault;
        }
        if (tone !== undefined) {
          _payload[`tone`] = tone;
        }
        if (position !== undefined) {
          _payload[`position`] = position;
        }
        if (isSystem !== undefined) {
          _payload[`is_system`] = isSystem;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        if (updatedAt !== undefined) {
          _payload[`updated_at`] = updatedAt;
        }
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        if (order !== undefined) {
          _payload[`order`] = order;
        }
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsKinds.commands.at(-1)!, listSpecs, { method: "get" });
const createSpecs: PromptSpec[] = [
  { key: "code", option: "--code <code>", name: "code", description: "The value's stable identifier, and the string a document stores in `kind`. Lowercase letters, digits, `-` and `_`, starting with a letter. Unique per tenant and FIXED once created: renaming it would orphan every document carrying it, so an edit that changes it is refused and the title is what a merchant renames.", type: "string", required: true },
  { key: "title", option: "--title <title>", name: "title", description: "What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in `labels`.", type: "string", required: true },
  { key: "description", option: "--description <description>", name: "description", description: "One sentence a person reads under the title — what this value is for. Optional.", type: "string", required: false },
  { key: "descriptions", option: "--descriptions <descriptions>", name: "descriptions", description: "The description per language tag. Falls back to `description` when a tag is missing.", type: "object", required: false },
  { key: "isDefault", option: "--is-default <is-default>", name: "is_default", description: "Whether this is the value a caller falls back to. Exactly ONE row of the table carries it: promoting another demotes the current one, so a client can mark the default without reading anything else. Deleting the default hands the flag to the first remaining row. Sending `true` promotes this value and demotes whichever held the flag. `false` is ignored — demote by promoting another.", type: "boolean", required: false },
  { key: "labels", option: "--labels <labels>", name: "labels", description: "The title per language tag, for a UI that has to render it in the reader's language. Falls back to `title` when a tag is missing.", type: "object", required: false },
  { key: "position", option: "--position <position>", name: "position", description: "Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order. Defaults to 0.", type: "integer", required: false },
  { key: "tone", option: "--tone <tone>", name: "tone", description: "The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'. Defaults to 'neutral' on a value a merchant creates.", type: "string", required: false, enum: ["neutral","info","success","warning","danger"] },
];
documentsKinds
  .command(`create`)
  .description(`A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. This is the route that makes the set open. A proforma invoice, a dunning letter, a works certificate or a scrap certificate is a kind this app was never going to enumerate, and a document may name it the moment it exists here — no release, no migration. \`code\` is lowercase letters, digits, \`-\` and \`_\`, unique per tenant and FIXED from here on; \`title\` is what a merchant renames later. The value is created as the merchant's own (\`is_system: false\`) and not as the default unless \`is_default: true\` says so, in which case whichever row held the flag is demoted in the same call.`)
  .option(`--code <code>`, `The value's stable identifier, and the string a document stores in \`kind\`. Lowercase letters, digits, \`-\` and \`_\`, starting with a letter. Unique per tenant and FIXED once created: renaming it would orphan every document carrying it, so an edit that changes it is refused and the title is what a merchant renames.`)
  .option(`--title <title>`, `What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in \`labels\`.`)
  .option(`--description <description>`, `One sentence a person reads under the title — what this value is for. Optional.`)
  .option(`--descriptions <descriptions>`, `The description per language tag. Falls back to \`description\` when a tag is missing.`)
  .option(
    `--is-default [value]`,
    `Whether this is the value a caller falls back to. Exactly ONE row of the table carries it: promoting another demotes the current one, so a client can mark the default without reading anything else. Deleting the default hands the flag to the first remaining row. Sending \`true\` promotes this value and demotes whichever held the flag. \`false\` is ignored — demote by promoting another.`,
    (value: string | undefined) =>
      value === undefined ? true : parseBool(value),
  )
  .option(`--labels <labels>`, `The title per language tag, for a UI that has to render it in the reader's language. Falls back to \`title\` when a tag is missing.`)
  .option(`--position <position>`, `Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order. Defaults to 0.`, parseInteger)
  .option(`--tone <tone>`, `The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'. Defaults to 'neutral' on a value a merchant creates.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { code, title, description, descriptions, isDefault, labels, position, tone } = await promptForMissing(
          _options,
          createSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/kinds`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (description !== undefined) {
          _payload[`description`] = description;
        }
        if (descriptions !== undefined) {
          _payload[`descriptions`] = resolveBodyParam(descriptions);
        }
        if (isDefault !== undefined) {
          _payload[`is_default`] = isDefault;
        }
        if (labels !== undefined) {
          _payload[`labels`] = resolveBodyParam(labels);
        }
        if (position !== undefined) {
          _payload[`position`] = position;
        }
        if (title !== undefined) {
          _payload[`title`] = title;
        }
        if (tone !== undefined) {
          _payload[`tone`] = tone;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsKinds.commands.at(-1)!, createSpecs, { method: "post" });
const defaultsSpecs: PromptSpec[] = [
  { key: "body", option: "--body <body>", name: "data", description: "Request body", type: "object", required: true },
];
documentsKinds
  .command(`defaults`)
  .description(`A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. Seeds \`invoice\`, \`delivery_note\`, \`credit_note\` and \`return_receipt\`, with \`invoice\` as the default. IDEMPOTENT BY CODE: a kind the tenant already has is left exactly as it is, including a title they changed and a tone they re-picked, so a second call reports it under \`existing\` and writes nothing. The same seed runs on the app.installed announcement and lazily on the first list read — three paths, because the marketplace does not reliably fire the install event and a tenant with no kinds can file no documents.`)
  .option(`--body <body>`, `Request body`)
  .action(
    actionRunner(
      async (_options, _command) => {
        // The global --data is the documented body flag: let it satisfy the
        // required --body before promptForMissing() asks for it.
        if (cliConfig.data !== undefined) {
          (_options as Record<string, unknown>).body ??= cliConfig.data;
        }
        const { body } = await promptForMissing(
          _options,
          defaultsSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/kinds/defaults`;
        const _payload: RequestParams = {};
        if (body !== undefined || cliConfig.data !== undefined) {
          Object.assign(_payload, resolveBodyParam(body ?? cliConfig.data));
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsKinds.commands.at(-1)!, defaultsSpecs, { method: "post" });
const deleteSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The document kind to remove.", type: "string", required: true, resource: { listPath: "/documents/kinds", hasLimit: true } },
];
documentsKinds
  .command(`delete`)
  .description(`A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. Two refusals stand in for the foreign key these rows deliberately have not got. A kind at least one document still carries is a 409, because there is no reference to break — the alternative is a document whose kind nothing can render. And the LAST kind is a 409 whatever else is true, because every document carries one and a merchant with none could file nothing. Deleting the default hands the flag to the first remaining row, so a client may still rely on finding one.`)
  .option(`--id <id>`, `The document kind to remove.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          deleteSpecs,
          _command,
        );
        await confirmDestructive(`documents-kinds delete`);
        const _client = await sdkForProject();
        const _apiPath = `/documents/kinds/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `delete`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsKinds.commands.at(-1)!, deleteSpecs, { method: "delete", destructive: true });
const getSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The document kind to read.", type: "string", required: true, resource: { listPath: "/documents/kinds", hasLimit: true } },
];
documentsKinds
  .command(`get`)
  .description(`A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. The route that turns an id back into a kind. Unlike the list it does NOT seed, so on a fresh tenant read the list first — and note that a document stores the \`code\`, never this id, which is why the code cannot change.`)
  .option(`--id <id>`, `The document kind to read.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          getSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/kinds/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsKinds.commands.at(-1)!, getSpecs, { method: "get" });
const updateSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The document kind to edit.", type: "string", required: true, resource: { listPath: "/documents/kinds", hasLimit: true } },
  { key: "code", option: "--code <code>", name: "code", description: "The value's stable identifier, and the string a document stores in `kind`. Lowercase letters, digits, `-` and `_`, starting with a letter. Unique per tenant and FIXED once created: renaming it would orphan every document carrying it, so an edit that changes it is refused and the title is what a merchant renames.", type: "string", required: false },
  { key: "description", option: "--description <description>", name: "description", description: "One sentence a person reads under the title — what this value is for. Optional.", type: "string", required: false },
  { key: "descriptions", option: "--descriptions <descriptions>", name: "descriptions", description: "The description per language tag. Falls back to `description` when a tag is missing.", type: "object", required: false },
  { key: "isDefault", option: "--is-default <is-default>", name: "is_default", description: "Whether this is the value a caller falls back to. Exactly ONE row of the table carries it: promoting another demotes the current one, so a client can mark the default without reading anything else. Deleting the default hands the flag to the first remaining row. Sending `true` promotes this value and demotes whichever held the flag. `false` is ignored — demote by promoting another.", type: "boolean", required: false },
  { key: "labels", option: "--labels <labels>", name: "labels", description: "The title per language tag, for a UI that has to render it in the reader's language. Falls back to `title` when a tag is missing.", type: "object", required: false },
  { key: "position", option: "--position <position>", name: "position", description: "Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order. Defaults to 0.", type: "integer", required: false },
  { key: "title", option: "--title <title>", name: "title", description: "What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in `labels`.", type: "string", required: false },
  { key: "tone", option: "--tone <tone>", name: "tone", description: "The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'. Defaults to 'neutral' on a value a merchant creates.", type: "string", required: false, enum: ["neutral","info","success","warning","danger"] },
];
documentsKinds
  .command(`update`)
  .description(`A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. What a merchant edits here is the WORDS: the title, the per-language labels, the description, the badge tone and the position in a select. What they cannot edit is the \`code\` — every document stores it, so renaming it would orphan each one, and a body that changes it is refused with a 400 that says to create a new kind and move the documents over. A seeded kind is as editable as any other: \`is_system\` records that this app put the row there and grants it no protection.`)
  .option(`--id <id>`, `The document kind to edit.`)
  .option(`--code <code>`, `The value's stable identifier, and the string a document stores in \`kind\`. Lowercase letters, digits, \`-\` and \`_\`, starting with a letter. Unique per tenant and FIXED once created: renaming it would orphan every document carrying it, so an edit that changes it is refused and the title is what a merchant renames.`)
  .option(`--description <description>`, `One sentence a person reads under the title — what this value is for. Optional.`)
  .option(`--descriptions <descriptions>`, `The description per language tag. Falls back to \`description\` when a tag is missing.`)
  .option(
    `--is-default [value]`,
    `Whether this is the value a caller falls back to. Exactly ONE row of the table carries it: promoting another demotes the current one, so a client can mark the default without reading anything else. Deleting the default hands the flag to the first remaining row. Sending \`true\` promotes this value and demotes whichever held the flag. \`false\` is ignored — demote by promoting another.`,
    (value: string | undefined) =>
      value === undefined ? true : parseBool(value),
  )
  .option(`--labels <labels>`, `The title per language tag, for a UI that has to render it in the reader's language. Falls back to \`title\` when a tag is missing.`)
  .option(`--position <position>`, `Sort order in a select or a list, ascending. Values that tie fall back to their code, so a table where every position is 0 is still in a stable order. Defaults to 0.`, parseInteger)
  .option(`--title <title>`, `What the value is called for a person, in the tenant's working language. At least one character. A locale map goes in \`labels\`.`)
  .option(`--tone <tone>`, `The badge colour a screen renders this value in — semantic, not a hex code: the vocabulary says what a value MEANS and the client decides what 'warning' looks like in its own design system. One of 'neutral', 'info', 'success', 'warning', 'danger'. Defaults to 'neutral' on a value a merchant creates.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, code, description, descriptions, isDefault, labels, position, title, tone } = await promptForMissing(
          _options,
          updateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/kinds/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (description !== undefined) {
          _payload[`description`] = description;
        }
        if (descriptions !== undefined) {
          _payload[`descriptions`] = resolveBodyParam(descriptions);
        }
        if (isDefault !== undefined) {
          _payload[`is_default`] = isDefault;
        }
        if (labels !== undefined) {
          _payload[`labels`] = resolveBodyParam(labels);
        }
        if (position !== undefined) {
          _payload[`position`] = position;
        }
        if (title !== undefined) {
          _payload[`title`] = title;
        }
        if (tone !== undefined) {
          _payload[`tone`] = tone;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `put`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsKinds.commands.at(-1)!, updateSpecs, { method: "put" });
const makeDefaultSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The document kind to make the default.", type: "string", required: true, resource: { listPath: "/documents/kinds", hasLimit: true } },
];
documentsKinds
  .command(`make-default`)
  .description(`A document kind is a value the MERCHANT keeps: a code every document stores, the words a person reads for it and the badge colour a screen renders. Four arrive with the app because an order produces them; a merchant adds a proforma invoice or a dunning letter without a release of this app. The default flag is a SINGLE answer, not a per-row opinion, so moving it is a single call: this row is promoted and whichever held it is demoted, in one request. \`PUT\` with \`is_default: true\` does the same thing as a side effect of an edit — this exists because a client that wants nothing but the flag moved should not have to send one, and because promoting and demoting in two calls can leave two defaults or none.`)
  .option(`--id <id>`, `The document kind to make the default.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          makeDefaultSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/kinds/{id}/make-default`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsKinds.commands.at(-1)!, makeDefaultSpecs, { method: "post" });
const documentsVocabulariesListSpecs: PromptSpec[] = [
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
documentsKinds
  .command(`documents-vocabularies-list`)
  .description(`The index of the value sets this app owns, with their titles and no values — the cheap read a client makes once. Two are published, and they differ in WHO owns the set: \`kinds\` is the merchant's own table, so it is read per request and a merchant may extend it; \`visibilities\` is the database CHECK, so it is closed and a merchant cannot. A client holding \`'documents.kinds'\` builds \`GET /documents/vocabularies/kinds\` with no further knowledge, which is the point of every app serving these two routes under its own prefix.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { filter } = await promptForMissing(
          _options,
          documentsVocabulariesListSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/vocabularies`;
        const _payload: RequestParams = {};
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsKinds.commands.at(-1)!, documentsVocabulariesListSpecs, { method: "get" });
const documentsVocabulariesGetSpecs: PromptSpec[] = [
  { key: "name", option: "--name <name>", name: "name", description: "The vocabulary to read, as GET /documents/vocabularies names it.", type: "string", required: true, enum: ["kinds","visibilities"], resource: { listPath: "/documents/vocabularies", hasLimit: false } },
];
documentsKinds
  .command(`documents-vocabularies-get`)
  .description(`One vocabulary and every value in it, each with the title, description and badge tone a screen renders — which is the reason this route exists at all: a UI that keeps its own copy of the list is a UI that eventually offers a value the data refuses. \`source\` says where the set comes from and is the field to branch on: 'table' means the merchant owns it (\`kinds\`), so the answer is their rows in their order and \`is_default\` marks the fallback; 'schema' means a database CHECK owns it (\`visibilities\`), so the served set is the enforced set by construction. \`closed\` is true either way — the set is exhaustive at this moment, so a value outside it is stale data rather than a missing label. Reading \`kinds\` SEEDS an empty table, exactly as the kinds list does.`)
  .option(`--name <name>`, `The vocabulary to read, as GET /documents/vocabularies names it.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { name } = await promptForMissing(
          _options,
          documentsVocabulariesGetSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/vocabularies/{name}`.replace(`{name}`, name);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsKinds.commands.at(-1)!, documentsVocabulariesGetSpecs, { method: "get" });
