import { Command } from "commander";
import { resolveBodyParam } from "../../utils.js";
import { sdkForProject } from "../../sdks.js";
import type { RequestParams } from "../../types.js";
import {
  actionRunner,
  commandDescriptions,
  cliConfig,
  parse,
  parseInteger,
} from "../../parser.js";
import {
  confirmDestructive,
  promptForMissing,
  type PromptSpec,
  registerPromptSpecs,
} from "../../interactive.js";

export const documentsRegister = new Command("documents-register")
  .description(
    commandDescriptions["documentsRegister"] ??
      `The records a buyer is sent, and the one question this app exists to answer: which document belongs to which transaction. A document is an invoice, a delivery note, a credit note or a return receipt — filed against a transaction (\`entity_type\` + \`entity_id\`, and \`order\` is the only owner accepted today), carrying the \`number\` a customer quotes on the phone, and pointing at bytes it never holds: \`source\` decides whether the file is an asset of this platform (\`storage_asset_id\`) or a file on the tenant's own host (\`external_url\`), and a database CHECK pairs the two so neither can be half-filled. Nothing here produces a document and nothing here serves one — a finance system issues them, this records what was issued. The column to read twice is \`visibility\`: an \`internal\` document is answered to an operator and NEVER to a storefront caller, which is confined to the customer ones in the query itself, so an internal row is missing from its list, missing from its page total and a 404 at its own address.`,
  )
  .configureHelp({
    helpWidth: process.stdout.columns || 80,
  });

const documentsDocumentsListSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.", type: "string", required: false },
  { key: "entityType", option: "--entity-type <entity-type>", name: "entity_type", description: "Filter by the kind of transaction a document belongs to. Send it together with `entity_id`: on its own it selects every document of every order.", type: "string", required: false },
  { key: "entityId", option: "--entity-id <entity-id>", name: "entity_id", description: "Filter to ONE transaction's documents — with `entity_type`, this is the pair an account area reads a buyer's papers with.", type: "string", required: false },
  { key: "kind", option: "--kind <kind>", name: "kind", description: "Filter by kind. One of the kinds this tenant keeps (GET /documents/kinds); no enum is published, because the set is the merchant's and a value they added this morning must not be refused.", type: "string", required: false },
  { key: "number", option: "--number <number>", name: "number", description: "Look a document up by the number printed on it — the search a service desk starts from when a customer quotes one. Exact match, and not unique: two documents of one order may legitimately share a number.", type: "string", required: false },
  { key: "source", option: "--source <source>", name: "source", description: "Filter by where the bytes are. The operational use is finding the external ones before a host is retired.", type: "string", required: false, enum: ["storage","external"] },
  { key: "storageAssetId", option: "--storage-asset-id <storage-asset-id>", name: "storage_asset_id", description: "Find the document that points at one stored file — the reverse lookup, for a clean-up that has an asset and needs its register entry.", type: "string", required: false },
  { key: "deliveryPath", option: "--delivery-path <delivery-path>", name: "delivery_path", description: "Filter to rows whose `delivery_path` is exactly this value. Where the stored file is served from today — a CDN path, and a CACHE of an address rather than an authorisation. Do NOT fetch a document with it: a path is not a permission, so it answers a private asset with 403, and it is stale the moment the file moves. POST /documents/documents/{id}/link is the way to get the bytes; this column is kept for an operator tracing an object through the delivery plane. Null for an external document.", type: "string", required: false },
  { key: "externalUrl", option: "--external-url <external-url>", name: "external_url", description: "Filter to rows whose `external_url` is exactly this value. The address of a file this platform does not hold. Required while `source` is 'external' and null otherwise. It is the tenant's own host — a document archive, a finance system's portal — and this app stores the address without fetching it.", type: "string", required: false },
  { key: "filename", option: "--filename <filename>", name: "filename", description: "Filter by the exact file name. Useful against a feed that re-sends under a new key; it is an equality, not a search.", type: "string", required: false },
  { key: "contentType", option: "--content-type <content-type>", name: "content_type", description: "Filter to rows whose `content_type` is exactly this value. The media type of the file, so a client knows whether to open it or hand it to the browser. Nullable, because a feed does not always say.", type: "string", required: false },
  { key: "byteSize", option: "--byte-size <byte-size>", name: "byte_size", description: "Filter to rows whose `byte_size` is exactly this value. How large the file is, in bytes — what a download link shows next to it. Nullable, and never computed here: this app does not read the bytes.", type: "integer", required: false },
  { key: "issuedAt", option: "--issued-at <issued-at>", name: "issued_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. The date ON the document — when the merchant issued it, not when this row was written. It is the date a buyer sorts their invoices by and the one that appears in a tax return, which is why it is a date and not a timestamp: a document is issued on a day.", type: "string", required: false },
  { key: "dueDate", option: "--due-date <due-date>", name: "due_date", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the amount on this document is due. Only some kinds carry one — an invoice does, a delivery note does not — so it is nullable, and nothing in this app dunns on it.", type: "string", required: false },
  { key: "totalAmount", option: "--total-amount <total-amount>", name: "total_amount", description: "Filter to rows whose `total_amount` is exactly this value. The gross amount printed on the document, in `currency`. A COPY of what the document says, kept so a list can show it without fetching the file — it is not recomputed here and never corrects the document. Nullable: a delivery note carries no amount.", type: "number", required: false },
  { key: "currency", option: "--currency <currency>", name: "currency", description: "Filter to rows whose `currency` is exactly this value. The ISO 4217 code the amount is in. Nullable exactly where the amount is, and carried per document rather than per tenant because a merchant selling across markets issues in more than one.", type: "string", required: false },
  { key: "visibility", option: "--visibility <visibility>", name: "visibility", description: "Filter by who may read the document. A storefront caller is confined to 'customer' whatever it sends here, so this selector narrows an operator's list and can never widen a buyer's.", type: "string", required: false, enum: ["internal","customer"] },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "Look a document up by the key the system that issued it knows it by — what a feed does before deciding between a create and an update. Unique per tenant, so this answers at most one document.", type: "string", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.", type: "string", required: false },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.", type: "string", required: false },
  { key: "updatedAt", option: "--updated-at <updated-at>", name: "updated_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was last written. Server-set — every route that changes this row stamps it.", type: "string", required: false },
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Page size (default 50, max 200). A larger value is clamped rather than refused.", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.", type: "integer", required: false },
  { key: "order", option: "--order <order>", name: "order", description: "Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.", type: "string", required: false },
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
documentsRegister
  .command(`documents-documents-list`)
  .description(`A document is one record a merchant issued and filed against a transaction — an invoice, a delivery note, a credit note, a return receipt. The row is the REGISTER entry: it says which transaction the document belongs to, what kind of record it is, the number a customer quotes, who may read it and where its bytes live. It never holds the bytes, and this app never produces a document. This is the list an account area reads: filter \`?entity_type=order&entity_id=…\` for one transaction's papers, \`?kind=invoice\` for one sort of record, \`?number=\` for the one a customer quoted. Read \`visibility\` before trusting the answer to be complete — a STOREFRONT caller (one acting for a buyer, or one asking with \`?audience=customer\`) is confined to the customer documents in the query itself, so an internal one is absent from \`items\` AND from \`page.total\`, which is what stops the count telling a buyer how many documents it is not being shown. The narrowing only ever narrows: \`?visibility=internal\` from such a caller answers the customer ones, not a 403.`)
  .option(`--id <id>`, `Filter to rows whose \`id\` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.`)
  .option(`--entity-type <entity-type>`, `Filter by the kind of transaction a document belongs to. Send it together with \`entity_id\`: on its own it selects every document of every order.`)
  .option(`--entity-id <entity-id>`, `Filter to ONE transaction's documents — with \`entity_type\`, this is the pair an account area reads a buyer's papers with.`)
  .option(`--kind <kind>`, `Filter by kind. One of the kinds this tenant keeps (GET /documents/kinds); no enum is published, because the set is the merchant's and a value they added this morning must not be refused.`)
  .option(`--number <number>`, `Look a document up by the number printed on it — the search a service desk starts from when a customer quotes one. Exact match, and not unique: two documents of one order may legitimately share a number.`)
  .option(`--source <source>`, `Filter by where the bytes are. The operational use is finding the external ones before a host is retired.`)
  .option(`--storage-asset-id <storage-asset-id>`, `Find the document that points at one stored file — the reverse lookup, for a clean-up that has an asset and needs its register entry.`)
  .option(`--delivery-path <delivery-path>`, `Filter to rows whose \`delivery_path\` is exactly this value. Where the stored file is served from today — a CDN path, and a CACHE of an address rather than an authorisation. Do NOT fetch a document with it: a path is not a permission, so it answers a private asset with 403, and it is stale the moment the file moves. POST /documents/documents/{id}/link is the way to get the bytes; this column is kept for an operator tracing an object through the delivery plane. Null for an external document.`)
  .option(`--external-url <external-url>`, `Filter to rows whose \`external_url\` is exactly this value. The address of a file this platform does not hold. Required while \`source\` is 'external' and null otherwise. It is the tenant's own host — a document archive, a finance system's portal — and this app stores the address without fetching it.`)
  .option(`--filename <filename>`, `Filter by the exact file name. Useful against a feed that re-sends under a new key; it is an equality, not a search.`)
  .option(`--content-type <content-type>`, `Filter to rows whose \`content_type\` is exactly this value. The media type of the file, so a client knows whether to open it or hand it to the browser. Nullable, because a feed does not always say.`)
  .option(`--byte-size <byte-size>`, `Filter to rows whose \`byte_size\` is exactly this value. How large the file is, in bytes — what a download link shows next to it. Nullable, and never computed here: this app does not read the bytes.`, parseInteger)
  .option(`--issued-at <issued-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. The date ON the document — when the merchant issued it, not when this row was written. It is the date a buyer sorts their invoices by and the one that appears in a tax return, which is why it is a date and not a timestamp: a document is issued on a day.`)
  .option(`--due-date <due-date>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When the amount on this document is due. Only some kinds carry one — an invoice does, a delivery note does not — so it is nullable, and nothing in this app dunns on it.`)
  .option(`--total-amount <total-amount>`, `Filter to rows whose \`total_amount\` is exactly this value. The gross amount printed on the document, in \`currency\`. A COPY of what the document says, kept so a list can show it without fetching the file — it is not recomputed here and never corrects the document. Nullable: a delivery note carries no amount.`, parseInteger)
  .option(`--currency <currency>`, `Filter to rows whose \`currency\` is exactly this value. The ISO 4217 code the amount is in. Nullable exactly where the amount is, and carried per document rather than per tenant because a merchant selling across markets issues in more than one.`)
  .option(`--visibility <visibility>`, `Filter by who may read the document. A storefront caller is confined to 'customer' whatever it sends here, so this selector narrows an operator's list and can never widen a buyer's.`)
  .option(`--external-id <external-id>`, `Look a document up by the key the system that issued it knows it by — what a feed does before deciding between a create and an update. Unique per tenant, so this answers at most one document.`)
  .option(`--source-synced-at <source-synced-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.`)
  .option(`--created-at <created-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.`)
  .option(`--updated-at <updated-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When the row was last written. Server-set — every route that changes this row stamps it.`)
  .option(`--limit <limit>`, `Page size (default 50, max 200). A larger value is clamped rather than refused.`, parseInteger)
  .option(`--offset <offset>`, `Row offset for pagination (default 0). Page with \`page.total\` and \`page.hasMore\`.`, parseInteger)
  .option(`--order <order>`, `Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, entityType, entityId, kind, number, source, storageAssetId, deliveryPath, externalUrl, filename, contentType, byteSize, issuedAt, dueDate, totalAmount, currency, visibility, externalId, sourceSyncedAt, createdAt, updatedAt, limit, offset, order, filter } = await promptForMissing(
          _options,
          documentsDocumentsListSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/documents`;
        const _payload: RequestParams = {};
        if (id !== undefined) {
          _payload[`id`] = id;
        }
        if (entityType !== undefined) {
          _payload[`entity_type`] = entityType;
        }
        if (entityId !== undefined) {
          _payload[`entity_id`] = entityId;
        }
        if (kind !== undefined) {
          _payload[`kind`] = kind;
        }
        if (number !== undefined) {
          _payload[`number`] = number;
        }
        if (source !== undefined) {
          _payload[`source`] = source;
        }
        if (storageAssetId !== undefined) {
          _payload[`storage_asset_id`] = storageAssetId;
        }
        if (deliveryPath !== undefined) {
          _payload[`delivery_path`] = deliveryPath;
        }
        if (externalUrl !== undefined) {
          _payload[`external_url`] = externalUrl;
        }
        if (filename !== undefined) {
          _payload[`filename`] = filename;
        }
        if (contentType !== undefined) {
          _payload[`content_type`] = contentType;
        }
        if (byteSize !== undefined) {
          _payload[`byte_size`] = byteSize;
        }
        if (issuedAt !== undefined) {
          _payload[`issued_at`] = issuedAt;
        }
        if (dueDate !== undefined) {
          _payload[`due_date`] = dueDate;
        }
        if (totalAmount !== undefined) {
          _payload[`total_amount`] = totalAmount;
        }
        if (currency !== undefined) {
          _payload[`currency`] = currency;
        }
        if (visibility !== undefined) {
          _payload[`visibility`] = visibility;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        if (updatedAt !== undefined) {
          _payload[`updated_at`] = updatedAt;
        }
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        if (order !== undefined) {
          _payload[`order`] = order;
        }
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsRegister.commands.at(-1)!, documentsDocumentsListSpecs, { method: "get" });
const documentsDocumentsCreateSpecs: PromptSpec[] = [
  { key: "entityId", option: "--entity-id <entity-id>", name: "entity_id", description: "WHICH transaction this document belongs to — the id of the order, as the orders app knows it. Nothing here checks that the transaction exists: it lives in another app, and a register that called it on every write would fail a whole feed for one deleted order. Together with `entity_type` this is the filter an account area reads a buyer's papers with.", type: "string", required: true },
  { key: "entityType", option: "--entity-type <entity-type>", name: "entity_type", description: "WHAT KIND of transaction this document belongs to. `order` is the only value this app accepts today, and a write naming anything else is refused with a message listing what is accepted. The column carries no database constraint on purpose: a return receipt hangs off a return, a contract off an organization and a certificate off a product, so the next kind of owner is a release of this app rather than a migration.", type: "string", required: true },
  { key: "filename", option: "--filename <filename>", name: "filename", description: "What the file is called — the name a person is offered when they download it, and the only thing the register has to show them. Required, at least one character: a row that names no file is an offer of a download nobody can complete.", type: "string", required: true },
  { key: "kind", option: "--kind <kind>", name: "kind", description: "What kind of record this is, as a code from GET /documents/kinds — `invoice`, `delivery_note`, `credit_note`, `return_receipt` on a fresh install, plus whatever the merchant added. The check is a membership test against the tenant's own table and NOT a database constraint, because a merchant adds a proforma invoice or a dunning letter without a release of this app. A code the tenant does not keep is refused with 400 and the list of the ones they do.", type: "string", required: true },
  { key: "byteSize", option: "--byte-size <byte-size>", name: "byte_size", description: "How large the file is, in bytes — what a download link shows next to it. Nullable, and never computed here: this app does not read the bytes.", type: "integer", required: false },
  { key: "contentType", option: "--content-type <content-type>", name: "content_type", description: "The media type of the file, so a client knows whether to open it or hand it to the browser. Nullable, because a feed does not always say.", type: "string", required: false },
  { key: "currency", option: "--currency <currency>", name: "currency", description: "The ISO 4217 code the amount is in. Nullable exactly where the amount is, and carried per document rather than per tenant because a merchant selling across markets issues in more than one.", type: "string", required: false },
  { key: "deliveryPath", option: "--delivery-path <delivery-path>", name: "delivery_path", description: "Where the stored file is served from today — a CDN path, and a CACHE of an address rather than an authorisation. Do NOT fetch a document with it: a path is not a permission, so it answers a private asset with 403, and it is stale the moment the file moves. POST /documents/documents/{id}/link is the way to get the bytes; this column is kept for an operator tracing an object through the delivery plane. Null for an external document.", type: "string", required: false },
  { key: "dueDate", option: "--due-date <due-date>", name: "due_date", description: "When the amount on this document is due. Only some kinds carry one — an invoice does, a delivery note does not — so it is nullable, and nothing in this app dunns on it.", type: "string", required: false },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "The key this document has in the system that ISSUED it — a finance system, a warehouse. Unique per tenant, and the key this register recognises a feed's own rows by: a write carrying one this tenant already holds UPDATES that document and answers 200 instead of filing a second copy. The document number is deliberately NOT that key, because a merchant may renumber and one number may cover an invoice and its delivery note.", type: "string", required: false },
  { key: "externalRefs", option: "--external-refs <external-refs>", name: "external_refs", description: "Every OTHER system that knows this row, keyed by system name. `external_id` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on `metadata`.", type: "object", required: false },
  { key: "externalUrl", option: "--external-url <external-url>", name: "external_url", description: "The address of a file this platform does not hold. Required while `source` is 'external' and null otherwise. It is the tenant's own host — a document archive, a finance system's portal — and this app stores the address without fetching it.", type: "string", required: false },
  { key: "issuedAt", option: "--issued-at <issued-at>", name: "issued_at", description: "The date ON the document — when the merchant issued it, not when this row was written. It is the date a buyer sorts their invoices by and the one that appears in a tax return, which is why it is a date and not a timestamp: a document is issued on a day.", type: "string", required: false },
  { key: "metadata", option: "--metadata <metadata>", name: "metadata", description: "Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so `?metadata=erp` is refused with 400 `invalid_value` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.", type: "object", required: false },
  { key: "number", option: "--number <number>", name: "number", description: "The number printed on the document — what a customer quotes when they call about it, and what a service desk searches for. The DOCUMENT's own number, not the order's: an invoice and its credit note carry different ones. Nullable, because a delivery note is not always numbered, and NOT unique: a merchant who issues an invoice and its delivery note under one number is ordinary practice, and the source key is what identifies a row instead.", type: "string", required: false },
  { key: "source", option: "--source <source>", name: "source", description: "WHERE the bytes are, and which of the two address columns is filled. 'storage' — an asset this platform holds, addressed by `storage_asset_id`, and the only case POST /documents/documents/{id}/link can hand over: the bucket is private, so the link is a signed, short-lived URL. 'external' — a file on a host the tenant runs, addressed by `external_url`, which this app neither fetches nor signs. The database pairs them: `(source = 'storage' AND storage_asset_id IS NOT NULL) OR (source = 'external' AND external_url IS NOT NULL)`, the same CHECK the product assets carry, so neither pairing can be half-filled. It is a discriminator rather than a preference. Defaults to 'storage'.", type: "string", required: false, enum: ["storage","external"] },
  { key: "sourceData", option: "--source-data <source-data>", name: "source_data", description: "What the source said about this row, kept as it said it. Carries the ETag a write-back has to return in `If-Match`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on `metadata`.", type: "object", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.", type: "string", required: false },
  { key: "storageAssetId", option: "--storage-asset-id <storage-asset-id>", name: "storage_asset_id", description: "The stable identity of the stored file, as the platform's storage service issued it. Required while `source` is 'storage' and null otherwise. It is the IDENTITY, not an address: it survives a move or a rename, which `delivery_path` does not, and it is what POST /documents/documents/{id}/link signs. The file is uploaded by whoever ISSUES the document — this app stores no bytes and has no upload route.", type: "string", required: false },
  { key: "totalAmount", option: "--total-amount <total-amount>", name: "total_amount", description: "The gross amount printed on the document, in `currency`. A COPY of what the document says, kept so a list can show it without fetching the file — it is not recomputed here and never corrects the document. Nullable: a delivery note carries no amount.", type: "number", required: false },
  { key: "visibility", option: "--visibility <visibility>", name: "visibility", description: "Who may read this document. 'customer' — the buyer may, which is what an account area shows and the column's default, because a document a finance system issues to a customer is the normal case. 'internal' — the merchant's side only: a margin sheet, a supplier confirmation, a credit note still being argued about. A storefront caller is confined to 'customer' IN THE QUERY, so an internal document is absent from its list, absent from its page total and answered 404 at its own address. This is the one value in this app that, set wrongly, shows a buyer another buyer's invoice. Defaults to 'customer'.", type: "string", required: false, enum: ["internal","customer"] },
];
documentsRegister
  .command(`documents-documents-create`)
  .description(`A document is one record a merchant issued and filed against a transaction — an invoice, a delivery note, a credit note, a return receipt. The row is the REGISTER entry: it says which transaction the document belongs to, what kind of record it is, the number a customer quotes, who may read it and where its bytes live. It never holds the bytes, and this app never produces a document. This route is written for a FEED, because a feed re-runs: a body carrying an \`external_id\` this tenant already holds UPDATES that document and answers 200, and a body with none is a plain create and answers 201. That is what stops a retry, a restart or a full re-sync showing a buyer one invoice three times; the unique index behind \`external_id\` is the net under it rather than the mechanism. Four fields are owed — \`entity_type\`, \`entity_id\`, \`kind\` and \`filename\` — and two are decided for you: \`source\` defaults to 'storage' and \`visibility\` to 'customer', because a document a finance system issues to a customer is the normal case. Three refusals are worth knowing before the first call: \`entity_type\` accepts \`order\` and nothing else yet and its refusal NAMES what it accepts, \`kind\` has to be one this tenant keeps (GET /documents/kinds) and its refusal lists them, and the byte binding is the database's — \`source: 'storage'\` needs a \`storage_asset_id\`, \`source: 'external'\` an \`external_url\`.`)
  .option(`--entity-id <entity-id>`, `WHICH transaction this document belongs to — the id of the order, as the orders app knows it. Nothing here checks that the transaction exists: it lives in another app, and a register that called it on every write would fail a whole feed for one deleted order. Together with \`entity_type\` this is the filter an account area reads a buyer's papers with.`)
  .option(`--entity-type <entity-type>`, `WHAT KIND of transaction this document belongs to. \`order\` is the only value this app accepts today, and a write naming anything else is refused with a message listing what is accepted. The column carries no database constraint on purpose: a return receipt hangs off a return, a contract off an organization and a certificate off a product, so the next kind of owner is a release of this app rather than a migration.`)
  .option(`--filename <filename>`, `What the file is called — the name a person is offered when they download it, and the only thing the register has to show them. Required, at least one character: a row that names no file is an offer of a download nobody can complete.`)
  .option(`--kind <kind>`, `What kind of record this is, as a code from GET /documents/kinds — \`invoice\`, \`delivery_note\`, \`credit_note\`, \`return_receipt\` on a fresh install, plus whatever the merchant added. The check is a membership test against the tenant's own table and NOT a database constraint, because a merchant adds a proforma invoice or a dunning letter without a release of this app. A code the tenant does not keep is refused with 400 and the list of the ones they do.`)
  .option(`--byte-size <byte-size>`, `How large the file is, in bytes — what a download link shows next to it. Nullable, and never computed here: this app does not read the bytes.`, parseInteger)
  .option(`--content-type <content-type>`, `The media type of the file, so a client knows whether to open it or hand it to the browser. Nullable, because a feed does not always say.`)
  .option(`--currency <currency>`, `The ISO 4217 code the amount is in. Nullable exactly where the amount is, and carried per document rather than per tenant because a merchant selling across markets issues in more than one.`)
  .option(`--delivery-path <delivery-path>`, `Where the stored file is served from today — a CDN path, and a CACHE of an address rather than an authorisation. Do NOT fetch a document with it: a path is not a permission, so it answers a private asset with 403, and it is stale the moment the file moves. POST /documents/documents/{id}/link is the way to get the bytes; this column is kept for an operator tracing an object through the delivery plane. Null for an external document.`)
  .option(`--due-date <due-date>`, `When the amount on this document is due. Only some kinds carry one — an invoice does, a delivery note does not — so it is nullable, and nothing in this app dunns on it.`)
  .option(`--external-id <external-id>`, `The key this document has in the system that ISSUED it — a finance system, a warehouse. Unique per tenant, and the key this register recognises a feed's own rows by: a write carrying one this tenant already holds UPDATES that document and answers 200 instead of filing a second copy. The document number is deliberately NOT that key, because a merchant may renumber and one number may cover an invoice and its delivery note.`)
  .option(`--external-refs <external-refs>`, `Every OTHER system that knows this row, keyed by system name. \`external_id\` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on \`metadata\`.`)
  .option(`--external-url <external-url>`, `The address of a file this platform does not hold. Required while \`source\` is 'external' and null otherwise. It is the tenant's own host — a document archive, a finance system's portal — and this app stores the address without fetching it.`)
  .option(`--issued-at <issued-at>`, `The date ON the document — when the merchant issued it, not when this row was written. It is the date a buyer sorts their invoices by and the one that appears in a tax return, which is why it is a date and not a timestamp: a document is issued on a day.`)
  .option(`--metadata <metadata>`, `Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so \`?metadata=erp\` is refused with 400 \`invalid_value\` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.`)
  .option(`--number <number>`, `The number printed on the document — what a customer quotes when they call about it, and what a service desk searches for. The DOCUMENT's own number, not the order's: an invoice and its credit note carry different ones. Nullable, because a delivery note is not always numbered, and NOT unique: a merchant who issues an invoice and its delivery note under one number is ordinary practice, and the source key is what identifies a row instead.`)
  .option(`--source <source>`, `WHERE the bytes are, and which of the two address columns is filled. 'storage' — an asset this platform holds, addressed by \`storage_asset_id\`, and the only case POST /documents/documents/{id}/link can hand over: the bucket is private, so the link is a signed, short-lived URL. 'external' — a file on a host the tenant runs, addressed by \`external_url\`, which this app neither fetches nor signs. The database pairs them: \`(source = 'storage' AND storage_asset_id IS NOT NULL) OR (source = 'external' AND external_url IS NOT NULL)\`, the same CHECK the product assets carry, so neither pairing can be half-filled. It is a discriminator rather than a preference. Defaults to 'storage'.`)
  .option(`--source-data <source-data>`, `What the source said about this row, kept as it said it. Carries the ETag a write-back has to return in \`If-Match\`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on \`metadata\`.`)
  .option(`--source-synced-at <source-synced-at>`, `When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.`)
  .option(`--storage-asset-id <storage-asset-id>`, `The stable identity of the stored file, as the platform's storage service issued it. Required while \`source\` is 'storage' and null otherwise. It is the IDENTITY, not an address: it survives a move or a rename, which \`delivery_path\` does not, and it is what POST /documents/documents/{id}/link signs. The file is uploaded by whoever ISSUES the document — this app stores no bytes and has no upload route.`)
  .option(`--total-amount <total-amount>`, `The gross amount printed on the document, in \`currency\`. A COPY of what the document says, kept so a list can show it without fetching the file — it is not recomputed here and never corrects the document. Nullable: a delivery note carries no amount.`, parseInteger)
  .option(`--visibility <visibility>`, `Who may read this document. 'customer' — the buyer may, which is what an account area shows and the column's default, because a document a finance system issues to a customer is the normal case. 'internal' — the merchant's side only: a margin sheet, a supplier confirmation, a credit note still being argued about. A storefront caller is confined to 'customer' IN THE QUERY, so an internal document is absent from its list, absent from its page total and answered 404 at its own address. This is the one value in this app that, set wrongly, shows a buyer another buyer's invoice. Defaults to 'customer'.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { entityId, entityType, filename, kind, byteSize, contentType, currency, deliveryPath, dueDate, externalId, externalRefs, externalUrl, issuedAt, metadata, number, source, sourceData, sourceSyncedAt, storageAssetId, totalAmount, visibility } = await promptForMissing(
          _options,
          documentsDocumentsCreateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/documents`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (byteSize !== undefined) {
          _payload[`byte_size`] = byteSize;
        }
        if (contentType !== undefined) {
          _payload[`content_type`] = contentType;
        }
        if (currency !== undefined) {
          _payload[`currency`] = currency;
        }
        if (deliveryPath !== undefined) {
          _payload[`delivery_path`] = deliveryPath;
        }
        if (dueDate !== undefined) {
          _payload[`due_date`] = dueDate;
        }
        if (entityId !== undefined) {
          _payload[`entity_id`] = entityId;
        }
        if (entityType !== undefined) {
          _payload[`entity_type`] = entityType;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (externalRefs !== undefined) {
          _payload[`external_refs`] = resolveBodyParam(externalRefs);
        }
        if (externalUrl !== undefined) {
          _payload[`external_url`] = externalUrl;
        }
        if (filename !== undefined) {
          _payload[`filename`] = filename;
        }
        if (issuedAt !== undefined) {
          _payload[`issued_at`] = issuedAt;
        }
        if (kind !== undefined) {
          _payload[`kind`] = kind;
        }
        if (metadata !== undefined) {
          _payload[`metadata`] = resolveBodyParam(metadata);
        }
        if (number !== undefined) {
          _payload[`number`] = number;
        }
        if (source !== undefined) {
          _payload[`source`] = source;
        }
        if (sourceData !== undefined) {
          _payload[`source_data`] = resolveBodyParam(sourceData);
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        if (storageAssetId !== undefined) {
          _payload[`storage_asset_id`] = storageAssetId;
        }
        if (totalAmount !== undefined) {
          _payload[`total_amount`] = totalAmount;
        }
        if (visibility !== undefined) {
          _payload[`visibility`] = visibility;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsRegister.commands.at(-1)!, documentsDocumentsCreateSpecs, { method: "post" });
const documentsDocumentsDeleteSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The document to remove.", type: "string", required: true, resource: { listPath: "/documents/documents", hasLimit: true } },
];
documentsRegister
  .command(`documents-documents-delete`)
  .description(`A document is one record a merchant issued and filed against a transaction — an invoice, a delivery note, a credit note, a return receipt. The row is the REGISTER entry: it says which transaction the document belongs to, what kind of record it is, the number a customer quotes, who may read it and where its bytes live. It never holds the bytes, and this app never produces a document. Deleting the register entry does NOT delete the file: the bytes live in the platform's asset storage or on the tenant's own host, and this app has never held them. So this is "stop offering this document", not "destroy it" — and there is no undo here, because the row carried the only record of which transaction the file belonged to. A feed that still knows the document will re-file it on its next run, under the same \`external_id\`.`)
  .option(`--id <id>`, `The document to remove.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          documentsDocumentsDeleteSpecs,
          _command,
        );
        await confirmDestructive(`documents-register documents-documents-delete`);
        const _client = await sdkForProject();
        const _apiPath = `/documents/documents/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `delete`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsRegister.commands.at(-1)!, documentsDocumentsDeleteSpecs, { method: "delete", destructive: true });
const documentsDocumentsGetSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The document to read.", type: "string", required: true, resource: { listPath: "/documents/documents", hasLimit: true } },
];
documentsRegister
  .command(`documents-documents-get`)
  .description(`A document is one record a merchant issued and filed against a transaction — an invoice, a delivery note, a credit note, a return receipt. The row is the REGISTER entry: it says which transaction the document belongs to, what kind of record it is, the number a customer quotes, who may read it and where its bytes live. It never holds the bytes, and this app never produces a document. This is the route that turns an id back into a document, and the one place the visibility promise is easiest to get wrong: an \`internal\` document answers 404 to a storefront caller rather than 403, because a refusal that admitted the document exists would confirm what a guessed address was fishing for. An operator reads the same row at the same address.`)
  .option(`--id <id>`, `The document to read.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          documentsDocumentsGetSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/documents/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsRegister.commands.at(-1)!, documentsDocumentsGetSpecs, { method: "get" });
const documentsDocumentsUpdateSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The document to edit.", type: "string", required: true, resource: { listPath: "/documents/documents", hasLimit: true } },
  { key: "byteSize", option: "--byte-size <byte-size>", name: "byte_size", description: "How large the file is, in bytes — what a download link shows next to it. Nullable, and never computed here: this app does not read the bytes.", type: "integer", required: false },
  { key: "contentType", option: "--content-type <content-type>", name: "content_type", description: "The media type of the file, so a client knows whether to open it or hand it to the browser. Nullable, because a feed does not always say.", type: "string", required: false },
  { key: "currency", option: "--currency <currency>", name: "currency", description: "The ISO 4217 code the amount is in. Nullable exactly where the amount is, and carried per document rather than per tenant because a merchant selling across markets issues in more than one.", type: "string", required: false },
  { key: "deliveryPath", option: "--delivery-path <delivery-path>", name: "delivery_path", description: "Where the stored file is served from today — a CDN path, and a CACHE of an address rather than an authorisation. Do NOT fetch a document with it: a path is not a permission, so it answers a private asset with 403, and it is stale the moment the file moves. POST /documents/documents/{id}/link is the way to get the bytes; this column is kept for an operator tracing an object through the delivery plane. Null for an external document.", type: "string", required: false },
  { key: "dueDate", option: "--due-date <due-date>", name: "due_date", description: "When the amount on this document is due. Only some kinds carry one — an invoice does, a delivery note does not — so it is nullable, and nothing in this app dunns on it.", type: "string", required: false },
  { key: "entityId", option: "--entity-id <entity-id>", name: "entity_id", description: "WHICH transaction this document belongs to — the id of the order, as the orders app knows it. Nothing here checks that the transaction exists: it lives in another app, and a register that called it on every write would fail a whole feed for one deleted order. Together with `entity_type` this is the filter an account area reads a buyer's papers with.", type: "string", required: false },
  { key: "entityType", option: "--entity-type <entity-type>", name: "entity_type", description: "WHAT KIND of transaction this document belongs to. `order` is the only value this app accepts today, and a write naming anything else is refused with a message listing what is accepted. The column carries no database constraint on purpose: a return receipt hangs off a return, a contract off an organization and a certificate off a product, so the next kind of owner is a release of this app rather than a migration.", type: "string", required: false },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "The key this document has in the system that ISSUED it — a finance system, a warehouse. Unique per tenant, and the key this register recognises a feed's own rows by: a write carrying one this tenant already holds UPDATES that document and answers 200 instead of filing a second copy. The document number is deliberately NOT that key, because a merchant may renumber and one number may cover an invoice and its delivery note.", type: "string", required: false },
  { key: "externalRefs", option: "--external-refs <external-refs>", name: "external_refs", description: "Every OTHER system that knows this row, keyed by system name. `external_id` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on `metadata`.", type: "object", required: false },
  { key: "externalUrl", option: "--external-url <external-url>", name: "external_url", description: "The address of a file this platform does not hold. Required while `source` is 'external' and null otherwise. It is the tenant's own host — a document archive, a finance system's portal — and this app stores the address without fetching it.", type: "string", required: false },
  { key: "filename", option: "--filename <filename>", name: "filename", description: "What the file is called — the name a person is offered when they download it, and the only thing the register has to show them. Required, at least one character: a row that names no file is an offer of a download nobody can complete.", type: "string", required: false },
  { key: "issuedAt", option: "--issued-at <issued-at>", name: "issued_at", description: "The date ON the document — when the merchant issued it, not when this row was written. It is the date a buyer sorts their invoices by and the one that appears in a tax return, which is why it is a date and not a timestamp: a document is issued on a day.", type: "string", required: false },
  { key: "kind", option: "--kind <kind>", name: "kind", description: "What kind of record this is, as a code from GET /documents/kinds — `invoice`, `delivery_note`, `credit_note`, `return_receipt` on a fresh install, plus whatever the merchant added. The check is a membership test against the tenant's own table and NOT a database constraint, because a merchant adds a proforma invoice or a dunning letter without a release of this app. A code the tenant does not keep is refused with 400 and the list of the ones they do.", type: "string", required: false },
  { key: "metadata", option: "--metadata <metadata>", name: "metadata", description: "Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so `?metadata=erp` is refused with 400 `invalid_value` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.", type: "object", required: false },
  { key: "number", option: "--number <number>", name: "number", description: "The number printed on the document — what a customer quotes when they call about it, and what a service desk searches for. The DOCUMENT's own number, not the order's: an invoice and its credit note carry different ones. Nullable, because a delivery note is not always numbered, and NOT unique: a merchant who issues an invoice and its delivery note under one number is ordinary practice, and the source key is what identifies a row instead.", type: "string", required: false },
  { key: "source", option: "--source <source>", name: "source", description: "WHERE the bytes are, and which of the two address columns is filled. 'storage' — an asset this platform holds, addressed by `storage_asset_id`, and the only case POST /documents/documents/{id}/link can hand over: the bucket is private, so the link is a signed, short-lived URL. 'external' — a file on a host the tenant runs, addressed by `external_url`, which this app neither fetches nor signs. The database pairs them: `(source = 'storage' AND storage_asset_id IS NOT NULL) OR (source = 'external' AND external_url IS NOT NULL)`, the same CHECK the product assets carry, so neither pairing can be half-filled. It is a discriminator rather than a preference. Defaults to 'storage'.", type: "string", required: false, enum: ["storage","external"] },
  { key: "sourceData", option: "--source-data <source-data>", name: "source_data", description: "What the source said about this row, kept as it said it. Carries the ETag a write-back has to return in `If-Match`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on `metadata`.", type: "object", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.", type: "string", required: false },
  { key: "storageAssetId", option: "--storage-asset-id <storage-asset-id>", name: "storage_asset_id", description: "The stable identity of the stored file, as the platform's storage service issued it. Required while `source` is 'storage' and null otherwise. It is the IDENTITY, not an address: it survives a move or a rename, which `delivery_path` does not, and it is what POST /documents/documents/{id}/link signs. The file is uploaded by whoever ISSUES the document — this app stores no bytes and has no upload route.", type: "string", required: false },
  { key: "totalAmount", option: "--total-amount <total-amount>", name: "total_amount", description: "The gross amount printed on the document, in `currency`. A COPY of what the document says, kept so a list can show it without fetching the file — it is not recomputed here and never corrects the document. Nullable: a delivery note carries no amount.", type: "number", required: false },
  { key: "visibility", option: "--visibility <visibility>", name: "visibility", description: "Who may read this document. 'customer' — the buyer may, which is what an account area shows and the column's default, because a document a finance system issues to a customer is the normal case. 'internal' — the merchant's side only: a margin sheet, a supplier confirmation, a credit note still being argued about. A storefront caller is confined to 'customer' IN THE QUERY, so an internal document is absent from its list, absent from its page total and answered 404 at its own address. This is the one value in this app that, set wrongly, shows a buyer another buyer's invoice. Defaults to 'customer'.", type: "string", required: false, enum: ["internal","customer"] },
];
documentsRegister
  .command(`documents-documents-update`)
  .description(`A document is one record a merchant issued and filed against a transaction — an invoice, a delivery note, a credit note, a return receipt. The row is the REGISTER entry: it says which transaction the document belongs to, what kind of record it is, the number a customer quotes, who may read it and where its bytes live. It never holds the bytes, and this app never produces a document. A partial update: omitted fields keep their value, and a body carrying no field at all is refused rather than answered as a no-op. The provenance columns are the ones to leave alone — \`source_data\` holds the ETag a write-back to the issuing system has to return, and an edit here does not touch it, so what the source said survives being re-filed as internal. The same guards as the create apply to \`entity_type\`, \`kind\` and the byte binding, and an internal document is a 404 to a storefront caller here too.`)
  .option(`--id <id>`, `The document to edit.`)
  .option(`--byte-size <byte-size>`, `How large the file is, in bytes — what a download link shows next to it. Nullable, and never computed here: this app does not read the bytes.`, parseInteger)
  .option(`--content-type <content-type>`, `The media type of the file, so a client knows whether to open it or hand it to the browser. Nullable, because a feed does not always say.`)
  .option(`--currency <currency>`, `The ISO 4217 code the amount is in. Nullable exactly where the amount is, and carried per document rather than per tenant because a merchant selling across markets issues in more than one.`)
  .option(`--delivery-path <delivery-path>`, `Where the stored file is served from today — a CDN path, and a CACHE of an address rather than an authorisation. Do NOT fetch a document with it: a path is not a permission, so it answers a private asset with 403, and it is stale the moment the file moves. POST /documents/documents/{id}/link is the way to get the bytes; this column is kept for an operator tracing an object through the delivery plane. Null for an external document.`)
  .option(`--due-date <due-date>`, `When the amount on this document is due. Only some kinds carry one — an invoice does, a delivery note does not — so it is nullable, and nothing in this app dunns on it.`)
  .option(`--entity-id <entity-id>`, `WHICH transaction this document belongs to — the id of the order, as the orders app knows it. Nothing here checks that the transaction exists: it lives in another app, and a register that called it on every write would fail a whole feed for one deleted order. Together with \`entity_type\` this is the filter an account area reads a buyer's papers with.`)
  .option(`--entity-type <entity-type>`, `WHAT KIND of transaction this document belongs to. \`order\` is the only value this app accepts today, and a write naming anything else is refused with a message listing what is accepted. The column carries no database constraint on purpose: a return receipt hangs off a return, a contract off an organization and a certificate off a product, so the next kind of owner is a release of this app rather than a migration.`)
  .option(`--external-id <external-id>`, `The key this document has in the system that ISSUED it — a finance system, a warehouse. Unique per tenant, and the key this register recognises a feed's own rows by: a write carrying one this tenant already holds UPDATES that document and answers 200 instead of filing a second copy. The document number is deliberately NOT that key, because a merchant may renumber and one number may cover an invoice and its delivery note.`)
  .option(`--external-refs <external-refs>`, `Every OTHER system that knows this row, keyed by system name. \`external_id\` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on \`metadata\`.`)
  .option(`--external-url <external-url>`, `The address of a file this platform does not hold. Required while \`source\` is 'external' and null otherwise. It is the tenant's own host — a document archive, a finance system's portal — and this app stores the address without fetching it.`)
  .option(`--filename <filename>`, `What the file is called — the name a person is offered when they download it, and the only thing the register has to show them. Required, at least one character: a row that names no file is an offer of a download nobody can complete.`)
  .option(`--issued-at <issued-at>`, `The date ON the document — when the merchant issued it, not when this row was written. It is the date a buyer sorts their invoices by and the one that appears in a tax return, which is why it is a date and not a timestamp: a document is issued on a day.`)
  .option(`--kind <kind>`, `What kind of record this is, as a code from GET /documents/kinds — \`invoice\`, \`delivery_note\`, \`credit_note\`, \`return_receipt\` on a fresh install, plus whatever the merchant added. The check is a membership test against the tenant's own table and NOT a database constraint, because a merchant adds a proforma invoice or a dunning letter without a release of this app. A code the tenant does not keep is refused with 400 and the list of the ones they do.`)
  .option(`--metadata <metadata>`, `Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so \`?metadata=erp\` is refused with 400 \`invalid_value\` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.`)
  .option(`--number <number>`, `The number printed on the document — what a customer quotes when they call about it, and what a service desk searches for. The DOCUMENT's own number, not the order's: an invoice and its credit note carry different ones. Nullable, because a delivery note is not always numbered, and NOT unique: a merchant who issues an invoice and its delivery note under one number is ordinary practice, and the source key is what identifies a row instead.`)
  .option(`--source <source>`, `WHERE the bytes are, and which of the two address columns is filled. 'storage' — an asset this platform holds, addressed by \`storage_asset_id\`, and the only case POST /documents/documents/{id}/link can hand over: the bucket is private, so the link is a signed, short-lived URL. 'external' — a file on a host the tenant runs, addressed by \`external_url\`, which this app neither fetches nor signs. The database pairs them: \`(source = 'storage' AND storage_asset_id IS NOT NULL) OR (source = 'external' AND external_url IS NOT NULL)\`, the same CHECK the product assets carry, so neither pairing can be half-filled. It is a discriminator rather than a preference. Defaults to 'storage'.`)
  .option(`--source-data <source-data>`, `What the source said about this row, kept as it said it. Carries the ETag a write-back has to return in \`If-Match\`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on \`metadata\`.`)
  .option(`--source-synced-at <source-synced-at>`, `When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.`)
  .option(`--storage-asset-id <storage-asset-id>`, `The stable identity of the stored file, as the platform's storage service issued it. Required while \`source\` is 'storage' and null otherwise. It is the IDENTITY, not an address: it survives a move or a rename, which \`delivery_path\` does not, and it is what POST /documents/documents/{id}/link signs. The file is uploaded by whoever ISSUES the document — this app stores no bytes and has no upload route.`)
  .option(`--total-amount <total-amount>`, `The gross amount printed on the document, in \`currency\`. A COPY of what the document says, kept so a list can show it without fetching the file — it is not recomputed here and never corrects the document. Nullable: a delivery note carries no amount.`, parseInteger)
  .option(`--visibility <visibility>`, `Who may read this document. 'customer' — the buyer may, which is what an account area shows and the column's default, because a document a finance system issues to a customer is the normal case. 'internal' — the merchant's side only: a margin sheet, a supplier confirmation, a credit note still being argued about. A storefront caller is confined to 'customer' IN THE QUERY, so an internal document is absent from its list, absent from its page total and answered 404 at its own address. This is the one value in this app that, set wrongly, shows a buyer another buyer's invoice. Defaults to 'customer'.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, byteSize, contentType, currency, deliveryPath, dueDate, entityId, entityType, externalId, externalRefs, externalUrl, filename, issuedAt, kind, metadata, number, source, sourceData, sourceSyncedAt, storageAssetId, totalAmount, visibility } = await promptForMissing(
          _options,
          documentsDocumentsUpdateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/documents/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (byteSize !== undefined) {
          _payload[`byte_size`] = byteSize;
        }
        if (contentType !== undefined) {
          _payload[`content_type`] = contentType;
        }
        if (currency !== undefined) {
          _payload[`currency`] = currency;
        }
        if (deliveryPath !== undefined) {
          _payload[`delivery_path`] = deliveryPath;
        }
        if (dueDate !== undefined) {
          _payload[`due_date`] = dueDate;
        }
        if (entityId !== undefined) {
          _payload[`entity_id`] = entityId;
        }
        if (entityType !== undefined) {
          _payload[`entity_type`] = entityType;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (externalRefs !== undefined) {
          _payload[`external_refs`] = resolveBodyParam(externalRefs);
        }
        if (externalUrl !== undefined) {
          _payload[`external_url`] = externalUrl;
        }
        if (filename !== undefined) {
          _payload[`filename`] = filename;
        }
        if (issuedAt !== undefined) {
          _payload[`issued_at`] = issuedAt;
        }
        if (kind !== undefined) {
          _payload[`kind`] = kind;
        }
        if (metadata !== undefined) {
          _payload[`metadata`] = resolveBodyParam(metadata);
        }
        if (number !== undefined) {
          _payload[`number`] = number;
        }
        if (source !== undefined) {
          _payload[`source`] = source;
        }
        if (sourceData !== undefined) {
          _payload[`source_data`] = resolveBodyParam(sourceData);
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        if (storageAssetId !== undefined) {
          _payload[`storage_asset_id`] = storageAssetId;
        }
        if (totalAmount !== undefined) {
          _payload[`total_amount`] = totalAmount;
        }
        if (visibility !== undefined) {
          _payload[`visibility`] = visibility;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `put`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsRegister.commands.at(-1)!, documentsDocumentsUpdateSpecs, { method: "put" });
const documentsDocumentsLinkSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The document to mint a link for.", type: "string", required: true, resource: { listPath: "/documents/documents", hasLimit: true } },
];
documentsRegister
  .command(`documents-documents-link`)
  .description(`A document is one record a merchant issued and filed against a transaction — an invoice, a delivery note, a credit note, a return receipt. The row is the REGISTER entry: it says which transaction the document belongs to, what kind of record it is, the number a customer quotes, who may read it and where its bytes live. It never holds the bytes, and this app never produces a document. This is how the bytes are handed over, and the ONLY way: the storage bucket is private, so the answer is a signed URL valid for minutes, which the caller then fetches directly. Nothing streams through this app — a 40 MB invoice through a function with a 15-second timeout is a bad trade, and the signature is the authorisation, so proxying it would add a second copy of a check that is already in the URL. There is no upload route for the same reason in reverse: whoever ISSUES the document uploads it to POST /v1/storage/assets itself, takes the \`ast_…\` id back and records it here. It is a POST because each call mints a new signature with a new expiry, so the answer must not be cached. ⚠ The AUDIENCE RULE applies here exactly as it does at the document's own address: a storefront caller asking for a link to an \`internal\` document is answered 404 — not 403 — because a link is the one thing that would turn a guessed id into another buyer's invoice. An \`external\` document has no asset of ours to sign and is refused with its \`external_url\` instead.`)
  .option(`--id <id>`, `The document to mint a link for.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          documentsDocumentsLinkSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/documents/documents/{id}/link`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(documentsRegister.commands.at(-1)!, documentsDocumentsLinkSpecs, { method: "post" });
