import { Command } from "commander";
import { resolveBodyParam } from "../../utils.js";
import { sdkForProject } from "../../sdks.js";
import type { RequestParams } from "../../types.js";
import {
  actionRunner,
  commandDescriptions,
  cliConfig,
  parse,
  parseInteger,
} from "../../parser.js";
import {
  confirmDestructive,
  promptForMissing,
  type PromptSpec,
  registerPromptSpecs,
} from "../../interactive.js";

export const productsCategories = new Command("products-categories")
  .description(
    commandDescriptions["productsCategories"] ??
      `The category tree and how products get into it. The nodes themselves, the memberships that file a product into a node — hand-picked or materialized by a rule — and the rule engine that maintains the second kind: preview a selector before storing it, recompute one category, or recompute every category that carries rules. Read this group when the question is "which products are in this category, and how did they get there".`,
  )
  .configureHelp({
    helpWidth: process.stdout.columns || 80,
  });

const listSpecs: PromptSpec[] = [
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Page size (default 50, max 200). A larger value is clamped rather than refused.", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.", type: "integer", required: false },
  { key: "order", option: "--order <order>", name: "order", description: "Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.", type: "string", required: false },
  { key: "id", option: "--id <id>", name: "id", description: "Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.", type: "string", required: false },
  { key: "code", option: "--code <code>", name: "code", description: "Exact match on `code`. The category's stable identifier — what an import and a storefront join on, and what survives a rename of the label. Unique per tenant.", type: "string", required: false },
  { key: "parentId", option: "--parent-id <parent-id>", name: "parent_id", description: "Exact match on `parent_id`. The category this one hangs under. Null is a root of the tree. Deleting a parent lifts its children to the root rather than deleting them, so a mis-click never takes a subtree with it.", type: "string", required: false },
  { key: "path", option: "--path <path>", name: "path", description: "Exact match on `path`. A materialized position in the tree, kept for importers that carry one (`tools/power_tools/cordless_drills`). Nothing in this app writes or reads it — `parent_id` is the structure this app navigates.", type: "string", required: false },
  { key: "position", option: "--position <position>", name: "position", description: "Exact match on `position`. Order among the siblings under the same parent, ascending.", type: "integer", required: false },
  { key: "labels", option: "--labels <labels>", name: "labels", description: "Exact match on `labels`. The category name a person sees, per language tag. The catalog reads by name, not by code — a locale left blank falls back to the next filled one. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "values", option: "--values <values>", name: "values", description: "Exact match on `values`. Whatever this catalog keeps on a category beyond the model — the keys belong to the tenant, not to this app, and nothing here reads them. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "rules", option: "--rules <rules>", name: "rules", description: "Exact match on `rules`. The selector that makes this a RULE-DRIVEN category. Null means hand-picked. Matching products are MATERIALIZED as `product_categories` rows with source `rule`, next to the hand-picked ones a recompute never touches; `POST /products/categories/{category_id}/rules/preview` dry-runs this exact document before it is stored. Conditions address the `common` bucket of a product's values — a value held per locale or per channel has no single answer for a rule to test. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "ruleMatch", option: "--rule-match <rule-match>", name: "rule_match", description: "Exact match on `rule_match`. How the conditions combine: 'all' ANDs them (the default), 'any' ORs them. It is a column of its own rather than a key of `rules` because the compiler reads the two separately.", type: "string", required: false, enum: ["all","any"] },
  { key: "rulesComputedAt", option: "--rules-computed-at <rules-computed-at>", name: "rules_computed_at", description: "Exact match on `rules_computed_at`. When the rule last ran TO COMPLETION and its memberships were synced. Null means no pass has ever finished — a recompute is chunked, so a half-finished pass leaves this untouched.", type: "string", required: false },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.", type: "string", required: false },
  { key: "updatedAt", option: "--updated-at <updated-at>", name: "updated_at", description: "Exact match on `updated_at`. When the row was last written. Server-set — it is not part of any request body.", type: "string", required: false },
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
productsCategories
  .command(`list`)
  .description(`One node of the category tree. \`parent_id\` is the structure this app navigates — null is a root — while \`path\` is kept only for importers that carry one and nothing here reads or writes it. A category is hand-picked or RULE-DRIVEN: a non-null \`rules\` selector makes every matching product a \`product_categories\` row with source \`rule\`, alongside the hand-picked ones, and \`rules_computed_at\` says when that last completed.

Every column of \`categories\` is an exact-match query parameter, \`order\` sorts by one column, and \`limit\`/\`offset\` page through \`page.total\`. A query key that is NOT a column is dropped rather than refused, and the \`filter\` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.

Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.`)
  .option(`--limit <limit>`, `Page size (default 50, max 200). A larger value is clamped rather than refused.`, parseInteger)
  .option(`--offset <offset>`, `Row offset for pagination (default 0). Page with \`page.total\` and \`page.hasMore\`.`, parseInteger)
  .option(`--order <order>`, `Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.`)
  .option(`--id <id>`, `Exact match on \`id\`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.`)
  .option(`--code <code>`, `Exact match on \`code\`. The category's stable identifier — what an import and a storefront join on, and what survives a rename of the label. Unique per tenant.`)
  .option(`--parent-id <parent-id>`, `Exact match on \`parent_id\`. The category this one hangs under. Null is a root of the tree. Deleting a parent lifts its children to the root rather than deleting them, so a mis-click never takes a subtree with it.`)
  .option(`--path <path>`, `Exact match on \`path\`. A materialized position in the tree, kept for importers that carry one (\`tools/power_tools/cordless_drills\`). Nothing in this app writes or reads it — \`parent_id\` is the structure this app navigates.`)
  .option(`--position <position>`, `Exact match on \`position\`. Order among the siblings under the same parent, ascending.`, parseInteger)
  .option(`--labels <labels>`, `Exact match on \`labels\`. The category name a person sees, per language tag. The catalog reads by name, not by code — a locale left blank falls back to the next filled one. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--values <values>`, `Exact match on \`values\`. Whatever this catalog keeps on a category beyond the model — the keys belong to the tenant, not to this app, and nothing here reads them. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--rules <rules>`, `Exact match on \`rules\`. The selector that makes this a RULE-DRIVEN category. Null means hand-picked. Matching products are MATERIALIZED as \`product_categories\` rows with source \`rule\`, next to the hand-picked ones a recompute never touches; \`POST /products/categories/{category_id}/rules/preview\` dry-runs this exact document before it is stored. Conditions address the \`common\` bucket of a product's values — a value held per locale or per channel has no single answer for a rule to test. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--rule-match <rule-match>`, `Exact match on \`rule_match\`. How the conditions combine: 'all' ANDs them (the default), 'any' ORs them. It is a column of its own rather than a key of \`rules\` because the compiler reads the two separately.`)
  .option(`--rules-computed-at <rules-computed-at>`, `Exact match on \`rules_computed_at\`. When the rule last ran TO COMPLETION and its memberships were synced. Null means no pass has ever finished — a recompute is chunked, so a half-finished pass leaves this untouched.`)
  .option(`--created-at <created-at>`, `Exact match on \`created_at\`. When the row was created. Server-set — it is not part of any request body.`)
  .option(`--updated-at <updated-at>`, `Exact match on \`updated_at\`. When the row was last written. Server-set — it is not part of any request body.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { limit, offset, order, id, code, parentId, path, position, labels, values, rules, ruleMatch, rulesComputedAt, createdAt, updatedAt, filter } = await promptForMissing(
          _options,
          listSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/categories`;
        const _payload: RequestParams = {};
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        if (order !== undefined) {
          _payload[`order`] = order;
        }
        if (id !== undefined) {
          _payload[`id`] = id;
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (parentId !== undefined) {
          _payload[`parent_id`] = parentId;
        }
        if (path !== undefined) {
          _payload[`path`] = path;
        }
        if (position !== undefined) {
          _payload[`position`] = position;
        }
        if (labels !== undefined) {
          _payload[`labels`] = labels;
        }
        if (values !== undefined) {
          _payload[`values`] = values;
        }
        if (rules !== undefined) {
          _payload[`rules`] = rules;
        }
        if (ruleMatch !== undefined) {
          _payload[`rule_match`] = ruleMatch;
        }
        if (rulesComputedAt !== undefined) {
          _payload[`rules_computed_at`] = rulesComputedAt;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        if (updatedAt !== undefined) {
          _payload[`updated_at`] = updatedAt;
        }
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, listSpecs, { method: "get" });
const createSpecs: PromptSpec[] = [
  { key: "code", option: "--code <code>", name: "code", description: "The category's stable identifier — what an import and a storefront join on, and what survives a rename of the label. Unique per tenant.", type: "string", required: true },
  { key: "labels", option: "--labels <labels>", name: "labels", description: "The category name a person sees, per language tag. The catalog reads by name, not by code — a locale left blank falls back to the next filled one.", type: "object", required: false },
  { key: "parentId", option: "--parent-id <parent-id>", name: "parent_id", description: "The category this one hangs under. Null is a root of the tree. Deleting a parent lifts its children to the root rather than deleting them, so a mis-click never takes a subtree with it.", type: "string", required: false },
  { key: "path", option: "--path <path>", name: "path", description: "A materialized position in the tree, kept for importers that carry one (`tools/power_tools/cordless_drills`). Nothing in this app writes or reads it — `parent_id` is the structure this app navigates.", type: "string", required: false },
  { key: "position", option: "--position <position>", name: "position", description: "Order among the siblings under the same parent, ascending.", type: "integer", required: false },
  { key: "ruleMatch", option: "--rule-match <rule-match>", name: "rule_match", description: "How the conditions combine: 'all' ANDs them (the default), 'any' ORs them. It is a column of its own rather than a key of `rules` because the compiler reads the two separately.", type: "string", required: false, enum: ["all","any"] },
  { key: "rules", option: "--rules <rules>", name: "rules", description: "The selector that makes this a RULE-DRIVEN category. Null means hand-picked. Matching products are MATERIALIZED as `product_categories` rows with source `rule`, next to the hand-picked ones a recompute never touches; `POST /products/categories/{category_id}/rules/preview` dry-runs this exact document before it is stored. Conditions address the `common` bucket of a product's values — a value held per locale or per channel has no single answer for a rule to test.", type: "object", required: false },
  { key: "rulesComputedAt", option: "--rules-computed-at <rules-computed-at>", name: "rules_computed_at", description: "When the rule last ran TO COMPLETION and its memberships were synced. Null means no pass has ever finished — a recompute is chunked, so a half-finished pass leaves this untouched.", type: "string", required: false },
  { key: "values", option: "--values <values>", name: "values", description: "Whatever this catalog keeps on a category beyond the model — the keys belong to the tenant, not to this app, and nothing here reads them.", type: "object", required: false },
];
productsCategories
  .command(`create`)
  .description(`Creates one category and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.

One node of the category tree. \`parent_id\` is the structure this app navigates — null is a root — while \`path\` is kept only for importers that carry one and nothing here reads or writes it. A category is hand-picked or RULE-DRIVEN: a non-null \`rules\` selector makes every matching product a \`product_categories\` row with source \`rule\`, alongside the hand-picked ones, and \`rules_computed_at\` says when that last completed.

\`code\` is the only column the database refuses the row without; everything else has a default or is nullable. A second row with the same \`code\` answers 409.`)
  .option(`--code <code>`, `The category's stable identifier — what an import and a storefront join on, and what survives a rename of the label. Unique per tenant.`)
  .option(`--labels <labels>`, `The category name a person sees, per language tag. The catalog reads by name, not by code — a locale left blank falls back to the next filled one.`)
  .option(`--parent-id <parent-id>`, `The category this one hangs under. Null is a root of the tree. Deleting a parent lifts its children to the root rather than deleting them, so a mis-click never takes a subtree with it.`)
  .option(`--path <path>`, `A materialized position in the tree, kept for importers that carry one (\`tools/power_tools/cordless_drills\`). Nothing in this app writes or reads it — \`parent_id\` is the structure this app navigates.`)
  .option(`--position <position>`, `Order among the siblings under the same parent, ascending.`, parseInteger)
  .option(`--rule-match <rule-match>`, `How the conditions combine: 'all' ANDs them (the default), 'any' ORs them. It is a column of its own rather than a key of \`rules\` because the compiler reads the two separately.`)
  .option(`--rules <rules>`, `The selector that makes this a RULE-DRIVEN category. Null means hand-picked. Matching products are MATERIALIZED as \`product_categories\` rows with source \`rule\`, next to the hand-picked ones a recompute never touches; \`POST /products/categories/{category_id}/rules/preview\` dry-runs this exact document before it is stored. Conditions address the \`common\` bucket of a product's values — a value held per locale or per channel has no single answer for a rule to test.`)
  .option(`--rules-computed-at <rules-computed-at>`, `When the rule last ran TO COMPLETION and its memberships were synced. Null means no pass has ever finished — a recompute is chunked, so a half-finished pass leaves this untouched.`)
  .option(`--values <values>`, `Whatever this catalog keeps on a category beyond the model — the keys belong to the tenant, not to this app, and nothing here reads them.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { code, labels, parentId, path, position, ruleMatch, rules, rulesComputedAt, values } = await promptForMissing(
          _options,
          createSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/categories`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (labels !== undefined) {
          _payload[`labels`] = resolveBodyParam(labels);
        }
        if (parentId !== undefined) {
          _payload[`parent_id`] = parentId;
        }
        if (path !== undefined) {
          _payload[`path`] = path;
        }
        if (position !== undefined) {
          _payload[`position`] = position;
        }
        if (ruleMatch !== undefined) {
          _payload[`rule_match`] = ruleMatch;
        }
        if (rules !== undefined) {
          _payload[`rules`] = resolveBodyParam(rules);
        }
        if (rulesComputedAt !== undefined) {
          _payload[`rules_computed_at`] = rulesComputedAt;
        }
        if (values !== undefined) {
          _payload[`values`] = resolveBodyParam(values);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, createSpecs, { method: "post" });
const rulesRecomputeAllSpecs: PromptSpec[] = [
  { key: "data", option: "--data <data>", name: "data", description: "Request body", type: "object", required: true },
];
productsCategories
  .command(`rules-recompute-all`)
  .description(`What the nightly \`recompute-category-rules\` schedule calls, and the call to reach for after a bulk import has changed what the rules select. Same sync as the single-category recompute, applied to every category with non-null rules. The whole run shares ONE budget: a category the budget no longer reaches is reported as \`skipped\` and picked up by the next run, and a failing category is reported in its result entry instead of aborting the run.`)
  .option(`--data <data>`, `Request body`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { data } = await promptForMissing(
          _options,
          rulesRecomputeAllSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/categories/rules/recompute-all`;
        const _payload: RequestParams = {};
        if (data !== undefined) {
          Object.assign(_payload, resolveBodyParam(data));
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, rulesRecomputeAllSpecs, { method: "post" });
const rulesPreviewSpecs: PromptSpec[] = [
  { key: "categoryId", option: "--category-id <category-id>", name: "category_id", description: "The `categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/categories`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/categories", hasLimit: true } },
  { key: "conditions", option: "--conditions [conditions...]", name: "conditions", description: "Between 1 and 25 conditions — a rule is a selector, not a query language. An empty list is a 400, not \"everything\".", type: "array", required: true },
  { key: "ruleMatch", option: "--rule-match <rule-match>", name: "rule_match", description: "'all' ANDs every condition (default), 'any' ORs them.", type: "string", required: false, enum: ["all","any"] },
];
productsCategories
  .command(`rules-preview`)
  .description(`Dry-runs a rule: how many products it selects, plus a sample of up to ten, and it WRITES NOTHING. Evaluates the rule in the request body against the live catalog WITHOUT touching product_categories — this powers the cockpit's "matches N products" preview while an operator edits a rule. Soft-deleted products are excluded. Counting is delegated to the database, never enumerated: a rule that compiles to a single query is answered by one exact-count request whatever its match set. A rule that needs several queries (rule_match "any", or a repeated column such as a range) is combined in the app and stops at \`cap\` ids — check \`capped\` before showing \`count\` as a total.`)
  .option(`--category-id <category-id>`, `The \`categories\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/categories\`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .option(`--conditions [conditions...]`, `Between 1 and 25 conditions — a rule is a selector, not a query language. An empty list is a 400, not "everything".`)
  .option(`--rule-match <rule-match>`, `'all' ANDs every condition (default), 'any' ORs them.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { categoryId, conditions, ruleMatch } = await promptForMissing(
          _options,
          rulesPreviewSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/categories/{category_id}/rules/preview`.replace(`{category_id}`, categoryId);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (conditions !== undefined) {
          _payload[`conditions`] = conditions;
        }
        if (ruleMatch !== undefined) {
          _payload[`rule_match`] = ruleMatch;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, rulesPreviewSpecs, { method: "post" });
const rulesRecomputeSpecs: PromptSpec[] = [
  { key: "categoryId", option: "--category-id <category-id>", name: "category_id", description: "The `categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/categories`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/categories", hasLimit: true } },
  { key: "cursor", option: "--cursor <cursor>", name: "cursor", description: "The `cursor` a previous call returned, to continue that pass. Send `null` explicitly to restart from the beginning; omit the field to let the app decide (resume if a pass is in flight, otherwise start fresh). Anything that is not a string or null is a 400.", type: "string", required: false },
];
productsCategories
  .command(`rules-recompute`)
  .description(`Syncs one category's rule-derived memberships to what its stored rule selects today. Evaluates categories.rules (NOT the request body), then inserts the newly matching products as source='rule' rows and deletes the rule rows that no longer match. Manual (source='manual') memberships are never inserted, deleted or shadowed. Stamps categories.rules_computed_at.

A large category does NOT finish in one call: the run stops when its wall-clock budget is spent and answers \`done: false\` with the \`cursor\` to send back, so drive it in a loop until \`done\` is true.`)
  .option(`--category-id <category-id>`, `The \`categories\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/categories\`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .option(`--cursor <cursor>`, `The \`cursor\` a previous call returned, to continue that pass. Send \`null\` explicitly to restart from the beginning; omit the field to let the app decide (resume if a pass is in flight, otherwise start fresh). Anything that is not a string or null is a 400.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { categoryId, cursor } = await promptForMissing(
          _options,
          rulesRecomputeSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/categories/{category_id}/rules/recompute`.replace(`{category_id}`, categoryId);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (cursor !== undefined) {
          _payload[`cursor`] = cursor;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, rulesRecomputeSpecs, { method: "post" });
const deleteSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/categories`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/categories", hasLimit: true } },
];
productsCategories
  .command(`delete`)
  .description(`Deletes one category by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.

It takes what hangs off it: product category memberships (\`category_id\`) are deleted with it. \`categories.parent_id\` is set to null instead, so the rows that pointed at it survive the delete rather than going with it.

An id no category of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.`)
  .option(`--id <id>`, `The \`categories\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/categories\`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          deleteSpecs,
          _command,
        );
        await confirmDestructive(`products-categories delete`);
        const _client = await sdkForProject();
        const _apiPath = `/products/categories/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `delete`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, deleteSpecs, { method: "delete", destructive: true });
const getSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/categories`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/categories", hasLimit: true } },
];
productsCategories
  .command(`get`)
  .description(`Reads one category by its id — the whole row, every column, as it is stored.

One node of the category tree. \`parent_id\` is the structure this app navigates — null is a root — while \`path\` is kept only for importers that carry one and nothing here reads or writes it. A category is hand-picked or RULE-DRIVEN: a non-null \`rules\` selector makes every matching product a \`product_categories\` row with source \`rule\`, alongside the hand-picked ones, and \`rules_computed_at\` says when that last completed.

An id no category of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.

Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.`)
  .option(`--id <id>`, `The \`categories\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/categories\`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          getSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/categories/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, getSpecs, { method: "get" });
const updateSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/categories`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/categories", hasLimit: true } },
  { key: "code", option: "--code <code>", name: "code", description: "The category's stable identifier — what an import and a storefront join on, and what survives a rename of the label. Unique per tenant.", type: "string", required: false },
  { key: "labels", option: "--labels <labels>", name: "labels", description: "The category name a person sees, per language tag. The catalog reads by name, not by code — a locale left blank falls back to the next filled one.", type: "object", required: false },
  { key: "parentId", option: "--parent-id <parent-id>", name: "parent_id", description: "The category this one hangs under. Null is a root of the tree. Deleting a parent lifts its children to the root rather than deleting them, so a mis-click never takes a subtree with it.", type: "string", required: false },
  { key: "path", option: "--path <path>", name: "path", description: "A materialized position in the tree, kept for importers that carry one (`tools/power_tools/cordless_drills`). Nothing in this app writes or reads it — `parent_id` is the structure this app navigates.", type: "string", required: false },
  { key: "position", option: "--position <position>", name: "position", description: "Order among the siblings under the same parent, ascending.", type: "integer", required: false },
  { key: "ruleMatch", option: "--rule-match <rule-match>", name: "rule_match", description: "How the conditions combine: 'all' ANDs them (the default), 'any' ORs them. It is a column of its own rather than a key of `rules` because the compiler reads the two separately.", type: "string", required: false, enum: ["all","any"] },
  { key: "rules", option: "--rules <rules>", name: "rules", description: "The selector that makes this a RULE-DRIVEN category. Null means hand-picked. Matching products are MATERIALIZED as `product_categories` rows with source `rule`, next to the hand-picked ones a recompute never touches; `POST /products/categories/{category_id}/rules/preview` dry-runs this exact document before it is stored. Conditions address the `common` bucket of a product's values — a value held per locale or per channel has no single answer for a rule to test.", type: "object", required: false },
  { key: "rulesComputedAt", option: "--rules-computed-at <rules-computed-at>", name: "rules_computed_at", description: "When the rule last ran TO COMPLETION and its memberships were synced. Null means no pass has ever finished — a recompute is chunked, so a half-finished pass leaves this untouched.", type: "string", required: false },
  { key: "values", option: "--values <values>", name: "values", description: "Whatever this catalog keeps on a category beyond the model — the keys belong to the tenant, not to this app, and nothing here reads them.", type: "object", required: false },
];
productsCategories
  .command(`update`)
  .description(`Updates one category by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.

One node of the category tree. \`parent_id\` is the structure this app navigates — null is a root — while \`path\` is kept only for importers that carry one and nothing here reads or writes it. A category is hand-picked or RULE-DRIVEN: a non-null \`rules\` selector makes every matching product a \`product_categories\` row with source \`rule\`, alongside the hand-picked ones, and \`rules_computed_at\` says when that last completed.

A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on \`code\` answers 409.`)
  .option(`--id <id>`, `The \`categories\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/categories\`. An id no categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .option(`--code <code>`, `The category's stable identifier — what an import and a storefront join on, and what survives a rename of the label. Unique per tenant.`)
  .option(`--labels <labels>`, `The category name a person sees, per language tag. The catalog reads by name, not by code — a locale left blank falls back to the next filled one.`)
  .option(`--parent-id <parent-id>`, `The category this one hangs under. Null is a root of the tree. Deleting a parent lifts its children to the root rather than deleting them, so a mis-click never takes a subtree with it.`)
  .option(`--path <path>`, `A materialized position in the tree, kept for importers that carry one (\`tools/power_tools/cordless_drills\`). Nothing in this app writes or reads it — \`parent_id\` is the structure this app navigates.`)
  .option(`--position <position>`, `Order among the siblings under the same parent, ascending.`, parseInteger)
  .option(`--rule-match <rule-match>`, `How the conditions combine: 'all' ANDs them (the default), 'any' ORs them. It is a column of its own rather than a key of \`rules\` because the compiler reads the two separately.`)
  .option(`--rules <rules>`, `The selector that makes this a RULE-DRIVEN category. Null means hand-picked. Matching products are MATERIALIZED as \`product_categories\` rows with source \`rule\`, next to the hand-picked ones a recompute never touches; \`POST /products/categories/{category_id}/rules/preview\` dry-runs this exact document before it is stored. Conditions address the \`common\` bucket of a product's values — a value held per locale or per channel has no single answer for a rule to test.`)
  .option(`--rules-computed-at <rules-computed-at>`, `When the rule last ran TO COMPLETION and its memberships were synced. Null means no pass has ever finished — a recompute is chunked, so a half-finished pass leaves this untouched.`)
  .option(`--values <values>`, `Whatever this catalog keeps on a category beyond the model — the keys belong to the tenant, not to this app, and nothing here reads them.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, code, labels, parentId, path, position, ruleMatch, rules, rulesComputedAt, values } = await promptForMissing(
          _options,
          updateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/categories/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (labels !== undefined) {
          _payload[`labels`] = resolveBodyParam(labels);
        }
        if (parentId !== undefined) {
          _payload[`parent_id`] = parentId;
        }
        if (path !== undefined) {
          _payload[`path`] = path;
        }
        if (position !== undefined) {
          _payload[`position`] = position;
        }
        if (ruleMatch !== undefined) {
          _payload[`rule_match`] = ruleMatch;
        }
        if (rules !== undefined) {
          _payload[`rules`] = resolveBodyParam(rules);
        }
        if (rulesComputedAt !== undefined) {
          _payload[`rules_computed_at`] = rulesComputedAt;
        }
        if (values !== undefined) {
          _payload[`values`] = resolveBodyParam(values);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `put`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, updateSpecs, { method: "put" });
const productsProductCategoriesListSpecs: PromptSpec[] = [
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Page size (default 50, max 200). A larger value is clamped rather than refused.", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.", type: "integer", required: false },
  { key: "order", option: "--order <order>", name: "order", description: "Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.", type: "string", required: false },
  { key: "id", option: "--id <id>", name: "id", description: "Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.", type: "string", required: false },
  { key: "productId", option: "--product-id <product-id>", name: "product_id", description: "Exact match on `product_id`. The product filed into the category. Deleting the product deletes the membership with it.", type: "string", required: false },
  { key: "categoryId", option: "--category-id <category-id>", name: "category_id", description: "Exact match on `category_id`. The category it is filed into. One row per (product, category), whichever way it got there.", type: "string", required: false },
  { key: "position", option: "--position <position>", name: "position", description: "Exact match on `position`. Sort order of this product inside the category.", type: "integer", required: false },
  { key: "source", option: "--source <source>", name: "source", description: "Exact match on `source`. How the membership came about: 'manual' is hand-picked, 'rule' was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass.", type: "string", required: false, enum: ["manual","rule"] },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.", type: "string", required: false },
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
productsCategories
  .command(`products-product-categories-list`)
  .description(`One membership: this product is filed in this category. \`source\` says how it got there — \`manual\` is hand-picked, \`rule\` was materialized by a category rule — and the two never touch each other: a recompute only ever inserts and deletes \`rule\` rows, so a hand-picked membership survives every pass. \`POST /products/{id}/categories\` is the friendlier way to create one, because it takes the product from the path and answers with the category code and the SKU.

Every column of \`product_categories\` is an exact-match query parameter, \`order\` sorts by one column, and \`limit\`/\`offset\` page through \`page.total\`. A query key that is NOT a column is dropped rather than refused, and the \`filter\` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.

Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.`)
  .option(`--limit <limit>`, `Page size (default 50, max 200). A larger value is clamped rather than refused.`, parseInteger)
  .option(`--offset <offset>`, `Row offset for pagination (default 0). Page with \`page.total\` and \`page.hasMore\`.`, parseInteger)
  .option(`--order <order>`, `Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.`)
  .option(`--id <id>`, `Exact match on \`id\`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.`)
  .option(`--product-id <product-id>`, `Exact match on \`product_id\`. The product filed into the category. Deleting the product deletes the membership with it.`)
  .option(`--category-id <category-id>`, `Exact match on \`category_id\`. The category it is filed into. One row per (product, category), whichever way it got there.`)
  .option(`--position <position>`, `Exact match on \`position\`. Sort order of this product inside the category.`, parseInteger)
  .option(`--source <source>`, `Exact match on \`source\`. How the membership came about: 'manual' is hand-picked, 'rule' was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes \`rule\` rows, so a hand-picked membership survives every pass.`)
  .option(`--created-at <created-at>`, `Exact match on \`created_at\`. When the row was created. Server-set — it is not part of any request body.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { limit, offset, order, id, productId, categoryId, position, source, createdAt, filter } = await promptForMissing(
          _options,
          productsProductCategoriesListSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/product_categories`;
        const _payload: RequestParams = {};
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        if (order !== undefined) {
          _payload[`order`] = order;
        }
        if (id !== undefined) {
          _payload[`id`] = id;
        }
        if (productId !== undefined) {
          _payload[`product_id`] = productId;
        }
        if (categoryId !== undefined) {
          _payload[`category_id`] = categoryId;
        }
        if (position !== undefined) {
          _payload[`position`] = position;
        }
        if (source !== undefined) {
          _payload[`source`] = source;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, productsProductCategoriesListSpecs, { method: "get" });
const productsProductCategoriesCreateSpecs: PromptSpec[] = [
  { key: "categoryId", option: "--category-id <category-id>", name: "category_id", description: "The category it is filed into. One row per (product, category), whichever way it got there.", type: "string", required: true },
  { key: "productId", option: "--product-id <product-id>", name: "product_id", description: "The product filed into the category. Deleting the product deletes the membership with it.", type: "string", required: true },
  { key: "position", option: "--position <position>", name: "position", description: "Sort order of this product inside the category.", type: "integer", required: false },
  { key: "source", option: "--source <source>", name: "source", description: "How the membership came about: 'manual' is hand-picked, 'rule' was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass.", type: "string", required: false, enum: ["manual","rule"] },
];
productsCategories
  .command(`products-product-categories-create`)
  .description(`Creates one product category membership and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.

One membership: this product is filed in this category. \`source\` says how it got there — \`manual\` is hand-picked, \`rule\` was materialized by a category rule — and the two never touch each other: a recompute only ever inserts and deletes \`rule\` rows, so a hand-picked membership survives every pass. \`POST /products/{id}/categories\` is the friendlier way to create one, because it takes the product from the path and answers with the category code and the SKU.

\`product_id\` and \`category_id\` are the only columns the database refuses the row without; everything else has a default or is nullable. A second row with the same \`product_id\` and \`category_id\` answers 409.`)
  .option(`--category-id <category-id>`, `The category it is filed into. One row per (product, category), whichever way it got there.`)
  .option(`--product-id <product-id>`, `The product filed into the category. Deleting the product deletes the membership with it.`)
  .option(`--position <position>`, `Sort order of this product inside the category.`, parseInteger)
  .option(`--source <source>`, `How the membership came about: 'manual' is hand-picked, 'rule' was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes \`rule\` rows, so a hand-picked membership survives every pass.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { categoryId, productId, position, source } = await promptForMissing(
          _options,
          productsProductCategoriesCreateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/product_categories`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (categoryId !== undefined) {
          _payload[`category_id`] = categoryId;
        }
        if (position !== undefined) {
          _payload[`position`] = position;
        }
        if (productId !== undefined) {
          _payload[`product_id`] = productId;
        }
        if (source !== undefined) {
          _payload[`source`] = source;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, productsProductCategoriesCreateSpecs, { method: "post" });
const productsProductCategoriesDeleteSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `product_categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/product_categories`. An id no product categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/product_categories", hasLimit: true } },
];
productsCategories
  .command(`products-product-categories-delete`)
  .description(`Deletes one product category membership by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.

Nothing in this schema references it, so nothing else changes.

An id no product category membership of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.`)
  .option(`--id <id>`, `The \`product_categories\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/product_categories\`. An id no product categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          productsProductCategoriesDeleteSpecs,
          _command,
        );
        await confirmDestructive(`products-categories products-product-categories-delete`);
        const _client = await sdkForProject();
        const _apiPath = `/products/product_categories/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `delete`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, productsProductCategoriesDeleteSpecs, { method: "delete", destructive: true });
const productsProductCategoriesGetSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `product_categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/product_categories`. An id no product categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/product_categories", hasLimit: true } },
];
productsCategories
  .command(`products-product-categories-get`)
  .description(`Reads one product category membership by its id — the whole row, every column, as it is stored.

One membership: this product is filed in this category. \`source\` says how it got there — \`manual\` is hand-picked, \`rule\` was materialized by a category rule — and the two never touch each other: a recompute only ever inserts and deletes \`rule\` rows, so a hand-picked membership survives every pass. \`POST /products/{id}/categories\` is the friendlier way to create one, because it takes the product from the path and answers with the category code and the SKU.

An id no product category membership of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.

Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.`)
  .option(`--id <id>`, `The \`product_categories\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/product_categories\`. An id no product categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          productsProductCategoriesGetSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/product_categories/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, productsProductCategoriesGetSpecs, { method: "get" });
const productsProductCategoriesUpdateSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `product_categories` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/product_categories`. An id no product categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/product_categories", hasLimit: true } },
  { key: "categoryId", option: "--category-id <category-id>", name: "category_id", description: "The category it is filed into. One row per (product, category), whichever way it got there.", type: "string", required: false },
  { key: "position", option: "--position <position>", name: "position", description: "Sort order of this product inside the category.", type: "integer", required: false },
  { key: "productId", option: "--product-id <product-id>", name: "product_id", description: "The product filed into the category. Deleting the product deletes the membership with it.", type: "string", required: false },
  { key: "source", option: "--source <source>", name: "source", description: "How the membership came about: 'manual' is hand-picked, 'rule' was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass.", type: "string", required: false, enum: ["manual","rule"] },
];
productsCategories
  .command(`products-product-categories-update`)
  .description(`Updates one product category membership by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.

One membership: this product is filed in this category. \`source\` says how it got there — \`manual\` is hand-picked, \`rule\` was materialized by a category rule — and the two never touch each other: a recompute only ever inserts and deletes \`rule\` rows, so a hand-picked membership survives every pass. \`POST /products/{id}/categories\` is the friendlier way to create one, because it takes the product from the path and answers with the category code and the SKU.

A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on \`product_id\` and \`category_id\` answers 409.`)
  .option(`--id <id>`, `The \`product_categories\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/product_categories\`. An id no product categorie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .option(`--category-id <category-id>`, `The category it is filed into. One row per (product, category), whichever way it got there.`)
  .option(`--position <position>`, `Sort order of this product inside the category.`, parseInteger)
  .option(`--product-id <product-id>`, `The product filed into the category. Deleting the product deletes the membership with it.`)
  .option(`--source <source>`, `How the membership came about: 'manual' is hand-picked, 'rule' was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes \`rule\` rows, so a hand-picked membership survives every pass.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, categoryId, position, productId, source } = await promptForMissing(
          _options,
          productsProductCategoriesUpdateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/product_categories/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (categoryId !== undefined) {
          _payload[`category_id`] = categoryId;
        }
        if (position !== undefined) {
          _payload[`position`] = position;
        }
        if (productId !== undefined) {
          _payload[`product_id`] = productId;
        }
        if (source !== undefined) {
          _payload[`source`] = source;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `put`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, productsProductCategoriesUpdateSpecs, { method: "put" });
const assignSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `products` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products`. An id no product of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true },
  { key: "categoryId", option: "--category-id <category-id>", name: "category_id", description: "The category to file the product into.", type: "string", required: true },
  { key: "position", option: "--position <position>", name: "position", description: "Sort order inside the category. Default 0.", type: "integer", required: false },
];
productsCategories
  .command(`assign`)
  .description(`Files one product into one category by hand, and the membership is always \`source: 'manual'\` — a rule recompute never deletes or shadows it. product_categories holds 28 758 rows and had no write surface that named the product it was filing. This takes the product from the route and the category from the body, which is what a bulk 'add the selected products to …' needs. The membership is always source='manual', so a rule recompute never deletes or shadows it.`)
  .option(`--id <id>`, `The \`products\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products\`. An id no product of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .option(`--category-id <category-id>`, `The category to file the product into.`)
  .option(`--position <position>`, `Sort order inside the category. Default 0.`, parseInteger)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, categoryId, position } = await promptForMissing(
          _options,
          assignSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/{id}/categories`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (categoryId !== undefined) {
          _payload[`category_id`] = categoryId;
        }
        if (position !== undefined) {
          _payload[`position`] = position;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsCategories.commands.at(-1)!, assignSpecs, { method: "post" });
