import { Command } from "commander";
import { resolveBodyParam } from "../../utils.js";
import { sdkForProject } from "../../sdks.js";
import type { RequestParams } from "../../types.js";
import {
  actionRunner,
  commandDescriptions,
  cliConfig,
  parse,
  parseInteger,
} from "../../parser.js";
import {
  confirmDestructive,
  promptForMissing,
  type PromptSpec,
  registerPromptSpecs,
} from "../../interactive.js";

export const productsAssets = new Command("products-assets")
  .description(
    commandDescriptions["productsAssets"] ??
      `The decoupled media domain: the asset rows a product's media attribute points at, whether their bytes sit in this platform's object store or on somebody else's host. An asset is addressed by code within its family and is never linked to a product by a join table — a product references it through an attribute value. The families that give assets their shape and their file-naming convention live in Data model.`,
  )
  .configureHelp({
    helpWidth: process.stdout.columns || 80,
  });

const listSpecs: PromptSpec[] = [
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Page size (default 50, max 200). A larger value is clamped rather than refused.", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.", type: "integer", required: false },
  { key: "order", option: "--order <order>", name: "order", description: "Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.", type: "string", required: false },
  { key: "id", option: "--id <id>", name: "id", description: "Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.", type: "string", required: false },
  { key: "assetFamilyId", option: "--asset-family-id <asset-family-id>", name: "asset_family_id", description: "Exact match on `asset_family_id`. The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.", type: "string", required: false },
  { key: "code", option: "--code <code>", name: "code", description: "Exact match on `code`. The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.", type: "string", required: false },
  { key: "source", option: "--source <source>", name: "source", description: "Exact match on `source`. Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.", type: "string", required: false, enum: ["storage","external"] },
  { key: "storageAssetId", option: "--storage-asset-id <storage-asset-id>", name: "storage_asset_id", description: "Exact match on `storage_asset_id`. The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.", type: "string", required: false },
  { key: "deliveryPath", option: "--delivery-path <delivery-path>", name: "delivery_path", description: "Exact match on `delivery_path`. The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.", type: "string", required: false },
  { key: "externalUrl", option: "--external-url <external-url>", name: "external_url", description: "Exact match on `external_url`. Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.", type: "string", required: false },
  { key: "attributeValues", option: "--attribute-values <attribute-values>", name: "attribute_values", description: "Exact match on `attribute_values`. Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.", type: "string", required: false },
  { key: "updatedAt", option: "--updated-at <updated-at>", name: "updated_at", description: "Exact match on `updated_at`. When the row was last written. Server-set — it is not part of any request body.", type: "string", required: false },
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
productsAssets
  .command(`list`)
  .description(`One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (\`source: "storage"\` with a \`storage_asset_id\` that survives a rename) or on somebody else's host (\`source: "external"\` with an \`external_url\`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.

Every column of \`assets\` is an exact-match query parameter, \`order\` sorts by one column, and \`limit\`/\`offset\` page through \`page.total\`. A query key that is NOT a column is dropped rather than refused, and the \`filter\` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.

Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.`)
  .option(`--limit <limit>`, `Page size (default 50, max 200). A larger value is clamped rather than refused.`, parseInteger)
  .option(`--offset <offset>`, `Row offset for pagination (default 0). Page with \`page.total\` and \`page.hasMore\`.`, parseInteger)
  .option(`--order <order>`, `Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.`)
  .option(`--id <id>`, `Exact match on \`id\`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.`)
  .option(`--asset-family-id <asset-family-id>`, `Exact match on \`asset_family_id\`. The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the \`default_asset_family\` tenant setting when the body names none.`)
  .option(`--code <code>`, `Exact match on \`code\`. The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.`)
  .option(`--source <source>`, `Exact match on \`source\`. Where the bytes live: 'storage' is this platform's object store and needs \`storage_asset_id\`, 'external' is somebody else's host and needs \`external_url\`. The database enforces the pair, so neither half can be stored on its own.`)
  .option(`--storage-asset-id <storage-asset-id>`, `Exact match on \`storage_asset_id\`. The stable \`ast_…\` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when \`source\` is \`storage\`.`)
  .option(`--delivery-path <delivery-path>`, `Exact match on \`delivery_path\`. The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.`)
  .option(`--external-url <external-url>`, `Exact match on \`external_url\`. Absolute URL of an externally hosted file. Required when \`source\` is \`external\`, and accepted only when the tenant has \`allow_external_media\` on and the host is on its \`external_media_allowed_hosts\` list — \`POST /products/assets\` is the only place an external URL can enter the catalog, so it is the only place those are enforced.`)
  .option(`--attribute-values <attribute-values>`, `Exact match on \`attribute_values\`. Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in \`attributes\`, selected per family by \`family_attributes\`, and their values live under their attribute CODE inside this object. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--created-at <created-at>`, `Exact match on \`created_at\`. When the row was created. Server-set — it is not part of any request body.`)
  .option(`--updated-at <updated-at>`, `Exact match on \`updated_at\`. When the row was last written. Server-set — it is not part of any request body.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { limit, offset, order, id, assetFamilyId, code, source, storageAssetId, deliveryPath, externalUrl, attributeValues, createdAt, updatedAt, filter } = await promptForMissing(
          _options,
          listSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/assets`;
        const _payload: RequestParams = {};
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        if (order !== undefined) {
          _payload[`order`] = order;
        }
        if (id !== undefined) {
          _payload[`id`] = id;
        }
        if (assetFamilyId !== undefined) {
          _payload[`asset_family_id`] = assetFamilyId;
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (source !== undefined) {
          _payload[`source`] = source;
        }
        if (storageAssetId !== undefined) {
          _payload[`storage_asset_id`] = storageAssetId;
        }
        if (deliveryPath !== undefined) {
          _payload[`delivery_path`] = deliveryPath;
        }
        if (externalUrl !== undefined) {
          _payload[`external_url`] = externalUrl;
        }
        if (attributeValues !== undefined) {
          _payload[`attribute_values`] = attributeValues;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        if (updatedAt !== undefined) {
          _payload[`updated_at`] = updatedAt;
        }
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsAssets.commands.at(-1)!, listSpecs, { method: "get" });
const createSpecs: PromptSpec[] = [
  { key: "assetFamilyId", option: "--asset-family-id <asset-family-id>", name: "asset_family_id", description: "The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.", type: "string", required: true },
  { key: "code", option: "--code <code>", name: "code", description: "The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.", type: "string", required: true },
  { key: "attributeValues", option: "--attribute-values <attribute-values>", name: "attribute_values", description: "Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.\n\nFour buckets, and an attribute's own flags decide which one it writes to:\n\n  `common`                    the attribute is neither localizable nor scopable — one value, full stop.\n                              `{\"common\": {\"net_weight\": 2.4, \"colour\": \"black\"}}`\n  `locale_specific`           `localizable`: one value per language tag.\n                              `{\"locale_specific\": {\"de_DE\": {\"name\": \"Akku-Bohrschrauber\"}}}`\n  `channel_specific`          `scopable`: one value per channel.\n                              `{\"channel_specific\": {\"b2b\": {\"minimum_order_quantity\": 6}}}`\n  `channel_locale_specific`   both: one value per channel AND language tag.\n                              `{\"channel_locale_specific\": {\"b2b\": {\"de_DE\": {\"description\": \"…\"}}}}`\n\nA reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.\n\nThe value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{\"amount\": …, \"unit\": …}` for a measure, a list of `{\"amount\": …, \"currency\": …}` for a price, an asset code for media.\n\nDefaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.\n\nWhich attributes an asset of this family has comes from `attributes` rows with `entity_type: \"asset\"` and `entity_ref` equal to the family's code — alt text, copyright, an expiry date.", type: "object", required: false },
  { key: "deliveryPath", option: "--delivery-path <delivery-path>", name: "delivery_path", description: "The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.", type: "string", required: false },
  { key: "externalUrl", option: "--external-url <external-url>", name: "external_url", description: "Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.", type: "string", required: false },
  { key: "source", option: "--source <source>", name: "source", description: "Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.", type: "string", required: false, enum: ["storage","external"] },
  { key: "storageAssetId", option: "--storage-asset-id <storage-asset-id>", name: "storage_asset_id", description: "The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.", type: "string", required: false },
];
productsAssets
  .command(`create`)
  .description(`Creates one asset and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.

One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (\`source: "storage"\` with a \`storage_asset_id\` that survives a rename) or on somebody else's host (\`source: "external"\` with an \`external_url\`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.

\`asset_family_id\` and \`code\` are the only columns the database refuses the row without; everything else has a default or is nullable. A second row with the same \`asset_family_id\` and \`code\` answers 409. This app owns the create, because it is the only place an external URL can enter the catalog: an asset with no family falls back to the \`default_asset_family\` setting, and an \`external\` one is refused unless the tenant allows external media and the URL's host is on its allow-list.`)
  .option(`--asset-family-id <asset-family-id>`, `The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the \`default_asset_family\` tenant setting when the body names none.`)
  .option(`--code <code>`, `The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.`)
  .option(`--attribute-values <attribute-values>`, `Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in \`attributes\`, selected per family by \`family_attributes\`, and their values live under their attribute CODE inside this object.

Four buckets, and an attribute's own flags decide which one it writes to:

  \`common\`                    the attribute is neither localizable nor scopable — one value, full stop.
                              \`{"common": {"net_weight": 2.4, "colour": "black"}}\`
  \`locale_specific\`           \`localizable\`: one value per language tag.
                              \`{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}\`
  \`channel_specific\`          \`scopable\`: one value per channel.
                              \`{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}\`
  \`channel_locale_specific\`   both: one value per channel AND language tag.
                              \`{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}\`

A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then \`common\`. \`common\` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. \`GET /products/attribute-schema\` answers, per field, the exact path a value belongs at (\`storage.path\`) and that full fallback order (\`from\`), so no client has to re-derive any of this.

The value itself is whatever the attribute's \`type\` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, \`{"amount": …, "unit": …}\` for a measure, a list of \`{"amount": …, "currency": …}\` for a price, an asset code for media.

Defaults to \`{}\`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.

Which attributes an asset of this family has comes from \`attributes\` rows with \`entity_type: "asset"\` and \`entity_ref\` equal to the family's code — alt text, copyright, an expiry date.`)
  .option(`--delivery-path <delivery-path>`, `The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.`)
  .option(`--external-url <external-url>`, `Absolute URL of an externally hosted file. Required when \`source\` is \`external\`, and accepted only when the tenant has \`allow_external_media\` on and the host is on its \`external_media_allowed_hosts\` list — \`POST /products/assets\` is the only place an external URL can enter the catalog, so it is the only place those are enforced.`)
  .option(`--source <source>`, `Where the bytes live: 'storage' is this platform's object store and needs \`storage_asset_id\`, 'external' is somebody else's host and needs \`external_url\`. The database enforces the pair, so neither half can be stored on its own.`)
  .option(`--storage-asset-id <storage-asset-id>`, `The stable \`ast_…\` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when \`source\` is \`storage\`.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { assetFamilyId, code, attributeValues, deliveryPath, externalUrl, source, storageAssetId } = await promptForMissing(
          _options,
          createSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/assets`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (assetFamilyId !== undefined) {
          _payload[`asset_family_id`] = assetFamilyId;
        }
        if (attributeValues !== undefined) {
          _payload[`attribute_values`] = resolveBodyParam(attributeValues);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (deliveryPath !== undefined) {
          _payload[`delivery_path`] = deliveryPath;
        }
        if (externalUrl !== undefined) {
          _payload[`external_url`] = externalUrl;
        }
        if (source !== undefined) {
          _payload[`source`] = source;
        }
        if (storageAssetId !== undefined) {
          _payload[`storage_asset_id`] = storageAssetId;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsAssets.commands.at(-1)!, createSpecs, { method: "post" });
const deleteSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/assets", hasLimit: true } },
];
productsAssets
  .command(`delete`)
  .description(`Deletes one asset by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.

Nothing in this schema references it, so nothing else changes.

An id no asset of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.`)
  .option(`--id <id>`, `The \`assets\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/assets\`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          deleteSpecs,
          _command,
        );
        await confirmDestructive(`products-assets delete`);
        const _client = await sdkForProject();
        const _apiPath = `/products/assets/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `delete`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsAssets.commands.at(-1)!, deleteSpecs, { method: "delete", destructive: true });
const getSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/assets", hasLimit: true } },
];
productsAssets
  .command(`get`)
  .description(`Reads one asset by its id — the whole row, every column, as it is stored.

One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (\`source: "storage"\` with a \`storage_asset_id\` that survives a rename) or on somebody else's host (\`source: "external"\` with an \`external_url\`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.

An id no asset of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.

Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.`)
  .option(`--id <id>`, `The \`assets\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/assets\`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          getSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/assets/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsAssets.commands.at(-1)!, getSpecs, { method: "get" });
const updateSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `assets` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/assets`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/assets", hasLimit: true } },
  { key: "assetFamilyId", option: "--asset-family-id <asset-family-id>", name: "asset_family_id", description: "The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.", type: "string", required: false },
  { key: "attributeValues", option: "--attribute-values <attribute-values>", name: "attribute_values", description: "Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.\n\nFour buckets, and an attribute's own flags decide which one it writes to:\n\n  `common`                    the attribute is neither localizable nor scopable — one value, full stop.\n                              `{\"common\": {\"net_weight\": 2.4, \"colour\": \"black\"}}`\n  `locale_specific`           `localizable`: one value per language tag.\n                              `{\"locale_specific\": {\"de_DE\": {\"name\": \"Akku-Bohrschrauber\"}}}`\n  `channel_specific`          `scopable`: one value per channel.\n                              `{\"channel_specific\": {\"b2b\": {\"minimum_order_quantity\": 6}}}`\n  `channel_locale_specific`   both: one value per channel AND language tag.\n                              `{\"channel_locale_specific\": {\"b2b\": {\"de_DE\": {\"description\": \"…\"}}}}`\n\nA reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.\n\nThe value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{\"amount\": …, \"unit\": …}` for a measure, a list of `{\"amount\": …, \"currency\": …}` for a price, an asset code for media.\n\nDefaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.\n\nWhich attributes an asset of this family has comes from `attributes` rows with `entity_type: \"asset\"` and `entity_ref` equal to the family's code — alt text, copyright, an expiry date.", type: "object", required: false },
  { key: "code", option: "--code <code>", name: "code", description: "The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.", type: "string", required: false },
  { key: "deliveryPath", option: "--delivery-path <delivery-path>", name: "delivery_path", description: "The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.", type: "string", required: false },
  { key: "externalUrl", option: "--external-url <external-url>", name: "external_url", description: "Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.", type: "string", required: false },
  { key: "source", option: "--source <source>", name: "source", description: "Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.", type: "string", required: false, enum: ["storage","external"] },
  { key: "storageAssetId", option: "--storage-asset-id <storage-asset-id>", name: "storage_asset_id", description: "The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.", type: "string", required: false },
];
productsAssets
  .command(`update`)
  .description(`Updates one asset by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.

One piece of media in the decoupled asset domain. The bytes live either in this platform's object store (\`source: "storage"\` with a \`storage_asset_id\` that survives a rename) or on somebody else's host (\`source: "external"\` with an \`external_url\`), and the database enforces the pair so neither half can be stored alone. A product points at an asset by its code through a media attribute; there is no product-to-asset link table in this app.

A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on \`asset_family_id\` and \`code\` answers 409.`)
  .option(`--id <id>`, `The \`assets\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/assets\`. An id no asset of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .option(`--asset-family-id <asset-family-id>`, `The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the \`default_asset_family\` tenant setting when the body names none.`)
  .option(`--attribute-values <attribute-values>`, `Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in \`attributes\`, selected per family by \`family_attributes\`, and their values live under their attribute CODE inside this object.

Four buckets, and an attribute's own flags decide which one it writes to:

  \`common\`                    the attribute is neither localizable nor scopable — one value, full stop.
                              \`{"common": {"net_weight": 2.4, "colour": "black"}}\`
  \`locale_specific\`           \`localizable\`: one value per language tag.
                              \`{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}\`
  \`channel_specific\`          \`scopable\`: one value per channel.
                              \`{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}\`
  \`channel_locale_specific\`   both: one value per channel AND language tag.
                              \`{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}\`

A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then \`common\`. \`common\` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. \`GET /products/attribute-schema\` answers, per field, the exact path a value belongs at (\`storage.path\`) and that full fallback order (\`from\`), so no client has to re-derive any of this.

The value itself is whatever the attribute's \`type\` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, \`{"amount": …, "unit": …}\` for a measure, a list of \`{"amount": …, "currency": …}\` for a price, an asset code for media.

Defaults to \`{}\`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.

Which attributes an asset of this family has comes from \`attributes\` rows with \`entity_type: "asset"\` and \`entity_ref\` equal to the family's code — alt text, copyright, an expiry date.`)
  .option(`--code <code>`, `The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.`)
  .option(`--delivery-path <delivery-path>`, `The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.`)
  .option(`--external-url <external-url>`, `Absolute URL of an externally hosted file. Required when \`source\` is \`external\`, and accepted only when the tenant has \`allow_external_media\` on and the host is on its \`external_media_allowed_hosts\` list — \`POST /products/assets\` is the only place an external URL can enter the catalog, so it is the only place those are enforced.`)
  .option(`--source <source>`, `Where the bytes live: 'storage' is this platform's object store and needs \`storage_asset_id\`, 'external' is somebody else's host and needs \`external_url\`. The database enforces the pair, so neither half can be stored on its own.`)
  .option(`--storage-asset-id <storage-asset-id>`, `The stable \`ast_…\` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when \`source\` is \`storage\`.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, assetFamilyId, attributeValues, code, deliveryPath, externalUrl, source, storageAssetId } = await promptForMissing(
          _options,
          updateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/assets/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (assetFamilyId !== undefined) {
          _payload[`asset_family_id`] = assetFamilyId;
        }
        if (attributeValues !== undefined) {
          _payload[`attribute_values`] = resolveBodyParam(attributeValues);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (deliveryPath !== undefined) {
          _payload[`delivery_path`] = deliveryPath;
        }
        if (externalUrl !== undefined) {
          _payload[`external_url`] = externalUrl;
        }
        if (source !== undefined) {
          _payload[`source`] = source;
        }
        if (storageAssetId !== undefined) {
          _payload[`storage_asset_id`] = storageAssetId;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `put`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsAssets.commands.at(-1)!, updateSpecs, { method: "put" });
