import { Command } from "commander";
import { resolveBodyParam } from "../../utils.js";
import { sdkForProject } from "../../sdks.js";
import type { RequestParams } from "../../types.js";
import {
  actionRunner,
  commandDescriptions,
  cliConfig,
  parse,
  parseInteger,
} from "../../parser.js";
import {
  confirmDestructive,
  promptForMissing,
  type PromptSpec,
  registerPromptSpecs,
} from "../../interactive.js";

export const productsReferences = new Command("products-references")
  .description(
    commandDescriptions["productsReferences"] ??
      `Reference entities and their records — the domains this catalog POINTS AT instead of duplicating. A brand, a manufacturer, a care instruction is one record here, edited once, and every product that uses it stores only its code. A reference entity carries attributes of its own, so its records hold real data rather than just a name; that shape is declared in Data model and read back with the attribute-schema call there.`,
  )
  .configureHelp({
    helpWidth: process.stdout.columns || 80,
  });

const productsReferenceEntitiesListSpecs: PromptSpec[] = [
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Page size (default 50, max 200). A larger value is clamped rather than refused.", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.", type: "integer", required: false },
  { key: "order", option: "--order <order>", name: "order", description: "Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.", type: "string", required: false },
  { key: "id", option: "--id <id>", name: "id", description: "Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.", type: "string", required: false },
  { key: "code", option: "--code <code>", name: "code", description: "Exact match on `code`. The entity's stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.", type: "string", required: false },
  { key: "labels", option: "--labels <labels>", name: "labels", description: "Exact match on `labels`. What the entity is called, per language tag — the heading over its record list. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "image", option: "--image <image>", name: "image", description: "Exact match on `image`. A delivery path or URL for the entity's own icon. Cosmetic — nothing in this app resolves it.", type: "string", required: false },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "Exact match on `external_id`. The key this domain has in the system that owns it — the register a brand or manufacturer list is maintained in. Unique per tenant where set.", type: "string", required: false },
  { key: "externalRefs", option: "--external-refs <external-refs>", name: "external_refs", description: "Exact match on `external_refs`. Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "Exact match on `source_synced_at`. When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.", type: "string", required: false },
  { key: "sourceData", option: "--source-data <source-data>", name: "source_data", description: "Exact match on `source_data`. What the source said about this row, kept as it said it: `{\"system\": …, \"etag\": …, \"raw\": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "metadata", option: "--metadata <metadata>", name: "metadata", description: "Exact match on `metadata`. Free-form jsonb this tenant owns, for anything about a reference domain this app does not model. Nothing here reads it. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.", type: "string", required: false },
  { key: "updatedAt", option: "--updated-at <updated-at>", name: "updated_at", description: "Exact match on `updated_at`. When the row was last written. Server-set — it is not part of any request body.", type: "string", required: false },
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
productsReferences
  .command(`products-reference-entities-list`)
  .description(`A domain of records the catalog POINTS AT instead of duplicating — brands, manufacturers, care instructions. Declaring one is how a brand comes to be edited in one place rather than on nine thousand products. A reference entity has attributes of its own (\`attributes\` rows with \`entity_type: "reference_entity"\` and this entity's code as \`entity_ref\`), which is what makes its records more than a label.

Every column of \`reference_entities\` is an exact-match query parameter, \`order\` sorts by one column, and \`limit\`/\`offset\` page through \`page.total\`. A query key that is NOT a column is dropped rather than refused, and the \`filter\` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.

Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.`)
  .option(`--limit <limit>`, `Page size (default 50, max 200). A larger value is clamped rather than refused.`, parseInteger)
  .option(`--offset <offset>`, `Row offset for pagination (default 0). Page with \`page.total\` and \`page.hasMore\`.`, parseInteger)
  .option(`--order <order>`, `Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.`)
  .option(`--id <id>`, `Exact match on \`id\`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.`)
  .option(`--code <code>`, `Exact match on \`code\`. The entity's stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.`)
  .option(`--labels <labels>`, `Exact match on \`labels\`. What the entity is called, per language tag — the heading over its record list. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--image <image>`, `Exact match on \`image\`. A delivery path or URL for the entity's own icon. Cosmetic — nothing in this app resolves it.`)
  .option(`--external-id <external-id>`, `Exact match on \`external_id\`. The key this domain has in the system that owns it — the register a brand or manufacturer list is maintained in. Unique per tenant where set.`)
  .option(`--external-refs <external-refs>`, `Exact match on \`external_refs\`. Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. \`external_id\` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by \`external_id\` and take this off the answer. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--source-synced-at <source-synced-at>`, `Exact match on \`source_synced_at\`. When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.`)
  .option(`--source-data <source-data>`, `Exact match on \`source_data\`. What the source said about this row, kept as it said it: \`{"system": …, "etag": …, "raw": {…}}\`. The \`etag\` is what a write-back has to hand back in \`If-Match\`, and between two runs there is nowhere else to keep it. \`raw\` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--metadata <metadata>`, `Exact match on \`metadata\`. Free-form jsonb this tenant owns, for anything about a reference domain this app does not model. Nothing here reads it. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--created-at <created-at>`, `Exact match on \`created_at\`. When the row was created. Server-set — it is not part of any request body.`)
  .option(`--updated-at <updated-at>`, `Exact match on \`updated_at\`. When the row was last written. Server-set — it is not part of any request body.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { limit, offset, order, id, code, labels, image, externalId, externalRefs, sourceSyncedAt, sourceData, metadata, createdAt, updatedAt, filter } = await promptForMissing(
          _options,
          productsReferenceEntitiesListSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/reference_entities`;
        const _payload: RequestParams = {};
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        if (order !== undefined) {
          _payload[`order`] = order;
        }
        if (id !== undefined) {
          _payload[`id`] = id;
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (labels !== undefined) {
          _payload[`labels`] = labels;
        }
        if (image !== undefined) {
          _payload[`image`] = image;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (externalRefs !== undefined) {
          _payload[`external_refs`] = externalRefs;
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        if (sourceData !== undefined) {
          _payload[`source_data`] = sourceData;
        }
        if (metadata !== undefined) {
          _payload[`metadata`] = metadata;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        if (updatedAt !== undefined) {
          _payload[`updated_at`] = updatedAt;
        }
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsReferences.commands.at(-1)!, productsReferenceEntitiesListSpecs, { method: "get" });
const productsReferenceEntitiesCreateSpecs: PromptSpec[] = [
  { key: "code", option: "--code <code>", name: "code", description: "The entity's stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.", type: "string", required: true },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "The key this domain has in the system that owns it — the register a brand or manufacturer list is maintained in. Unique per tenant where set.", type: "string", required: false },
  { key: "externalRefs", option: "--external-refs <external-refs>", name: "external_refs", description: "Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer.", type: "object", required: false },
  { key: "image", option: "--image <image>", name: "image", description: "A delivery path or URL for the entity's own icon. Cosmetic — nothing in this app resolves it.", type: "string", required: false },
  { key: "labels", option: "--labels <labels>", name: "labels", description: "What the entity is called, per language tag — the heading over its record list.", type: "object", required: false },
  { key: "metadata", option: "--metadata <metadata>", name: "metadata", description: "Free-form jsonb this tenant owns, for anything about a reference domain this app does not model. Nothing here reads it.", type: "object", required: false },
  { key: "sourceData", option: "--source-data <source-data>", name: "source_data", description: "What the source said about this row, kept as it said it: `{\"system\": …, \"etag\": …, \"raw\": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.", type: "object", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.", type: "string", required: false },
];
productsReferences
  .command(`products-reference-entities-create`)
  .description(`Creates one reference entity and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.

A domain of records the catalog POINTS AT instead of duplicating — brands, manufacturers, care instructions. Declaring one is how a brand comes to be edited in one place rather than on nine thousand products. A reference entity has attributes of its own (\`attributes\` rows with \`entity_type: "reference_entity"\` and this entity's code as \`entity_ref\`), which is what makes its records more than a label.

\`code\` is the only column the database refuses the row without; everything else has a default or is nullable. A second row with the same \`code\` answers 409.`)
  .option(`--code <code>`, `The entity's stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.`)
  .option(`--external-id <external-id>`, `The key this domain has in the system that owns it — the register a brand or manufacturer list is maintained in. Unique per tenant where set.`)
  .option(`--external-refs <external-refs>`, `Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. \`external_id\` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by \`external_id\` and take this off the answer.`)
  .option(`--image <image>`, `A delivery path or URL for the entity's own icon. Cosmetic — nothing in this app resolves it.`)
  .option(`--labels <labels>`, `What the entity is called, per language tag — the heading over its record list.`)
  .option(`--metadata <metadata>`, `Free-form jsonb this tenant owns, for anything about a reference domain this app does not model. Nothing here reads it.`)
  .option(`--source-data <source-data>`, `What the source said about this row, kept as it said it: \`{"system": …, "etag": …, "raw": {…}}\`. The \`etag\` is what a write-back has to hand back in \`If-Match\`, and between two runs there is nowhere else to keep it. \`raw\` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.`)
  .option(`--source-synced-at <source-synced-at>`, `When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { code, externalId, externalRefs, image, labels, metadata, sourceData, sourceSyncedAt } = await promptForMissing(
          _options,
          productsReferenceEntitiesCreateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/reference_entities`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (externalRefs !== undefined) {
          _payload[`external_refs`] = resolveBodyParam(externalRefs);
        }
        if (image !== undefined) {
          _payload[`image`] = image;
        }
        if (labels !== undefined) {
          _payload[`labels`] = resolveBodyParam(labels);
        }
        if (metadata !== undefined) {
          _payload[`metadata`] = resolveBodyParam(metadata);
        }
        if (sourceData !== undefined) {
          _payload[`source_data`] = resolveBodyParam(sourceData);
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsReferences.commands.at(-1)!, productsReferenceEntitiesCreateSpecs, { method: "post" });
const productsReferenceEntitiesDeleteSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `reference_entities` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entities`. An id no reference entitie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/reference_entities", hasLimit: true } },
];
productsReferences
  .command(`products-reference-entities-delete`)
  .description(`Deletes one reference entity by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.

It takes what hangs off it: reference entity records (\`reference_entity_id\`) are deleted with it.

An id no reference entity of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.`)
  .option(`--id <id>`, `The \`reference_entities\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/reference_entities\`. An id no reference entitie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          productsReferenceEntitiesDeleteSpecs,
          _command,
        );
        await confirmDestructive(`products-references products-reference-entities-delete`);
        const _client = await sdkForProject();
        const _apiPath = `/products/reference_entities/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `delete`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsReferences.commands.at(-1)!, productsReferenceEntitiesDeleteSpecs, { method: "delete", destructive: true });
const productsReferenceEntitiesGetSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `reference_entities` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entities`. An id no reference entitie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/reference_entities", hasLimit: true } },
];
productsReferences
  .command(`products-reference-entities-get`)
  .description(`Reads one reference entity by its id — the whole row, every column, as it is stored.

A domain of records the catalog POINTS AT instead of duplicating — brands, manufacturers, care instructions. Declaring one is how a brand comes to be edited in one place rather than on nine thousand products. A reference entity has attributes of its own (\`attributes\` rows with \`entity_type: "reference_entity"\` and this entity's code as \`entity_ref\`), which is what makes its records more than a label.

An id no reference entity of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.

Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.`)
  .option(`--id <id>`, `The \`reference_entities\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/reference_entities\`. An id no reference entitie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          productsReferenceEntitiesGetSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/reference_entities/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsReferences.commands.at(-1)!, productsReferenceEntitiesGetSpecs, { method: "get" });
const productsReferenceEntitiesUpdateSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `reference_entities` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entities`. An id no reference entitie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/reference_entities", hasLimit: true } },
  { key: "code", option: "--code <code>", name: "code", description: "The entity's stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.", type: "string", required: false },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "The key this domain has in the system that owns it — the register a brand or manufacturer list is maintained in. Unique per tenant where set.", type: "string", required: false },
  { key: "externalRefs", option: "--external-refs <external-refs>", name: "external_refs", description: "Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer.", type: "object", required: false },
  { key: "image", option: "--image <image>", name: "image", description: "A delivery path or URL for the entity's own icon. Cosmetic — nothing in this app resolves it.", type: "string", required: false },
  { key: "labels", option: "--labels <labels>", name: "labels", description: "What the entity is called, per language tag — the heading over its record list.", type: "object", required: false },
  { key: "metadata", option: "--metadata <metadata>", name: "metadata", description: "Free-form jsonb this tenant owns, for anything about a reference domain this app does not model. Nothing here reads it.", type: "object", required: false },
  { key: "sourceData", option: "--source-data <source-data>", name: "source_data", description: "What the source said about this row, kept as it said it: `{\"system\": …, \"etag\": …, \"raw\": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.", type: "object", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.", type: "string", required: false },
];
productsReferences
  .command(`products-reference-entities-update`)
  .description(`Updates one reference entity by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.

A domain of records the catalog POINTS AT instead of duplicating — brands, manufacturers, care instructions. Declaring one is how a brand comes to be edited in one place rather than on nine thousand products. A reference entity has attributes of its own (\`attributes\` rows with \`entity_type: "reference_entity"\` and this entity's code as \`entity_ref\`), which is what makes its records more than a label.

A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on \`code\` answers 409.`)
  .option(`--id <id>`, `The \`reference_entities\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/reference_entities\`. An id no reference entitie of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .option(`--code <code>`, `The entity's stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.`)
  .option(`--external-id <external-id>`, `The key this domain has in the system that owns it — the register a brand or manufacturer list is maintained in. Unique per tenant where set.`)
  .option(`--external-refs <external-refs>`, `Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. \`external_id\` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by \`external_id\` and take this off the answer.`)
  .option(`--image <image>`, `A delivery path or URL for the entity's own icon. Cosmetic — nothing in this app resolves it.`)
  .option(`--labels <labels>`, `What the entity is called, per language tag — the heading over its record list.`)
  .option(`--metadata <metadata>`, `Free-form jsonb this tenant owns, for anything about a reference domain this app does not model. Nothing here reads it.`)
  .option(`--source-data <source-data>`, `What the source said about this row, kept as it said it: \`{"system": …, "etag": …, "raw": {…}}\`. The \`etag\` is what a write-back has to hand back in \`If-Match\`, and between two runs there is nowhere else to keep it. \`raw\` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.`)
  .option(`--source-synced-at <source-synced-at>`, `When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, code, externalId, externalRefs, image, labels, metadata, sourceData, sourceSyncedAt } = await promptForMissing(
          _options,
          productsReferenceEntitiesUpdateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/reference_entities/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (externalRefs !== undefined) {
          _payload[`external_refs`] = resolveBodyParam(externalRefs);
        }
        if (image !== undefined) {
          _payload[`image`] = image;
        }
        if (labels !== undefined) {
          _payload[`labels`] = resolveBodyParam(labels);
        }
        if (metadata !== undefined) {
          _payload[`metadata`] = resolveBodyParam(metadata);
        }
        if (sourceData !== undefined) {
          _payload[`source_data`] = resolveBodyParam(sourceData);
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `put`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsReferences.commands.at(-1)!, productsReferenceEntitiesUpdateSpecs, { method: "put" });
const productsReferenceEntityRecordsListSpecs: PromptSpec[] = [
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Page size (default 50, max 200). A larger value is clamped rather than refused.", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.", type: "integer", required: false },
  { key: "order", option: "--order <order>", name: "order", description: "Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.", type: "string", required: false },
  { key: "id", option: "--id <id>", name: "id", description: "Exact match on `id`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.", type: "string", required: false },
  { key: "referenceEntityId", option: "--reference-entity-id <reference-entity-id>", name: "reference_entity_id", description: "Exact match on `reference_entity_id`. Which reference entity this record belongs to.", type: "string", required: false },
  { key: "code", option: "--code <code>", name: "code", description: "Exact match on `code`. The record's stable identifier — the value a product stores when it points at this record, the same way a select stores an option code. Unique within the entity.", type: "string", required: false },
  { key: "labels", option: "--labels <labels>", name: "labels", description: "Exact match on `labels`. What the record is called, per language tag — the text a picker shows while the code is what gets written. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "attributeValues", option: "--attribute-values <attribute-values>", name: "attribute_values", description: "Exact match on `attribute_values`. Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "Exact match on `external_id`. The key this record has in the system that owns it — a manufacturer number in the ERP, a supplier row keyed by GLN, a brand id in the PIM. Unique per tenant where set, so a brand list re-imports without founding a second Acme. Distinct from `code`, which is the value a product stores when it points here.", type: "string", required: false },
  { key: "externalRefs", option: "--external-refs <external-refs>", name: "external_refs", description: "Exact match on `external_refs`. Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "Exact match on `source_synced_at`. When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.", type: "string", required: false },
  { key: "sourceData", option: "--source-data <source-data>", name: "source_data", description: "Exact match on `source_data`. What the source said about this row, kept as it said it: `{\"system\": …, \"etag\": …, \"raw\": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and `null` cannot be matched this way. A value that does not parse as JSON is refused with 400 `invalid_value`, naming this filter, before the request reaches the data plane.", type: "string", required: false },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "Exact match on `created_at`. When the row was created. Server-set — it is not part of any request body.", type: "string", required: false },
  { key: "updatedAt", option: "--updated-at <updated-at>", name: "updated_at", description: "Exact match on `updated_at`. When the row was last written. Server-set — it is not part of any request body.", type: "string", required: false },
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
productsReferences
  .command(`products-reference-entity-records-list`)
  .description(`One record of a reference entity — one brand, one manufacturer. A product that points at it stores this record's CODE, exactly the way a select stores an option code, and the record's own properties live in its scoped \`attribute_values\` document. \`GET /products/attribute-schema\` offers these records as the \`options\` of any attribute that points at their entity, so a picker needs no second call.

Every column of \`reference_entity_records\` is an exact-match query parameter, \`order\` sorts by one column, and \`limit\`/\`offset\` page through \`page.total\`. A query key that is NOT a column is dropped rather than refused, and the \`filter\` object echoes the ones that were understood — that echo is the only way to tell an unfiltered answer from an empty one. It reads rows exactly as they are stored: no join is resolved, no jsonb value is unpacked.

Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.`)
  .option(`--limit <limit>`, `Page size (default 50, max 200). A larger value is clamped rather than refused.`, parseInteger)
  .option(`--offset <offset>`, `Row offset for pagination (default 0). Page with \`page.total\` and \`page.hasMore\`.`, parseInteger)
  .option(`--order <order>`, `Sort by one column: 'column' | 'column.asc' | 'column.desc'. A bare column sorts ascending. Anything else is refused with 400.`)
  .option(`--id <id>`, `Exact match on \`id\`. The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.`)
  .option(`--reference-entity-id <reference-entity-id>`, `Exact match on \`reference_entity_id\`. Which reference entity this record belongs to.`)
  .option(`--code <code>`, `Exact match on \`code\`. The record's stable identifier — the value a product stores when it points at this record, the same way a select stores an option code. Unique within the entity.`)
  .option(`--labels <labels>`, `Exact match on \`labels\`. What the record is called, per language tag — the text a picker shows while the code is what gets written. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--attribute-values <attribute-values>`, `Exact match on \`attribute_values\`. Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in \`attributes\`, selected per family by \`family_attributes\`, and their values live under their attribute CODE inside this object. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--external-id <external-id>`, `Exact match on \`external_id\`. The key this record has in the system that owns it — a manufacturer number in the ERP, a supplier row keyed by GLN, a brand id in the PIM. Unique per tenant where set, so a brand list re-imports without founding a second Acme. Distinct from \`code\`, which is the value a product stores when it points here.`)
  .option(`--external-refs <external-refs>`, `Exact match on \`external_refs\`. Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. \`external_id\` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by \`external_id\` and take this off the answer. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--source-synced-at <source-synced-at>`, `Exact match on \`source_synced_at\`. When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.`)
  .option(`--source-data <source-data>`, `Exact match on \`source_data\`. What the source said about this row, kept as it said it: \`{"system": …, "etag": …, "raw": {…}}\`. The \`etag\` is what a write-back has to hand back in \`If-Match\`, and between two runs there is nowhere else to keep it. \`raw\` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it. The whole jsonb document is compared, serialized as JSON — this is equality, not a path or containment query, and \`null\` cannot be matched this way. A value that does not parse as JSON is refused with 400 \`invalid_value\`, naming this filter, before the request reaches the data plane.`)
  .option(`--created-at <created-at>`, `Exact match on \`created_at\`. When the row was created. Server-set — it is not part of any request body.`)
  .option(`--updated-at <updated-at>`, `Exact match on \`updated_at\`. When the row was last written. Server-set — it is not part of any request body.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { limit, offset, order, id, referenceEntityId, code, labels, attributeValues, externalId, externalRefs, sourceSyncedAt, sourceData, createdAt, updatedAt, filter } = await promptForMissing(
          _options,
          productsReferenceEntityRecordsListSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/reference_entity_records`;
        const _payload: RequestParams = {};
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        if (order !== undefined) {
          _payload[`order`] = order;
        }
        if (id !== undefined) {
          _payload[`id`] = id;
        }
        if (referenceEntityId !== undefined) {
          _payload[`reference_entity_id`] = referenceEntityId;
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (labels !== undefined) {
          _payload[`labels`] = labels;
        }
        if (attributeValues !== undefined) {
          _payload[`attribute_values`] = attributeValues;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (externalRefs !== undefined) {
          _payload[`external_refs`] = externalRefs;
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        if (sourceData !== undefined) {
          _payload[`source_data`] = sourceData;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        if (updatedAt !== undefined) {
          _payload[`updated_at`] = updatedAt;
        }
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsReferences.commands.at(-1)!, productsReferenceEntityRecordsListSpecs, { method: "get" });
const productsReferenceEntityRecordsCreateSpecs: PromptSpec[] = [
  { key: "code", option: "--code <code>", name: "code", description: "The record's stable identifier — the value a product stores when it points at this record, the same way a select stores an option code. Unique within the entity.", type: "string", required: true },
  { key: "referenceEntityId", option: "--reference-entity-id <reference-entity-id>", name: "reference_entity_id", description: "Which reference entity this record belongs to.", type: "string", required: true },
  { key: "attributeValues", option: "--attribute-values <attribute-values>", name: "attribute_values", description: "Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.\n\nFour buckets, and an attribute's own flags decide which one it writes to:\n\n  `common`                    the attribute is neither localizable nor scopable — one value, full stop.\n                              `{\"common\": {\"net_weight\": 2.4, \"colour\": \"black\"}}`\n  `locale_specific`           `localizable`: one value per language tag.\n                              `{\"locale_specific\": {\"de_DE\": {\"name\": \"Akku-Bohrschrauber\"}}}`\n  `channel_specific`          `scopable`: one value per channel.\n                              `{\"channel_specific\": {\"b2b\": {\"minimum_order_quantity\": 6}}}`\n  `channel_locale_specific`   both: one value per channel AND language tag.\n                              `{\"channel_locale_specific\": {\"b2b\": {\"de_DE\": {\"description\": \"…\"}}}}`\n\nA reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.\n\nThe value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{\"amount\": …, \"unit\": …}` for a measure, a list of `{\"amount\": …, \"currency\": …}` for a price, an asset code for media.\n\nDefaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.\n\nWhich attributes a record of this entity has comes from `attributes` rows with `entity_type: \"reference_entity\"` and `entity_ref` equal to the entity's code — `GET /products/attribute-schema?entity_type=reference_entity&entity_ref=brand` answers it in one call.", type: "object", required: false },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "The key this record has in the system that owns it — a manufacturer number in the ERP, a supplier row keyed by GLN, a brand id in the PIM. Unique per tenant where set, so a brand list re-imports without founding a second Acme. Distinct from `code`, which is the value a product stores when it points here.", type: "string", required: false },
  { key: "externalRefs", option: "--external-refs <external-refs>", name: "external_refs", description: "Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer.", type: "object", required: false },
  { key: "labels", option: "--labels <labels>", name: "labels", description: "What the record is called, per language tag — the text a picker shows while the code is what gets written.", type: "object", required: false },
  { key: "sourceData", option: "--source-data <source-data>", name: "source_data", description: "What the source said about this row, kept as it said it: `{\"system\": …, \"etag\": …, \"raw\": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.", type: "object", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.", type: "string", required: false },
];
productsReferences
  .command(`products-reference-entity-records-create`)
  .description(`Creates one reference entity record and answers 201 with the stored row, including the id and the timestamps the database filled in — a client never sends an id, it reads one back and uses it in the path of every later call.

One record of a reference entity — one brand, one manufacturer. A product that points at it stores this record's CODE, exactly the way a select stores an option code, and the record's own properties live in its scoped \`attribute_values\` document. \`GET /products/attribute-schema\` offers these records as the \`options\` of any attribute that points at their entity, so a picker needs no second call.

\`reference_entity_id\` and \`code\` are the only columns the database refuses the row without; everything else has a default or is nullable. A second row with the same \`reference_entity_id\` and \`code\` answers 409.`)
  .option(`--code <code>`, `The record's stable identifier — the value a product stores when it points at this record, the same way a select stores an option code. Unique within the entity.`)
  .option(`--reference-entity-id <reference-entity-id>`, `Which reference entity this record belongs to.`)
  .option(`--attribute-values <attribute-values>`, `Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in \`attributes\`, selected per family by \`family_attributes\`, and their values live under their attribute CODE inside this object.

Four buckets, and an attribute's own flags decide which one it writes to:

  \`common\`                    the attribute is neither localizable nor scopable — one value, full stop.
                              \`{"common": {"net_weight": 2.4, "colour": "black"}}\`
  \`locale_specific\`           \`localizable\`: one value per language tag.
                              \`{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}\`
  \`channel_specific\`          \`scopable\`: one value per channel.
                              \`{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}\`
  \`channel_locale_specific\`   both: one value per channel AND language tag.
                              \`{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}\`

A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then \`common\`. \`common\` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. \`GET /products/attribute-schema\` answers, per field, the exact path a value belongs at (\`storage.path\`) and that full fallback order (\`from\`), so no client has to re-derive any of this.

The value itself is whatever the attribute's \`type\` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, \`{"amount": …, "unit": …}\` for a measure, a list of \`{"amount": …, "currency": …}\` for a price, an asset code for media.

Defaults to \`{}\`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.

Which attributes a record of this entity has comes from \`attributes\` rows with \`entity_type: "reference_entity"\` and \`entity_ref\` equal to the entity's code — \`GET /products/attribute-schema?entity_type=reference_entity&entity_ref=brand\` answers it in one call.`)
  .option(`--external-id <external-id>`, `The key this record has in the system that owns it — a manufacturer number in the ERP, a supplier row keyed by GLN, a brand id in the PIM. Unique per tenant where set, so a brand list re-imports without founding a second Acme. Distinct from \`code\`, which is the value a product stores when it points here.`)
  .option(`--external-refs <external-refs>`, `Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. \`external_id\` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by \`external_id\` and take this off the answer.`)
  .option(`--labels <labels>`, `What the record is called, per language tag — the text a picker shows while the code is what gets written.`)
  .option(`--source-data <source-data>`, `What the source said about this row, kept as it said it: \`{"system": …, "etag": …, "raw": {…}}\`. The \`etag\` is what a write-back has to hand back in \`If-Match\`, and between two runs there is nowhere else to keep it. \`raw\` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.`)
  .option(`--source-synced-at <source-synced-at>`, `When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { code, referenceEntityId, attributeValues, externalId, externalRefs, labels, sourceData, sourceSyncedAt } = await promptForMissing(
          _options,
          productsReferenceEntityRecordsCreateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/reference_entity_records`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (attributeValues !== undefined) {
          _payload[`attribute_values`] = resolveBodyParam(attributeValues);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (externalRefs !== undefined) {
          _payload[`external_refs`] = resolveBodyParam(externalRefs);
        }
        if (labels !== undefined) {
          _payload[`labels`] = resolveBodyParam(labels);
        }
        if (referenceEntityId !== undefined) {
          _payload[`reference_entity_id`] = referenceEntityId;
        }
        if (sourceData !== undefined) {
          _payload[`source_data`] = resolveBodyParam(sourceData);
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsReferences.commands.at(-1)!, productsReferenceEntityRecordsCreateSpecs, { method: "post" });
const productsReferenceEntityRecordsDeleteSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `reference_entity_records` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entity_records`. An id no reference entity record of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/reference_entity_records", hasLimit: true } },
];
productsReferences
  .command(`products-reference-entity-records-delete`)
  .description(`Deletes one reference entity record by id. It is a hard delete — the row is gone, and the answer is a confirmation rather than a result to branch on.

Nothing in this schema references it, so nothing else changes.

An id no reference entity record of this tenant carries answers 404; there is no 409, because every foreign key pointing at this entity resolves itself on delete rather than blocking one.`)
  .option(`--id <id>`, `The \`reference_entity_records\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/reference_entity_records\`. An id no reference entity record of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          productsReferenceEntityRecordsDeleteSpecs,
          _command,
        );
        await confirmDestructive(`products-references products-reference-entity-records-delete`);
        const _client = await sdkForProject();
        const _apiPath = `/products/reference_entity_records/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `delete`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsReferences.commands.at(-1)!, productsReferenceEntityRecordsDeleteSpecs, { method: "delete", destructive: true });
const productsReferenceEntityRecordsGetSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `reference_entity_records` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entity_records`. An id no reference entity record of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/reference_entity_records", hasLimit: true } },
];
productsReferences
  .command(`products-reference-entity-records-get`)
  .description(`Reads one reference entity record by its id — the whole row, every column, as it is stored.

One record of a reference entity — one brand, one manufacturer. A product that points at it stores this record's CODE, exactly the way a select stores an option code, and the record's own properties live in its scoped \`attribute_values\` document. \`GET /products/attribute-schema\` offers these records as the \`options\` of any attribute that points at their entity, so a picker needs no second call.

An id no reference entity record of this tenant carries answers 404, and so does one belonging to another tenant: row-level security makes that row invisible rather than forbidden. A malformed id answers 400 before the route is reached.

Answered from the gateway's tenant cache for up to 30 minutes and dropped the moment this entity is written, because the data model changes weekly at most and every product page asks the same question.`)
  .option(`--id <id>`, `The \`reference_entity_records\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/reference_entity_records\`. An id no reference entity record of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          productsReferenceEntityRecordsGetSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/reference_entity_records/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsReferences.commands.at(-1)!, productsReferenceEntityRecordsGetSpecs, { method: "get" });
const productsReferenceEntityRecordsUpdateSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The `reference_entity_records` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from `GET /v1/products/reference_entity_records`. An id no reference entity record of this tenant carries answers 404; a malformed one answers 400 before the route is reached.", type: "string", required: true, resource: { listPath: "/products/reference_entity_records", hasLimit: true } },
  { key: "attributeValues", option: "--attribute-values <attribute-values>", name: "attribute_values", description: "Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.\n\nFour buckets, and an attribute's own flags decide which one it writes to:\n\n  `common`                    the attribute is neither localizable nor scopable — one value, full stop.\n                              `{\"common\": {\"net_weight\": 2.4, \"colour\": \"black\"}}`\n  `locale_specific`           `localizable`: one value per language tag.\n                              `{\"locale_specific\": {\"de_DE\": {\"name\": \"Akku-Bohrschrauber\"}}}`\n  `channel_specific`          `scopable`: one value per channel.\n                              `{\"channel_specific\": {\"b2b\": {\"minimum_order_quantity\": 6}}}`\n  `channel_locale_specific`   both: one value per channel AND language tag.\n                              `{\"channel_locale_specific\": {\"b2b\": {\"de_DE\": {\"description\": \"…\"}}}}`\n\nA reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.\n\nThe value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{\"amount\": …, \"unit\": …}` for a measure, a list of `{\"amount\": …, \"currency\": …}` for a price, an asset code for media.\n\nDefaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.\n\nWhich attributes a record of this entity has comes from `attributes` rows with `entity_type: \"reference_entity\"` and `entity_ref` equal to the entity's code — `GET /products/attribute-schema?entity_type=reference_entity&entity_ref=brand` answers it in one call.", type: "object", required: false },
  { key: "code", option: "--code <code>", name: "code", description: "The record's stable identifier — the value a product stores when it points at this record, the same way a select stores an option code. Unique within the entity.", type: "string", required: false },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "The key this record has in the system that owns it — a manufacturer number in the ERP, a supplier row keyed by GLN, a brand id in the PIM. Unique per tenant where set, so a brand list re-imports without founding a second Acme. Distinct from `code`, which is the value a product stores when it points here.", type: "string", required: false },
  { key: "externalRefs", option: "--external-refs <external-refs>", name: "external_refs", description: "Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. `external_id` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by `external_id` and take this off the answer.", type: "object", required: false },
  { key: "labels", option: "--labels <labels>", name: "labels", description: "What the record is called, per language tag — the text a picker shows while the code is what gets written.", type: "object", required: false },
  { key: "referenceEntityId", option: "--reference-entity-id <reference-entity-id>", name: "reference_entity_id", description: "Which reference entity this record belongs to.", type: "string", required: false },
  { key: "sourceData", option: "--source-data <source-data>", name: "source_data", description: "What the source said about this row, kept as it said it: `{\"system\": …, \"etag\": …, \"raw\": {…}}`. The `etag` is what a write-back has to hand back in `If-Match`, and between two runs there is nowhere else to keep it. `raw` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.", type: "object", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.", type: "string", required: false },
];
productsReferences
  .command(`products-reference-entity-records-update`)
  .description(`Updates one reference entity record by id. A partial patch: the body names only the columns to change and every column it leaves out keeps its current value, so there is no read-modify-write and no way to blank a field by forgetting it.

One record of a reference entity — one brand, one manufacturer. A product that points at it stores this record's CODE, exactly the way a select stores an option code, and the record's own properties live in its scoped \`attribute_values\` document. \`GET /products/attribute-schema\` offers these records as the \`options\` of any attribute that points at their entity, so a picker needs no second call.

A body that names nothing writable is refused with 400 rather than answered as a no-op, an id nobody carries answers 404, and a value that collides on \`reference_entity_id\` and \`code\` answers 409.`)
  .option(`--id <id>`, `The \`reference_entity_records\` row to address, by id. It names a row THIS TENANT holds, so no example is published — a uuid this app invented would document a call that answers 404, and a real one would be another tenant's data. Read one from \`GET /v1/products/reference_entity_records\`. An id no reference entity record of this tenant carries answers 404; a malformed one answers 400 before the route is reached.`)
  .option(`--attribute-values <attribute-values>`, `Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in \`attributes\`, selected per family by \`family_attributes\`, and their values live under their attribute CODE inside this object.

Four buckets, and an attribute's own flags decide which one it writes to:

  \`common\`                    the attribute is neither localizable nor scopable — one value, full stop.
                              \`{"common": {"net_weight": 2.4, "colour": "black"}}\`
  \`locale_specific\`           \`localizable\`: one value per language tag.
                              \`{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}\`
  \`channel_specific\`          \`scopable\`: one value per channel.
                              \`{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}\`
  \`channel_locale_specific\`   both: one value per channel AND language tag.
                              \`{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}\`

A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then \`common\`. \`common\` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. \`GET /products/attribute-schema\` answers, per field, the exact path a value belongs at (\`storage.path\`) and that full fallback order (\`from\`), so no client has to re-derive any of this.

The value itself is whatever the attribute's \`type\` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, \`{"amount": …, "unit": …}\` for a measure, a list of \`{"amount": …, "currency": …}\` for a price, an asset code for media.

Defaults to \`{}\`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.

Which attributes a record of this entity has comes from \`attributes\` rows with \`entity_type: "reference_entity"\` and \`entity_ref\` equal to the entity's code — \`GET /products/attribute-schema?entity_type=reference_entity&entity_ref=brand\` answers it in one call.`)
  .option(`--code <code>`, `The record's stable identifier — the value a product stores when it points at this record, the same way a select stores an option code. Unique within the entity.`)
  .option(`--external-id <external-id>`, `The key this record has in the system that owns it — a manufacturer number in the ERP, a supplier row keyed by GLN, a brand id in the PIM. Unique per tenant where set, so a brand list re-imports without founding a second Acme. Distinct from \`code\`, which is the value a product stores when it points here.`)
  .option(`--external-refs <external-refs>`, `Every OTHER system that knows this row, keyed by system name — a second PIM, a supplier's feed, a GTIN register. \`external_id\` is the system that OWNS the row; this is the rest, so the next identifier standard costs a key in here rather than a column and a migration. It filters the way every jsonb column of this app filters: the WHOLE document is compared, so there is no asking for one key — read the row by \`external_id\` and take this off the answer.`)
  .option(`--labels <labels>`, `What the record is called, per language tag — the text a picker shows while the code is what gets written.`)
  .option(`--reference-entity-id <reference-entity-id>`, `Which reference entity this record belongs to.`)
  .option(`--source-data <source-data>`, `What the source said about this row, kept as it said it: \`{"system": …, "etag": …, "raw": {…}}\`. The \`etag\` is what a write-back has to hand back in \`If-Match\`, and between two runs there is nowhere else to keep it. \`raw\` carries the source fields this app does not model, so they survive a round trip instead of being lost the first time somebody edits here. Written by whatever imports the row; nothing in this app reads or maintains it.`)
  .option(`--source-synced-at <source-synced-at>`, `When this row was last CONFIRMED against its source — not when it last changed. A delta run asks for everything it has not seen since its last pass, and over 25 000 products that is the difference between an index scan and reading the whole catalog, which is the reason the column is indexed. An edit made here leaves it alone, so a value that has stopped moving says the feed has gone quiet, not that nobody works the record. Null for a row no source owns.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, attributeValues, code, externalId, externalRefs, labels, referenceEntityId, sourceData, sourceSyncedAt } = await promptForMissing(
          _options,
          productsReferenceEntityRecordsUpdateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/products/reference_entity_records/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (attributeValues !== undefined) {
          _payload[`attribute_values`] = resolveBodyParam(attributeValues);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (externalRefs !== undefined) {
          _payload[`external_refs`] = resolveBodyParam(externalRefs);
        }
        if (labels !== undefined) {
          _payload[`labels`] = resolveBodyParam(labels);
        }
        if (referenceEntityId !== undefined) {
          _payload[`reference_entity_id`] = referenceEntityId;
        }
        if (sourceData !== undefined) {
          _payload[`source_data`] = resolveBodyParam(sourceData);
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `put`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(productsReferences.commands.at(-1)!, productsReferenceEntityRecordsUpdateSpecs, { method: "put" });
