import { Command } from "commander";
import { resolveBodyParam } from "../../utils.js";
import { sdkForProject } from "../../sdks.js";
import type { RequestParams } from "../../types.js";
import {
  actionRunner,
  commandDescriptions,
  cliConfig,
  parse,
  parseInteger,
} from "../../parser.js";
import {
  confirmDestructive,
  promptForMissing,
  type PromptSpec,
  registerPromptSpecs,
} from "../../interactive.js";

export const quotesRanges = new Command("quotes-ranges")
  .description(
    commandDescriptions["quotesRanges"] ??
      `The counters quote numbers are drawn from.`,
  )
  .configureHelp({
    helpWidth: process.stdout.columns || 80,
  });

const listSpecs: PromptSpec[] = [
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Page size (default 50, max 200). A larger value is clamped rather than refused.", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.", type: "integer", required: false },
  { key: "order", option: "--order <order>", name: "order", description: "Sort by one column: 'column' | 'column.asc' | 'column.desc'. The column has to be one this entity has.", type: "string", required: false },
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
quotesRanges
  .command(`list`)
  .description(`The counters quote numbers are drawn from. A market points at one by its \`code\`; the app seeds \`quote\` with the prefix \`ANG-\`.`)
  .option(`--limit <limit>`, `Page size (default 50, max 200). A larger value is clamped rather than refused.`, parseInteger)
  .option(`--offset <offset>`, `Row offset for pagination (default 0). Page with \`page.total\` and \`page.hasMore\`.`, parseInteger)
  .option(`--order <order>`, `Sort by one column: 'column' | 'column.asc' | 'column.desc'. The column has to be one this entity has.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { limit, offset, order, filter } = await promptForMissing(
          _options,
          listSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/quotes/number-ranges`;
        const _payload: RequestParams = {};
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        if (order !== undefined) {
          _payload[`order`] = order;
        }
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(quotesRanges.commands.at(-1)!, listSpecs, { method: "get" });
const createSpecs: PromptSpec[] = [
  { key: "code", option: "--code <code>", name: "code", description: "What a market points at to draw from this range. Unique per tenant; `quote` is the one this app seeds.", type: "string", required: true },
  { key: "counter", option: "--counter <counter>", name: "counter", description: "The last number drawn. The next draw adds `step` and stores the result, so a number is never handed out twice.", type: "integer", required: false },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "When the row was written, stamped by the database.", type: "string", required: false },
  { key: "id", option: "--id <id>", name: "id", description: "The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.", type: "string", required: false },
  { key: "padding", option: "--padding <padding>", name: "padding", description: "How many digits the counter is padded to. 6 gives `000001`.", type: "integer", required: false },
  { key: "positionStep", option: "--position-step <position-step>", name: "position_step", description: "How far apart position numbers sit on a new quote — 10 leaves room to insert a line later without renumbering.", type: "integer", required: false },
  { key: "prefix", option: "--prefix <prefix>", name: "prefix", description: "Put in front of the counter — `ANG-` produces `ANG-000001`.", type: "string", required: false },
  { key: "step", option: "--step <step>", name: "step", description: "How far the counter moves per draw. 1 is consecutive; a larger step leaves gaps on purpose.", type: "integer", required: false },
  { key: "suffix", option: "--suffix <suffix>", name: "suffix", description: "Put after the counter. Empty on the standard range.", type: "string", required: false },
  { key: "tenantId", option: "--tenant-id <tenant-id>", name: "tenant_id", description: "The tenant this row belongs to. Set by the data plane from the request identity and never accepted from a caller.", type: "string", required: false },
  { key: "updatedAt", option: "--updated-at <updated-at>", name: "updated_at", description: "When the row last changed, stamped by the app on every write.", type: "string", required: false },
];
quotesRanges
  .command(`create`)
  .description(`Adds a counter, so one market can number its quotes differently from another. The code is unique per tenant.`)
  .option(`--code <code>`, `What a market points at to draw from this range. Unique per tenant; \`quote\` is the one this app seeds.`)
  .option(`--counter <counter>`, `The last number drawn. The next draw adds \`step\` and stores the result, so a number is never handed out twice.`, parseInteger)
  .option(`--created-at <created-at>`, `When the row was written, stamped by the database.`)
  .option(`--id <id>`, `The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.`)
  .option(`--padding <padding>`, `How many digits the counter is padded to. 6 gives \`000001\`.`, parseInteger)
  .option(`--position-step <position-step>`, `How far apart position numbers sit on a new quote — 10 leaves room to insert a line later without renumbering.`, parseInteger)
  .option(`--prefix <prefix>`, `Put in front of the counter — \`ANG-\` produces \`ANG-000001\`.`)
  .option(`--step <step>`, `How far the counter moves per draw. 1 is consecutive; a larger step leaves gaps on purpose.`, parseInteger)
  .option(`--suffix <suffix>`, `Put after the counter. Empty on the standard range.`)
  .option(`--tenant-id <tenant-id>`, `The tenant this row belongs to. Set by the data plane from the request identity and never accepted from a caller.`)
  .option(`--updated-at <updated-at>`, `When the row last changed, stamped by the app on every write.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { code, counter, createdAt, id, padding, positionStep, prefix, step, suffix, tenantId, updatedAt } = await promptForMissing(
          _options,
          createSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/quotes/number-ranges`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (counter !== undefined) {
          _payload[`counter`] = counter;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        if (id !== undefined) {
          _payload[`id`] = id;
        }
        if (padding !== undefined) {
          _payload[`padding`] = padding;
        }
        if (positionStep !== undefined) {
          _payload[`position_step`] = positionStep;
        }
        if (prefix !== undefined) {
          _payload[`prefix`] = prefix;
        }
        if (step !== undefined) {
          _payload[`step`] = step;
        }
        if (suffix !== undefined) {
          _payload[`suffix`] = suffix;
        }
        if (tenantId !== undefined) {
          _payload[`tenant_id`] = tenantId;
        }
        if (updatedAt !== undefined) {
          _payload[`updated_at`] = updatedAt;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(quotesRanges.commands.at(-1)!, createSpecs, { method: "post" });
const defaultsSpecs: PromptSpec[] = [
  { key: "library", option: "--library [library...]", name: "library", description: "The reusable blocks to create. Idempotent by label among live items. One without a label or without a block tree is reported under `skipped`.", type: "array", required: false },
  { key: "menus", option: "--menus [menus...]", name: "menus", description: "The menus to create. One with no key or no label is reported under `skipped`.", type: "array", required: false },
  { key: "mode", option: "--mode <mode>", name: "mode", description: "`fill` (the default) adds what is missing and keeps everything that exists. `reset` replaces every section that is sent — pages, menus and library items go to the trash first, site settings are removed — and must be asked for by name.", type: "string", required: false, enum: ["fill","reset"] },
  { key: "pages", option: "--pages [pages...]", name: "pages", description: "The pages to create. One that has no `slug` or no `title` is reported under `skipped` rather than refused, so one bad entry never loses the rest.", type: "array", required: false },
  { key: "settings", option: "--settings <settings>", name: "settings", description: "Site settings by key — the same values `PUT /pages/settings/site/{key}` stores. In fill only keys the tenant has not set are written; in reset every existing key is removed first. A key that is not a valid setting name, an empty value or one over 128 KiB is reported under `skipped`.", type: "object", required: false },
];
quotesRanges
  .command(`defaults`)
  .description(`Creates the \`quote\` range if it is missing. Idempotent, and what an integration calls first — the install event does not reliably fire on a marketplace install.`)
  .option(`--library [library...]`, `The reusable blocks to create. Idempotent by label among live items. One without a label or without a block tree is reported under \`skipped\`.`)
  .option(`--menus [menus...]`, `The menus to create. One with no key or no label is reported under \`skipped\`.`)
  .option(`--mode <mode>`, `\`fill\` (the default) adds what is missing and keeps everything that exists. \`reset\` replaces every section that is sent — pages, menus and library items go to the trash first, site settings are removed — and must be asked for by name.`)
  .option(`--pages [pages...]`, `The pages to create. One that has no \`slug\` or no \`title\` is reported under \`skipped\` rather than refused, so one bad entry never loses the rest.`)
  .option(`--settings <settings>`, `Site settings by key — the same values \`PUT /pages/settings/site/{key}\` stores. In fill only keys the tenant has not set are written; in reset every existing key is removed first. A key that is not a valid setting name, an empty value or one over 128 KiB is reported under \`skipped\`.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { library, menus, mode, pages, settings } = await promptForMissing(
          _options,
          defaultsSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/quotes/number-ranges/defaults`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (library !== undefined) {
          _payload[`library`] = library;
        }
        if (menus !== undefined) {
          _payload[`menus`] = menus;
        }
        if (mode !== undefined) {
          _payload[`mode`] = mode;
        }
        if (pages !== undefined) {
          _payload[`pages`] = pages;
        }
        if (settings !== undefined) {
          _payload[`settings`] = resolveBodyParam(settings);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(quotesRanges.commands.at(-1)!, defaultsSpecs, { method: "post" });
const deleteSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The number range.", type: "string", required: true, resource: { listPath: "/quotes/number-ranges", hasLimit: true } },
];
quotesRanges
  .command(`delete`)
  .description(`Removes a counter. The standard one comes back on the next draw rather than breaking quoting.`)
  .option(`--id <id>`, `The number range.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          deleteSpecs,
          _command,
        );
        await confirmDestructive(`quotes-ranges delete`);
        const _client = await sdkForProject();
        const _apiPath = `/quotes/number-ranges/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `delete`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(quotesRanges.commands.at(-1)!, deleteSpecs, { method: "delete", destructive: true });
const getSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The number range.", type: "string", required: true, resource: { listPath: "/quotes/number-ranges", hasLimit: true } },
];
quotesRanges
  .command(`get`)
  .description(`Reads one counter, including where it currently stands.`)
  .option(`--id <id>`, `The number range.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          getSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/quotes/number-ranges/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(quotesRanges.commands.at(-1)!, getSpecs, { method: "get" });
const updateSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The number range.", type: "string", required: true, resource: { listPath: "/quotes/number-ranges", hasLimit: true } },
  { key: "code", option: "--code <code>", name: "code", description: "What a market points at to draw from this range. Unique per tenant; `quote` is the one this app seeds.", type: "string", required: false },
  { key: "counter", option: "--counter <counter>", name: "counter", description: "The last number drawn. The next draw adds `step` and stores the result, so a number is never handed out twice.", type: "integer", required: false },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "When the row was written, stamped by the database.", type: "string", required: false },
  { key: "idBody", option: "--id-body <id-body>", name: "id_body", description: "The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.", type: "string", required: false },
  { key: "padding", option: "--padding <padding>", name: "padding", description: "How many digits the counter is padded to. 6 gives `000001`.", type: "integer", required: false },
  { key: "positionStep", option: "--position-step <position-step>", name: "position_step", description: "How far apart position numbers sit on a new quote — 10 leaves room to insert a line later without renumbering.", type: "integer", required: false },
  { key: "prefix", option: "--prefix <prefix>", name: "prefix", description: "Put in front of the counter — `ANG-` produces `ANG-000001`.", type: "string", required: false },
  { key: "step", option: "--step <step>", name: "step", description: "How far the counter moves per draw. 1 is consecutive; a larger step leaves gaps on purpose.", type: "integer", required: false },
  { key: "suffix", option: "--suffix <suffix>", name: "suffix", description: "Put after the counter. Empty on the standard range.", type: "string", required: false },
  { key: "tenantId", option: "--tenant-id <tenant-id>", name: "tenant_id", description: "The tenant this row belongs to. Set by the data plane from the request identity and never accepted from a caller.", type: "string", required: false },
  { key: "updatedAt", option: "--updated-at <updated-at>", name: "updated_at", description: "When the row last changed, stamped by the app on every write.", type: "string", required: false },
];
quotesRanges
  .command(`update`)
  .description(`Changes a counter — its prefix, its padding, or the counter itself. Lowering the counter will hand out numbers that already exist, which the unique index then refuses.`)
  .option(`--id <id>`, `The number range.`)
  .option(`--code <code>`, `What a market points at to draw from this range. Unique per tenant; \`quote\` is the one this app seeds.`)
  .option(`--counter <counter>`, `The last number drawn. The next draw adds \`step\` and stores the result, so a number is never handed out twice.`, parseInteger)
  .option(`--created-at <created-at>`, `When the row was written, stamped by the database.`)
  .option(`--id-body <id-body>`, `The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.`)
  .option(`--padding <padding>`, `How many digits the counter is padded to. 6 gives \`000001\`.`, parseInteger)
  .option(`--position-step <position-step>`, `How far apart position numbers sit on a new quote — 10 leaves room to insert a line later without renumbering.`, parseInteger)
  .option(`--prefix <prefix>`, `Put in front of the counter — \`ANG-\` produces \`ANG-000001\`.`)
  .option(`--step <step>`, `How far the counter moves per draw. 1 is consecutive; a larger step leaves gaps on purpose.`, parseInteger)
  .option(`--suffix <suffix>`, `Put after the counter. Empty on the standard range.`)
  .option(`--tenant-id <tenant-id>`, `The tenant this row belongs to. Set by the data plane from the request identity and never accepted from a caller.`)
  .option(`--updated-at <updated-at>`, `When the row last changed, stamped by the app on every write.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, code, counter, createdAt, idBody, padding, positionStep, prefix, step, suffix, tenantId, updatedAt } = await promptForMissing(
          _options,
          updateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/quotes/number-ranges/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (counter !== undefined) {
          _payload[`counter`] = counter;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        if (idBody !== undefined) {
          _payload[`id`] = idBody;
        }
        if (padding !== undefined) {
          _payload[`padding`] = padding;
        }
        if (positionStep !== undefined) {
          _payload[`position_step`] = positionStep;
        }
        if (prefix !== undefined) {
          _payload[`prefix`] = prefix;
        }
        if (step !== undefined) {
          _payload[`step`] = step;
        }
        if (suffix !== undefined) {
          _payload[`suffix`] = suffix;
        }
        if (tenantId !== undefined) {
          _payload[`tenant_id`] = tenantId;
        }
        if (updatedAt !== undefined) {
          _payload[`updated_at`] = updatedAt;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `put`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(quotesRanges.commands.at(-1)!, updateSpecs, { method: "put" });
