import { Command } from "commander";
import { resolveBodyParam } from "../../utils.js";
import { sdkForProject } from "../../sdks.js";
import type { RequestParams } from "../../types.js";
import {
  actionRunner,
  commandDescriptions,
  cliConfig,
  parse,
  parseInteger,
} from "../../parser.js";
import {
  confirmDestructive,
  promptForMissing,
  type PromptSpec,
  registerPromptSpecs,
} from "../../interactive.js";

export const salesRepsActingFor = new Command("sales-reps-acting-for")
  .description(
    commandDescriptions["salesRepsActingFor"] ??
      `Every occasion on which a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. This is the only record ANYWHERE that somebody else was behind a buyer's actions: the session such a handover mints is a BUYER session, so on every other app the resulting order looks exactly as though the contact placed it themselves, and without these rows the question "who actually raised this order" has no answer at all. The log is APPEND-ONLY — there is no route that edits an entry, because what happened cannot be corrected afterwards without the log becoming an opinion, and a null \`ended_at\` is therefore a fact (a session nobody closed) rather than a gap to fill in. One route does remove an entry, and for one reason: the contact is a person, so an erasure request has to be able to reach these rows. Nothing writes here yet — the handover that will is the release after next; this group is the table and the way to read it.`,
  )
  .configureHelp({
    helpWidth: process.stdout.columns || 80,
  });

const salesRepsImpersonationsListSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.", type: "string", required: false },
  { key: "repCode", option: "--rep-code <rep-code>", name: "rep_code", description: "Every occasion one rep acted for a buyer. The audit question \"what has this rep been doing\" is exactly this filter.", type: "string", required: false },
  { key: "organizationId", option: "--organization-id <organization-id>", name: "organization_id", description: "Every occasion a rep acted inside one customer — the question a buyer asks when an order appears that nobody there remembers placing.", type: "string", required: false },
  { key: "contactId", option: "--contact-id <contact-id>", name: "contact_id", description: "Every occasion a rep acted as one particular buyer. This is the filter an erasure request is served by.", type: "string", required: false },
  { key: "startedAt", option: "--started-at <started-at>", name: "started_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the rep began acting for the buyer. Written when the entry is recorded, and it may be sent explicitly by whatever recorded it — a system that noticed afterwards must be able to say WHEN rather than when it got round to writing it down. Defaults to the moment of the write.", type: "string", required: false },
  { key: "endedAt", option: "--ended-at <ended-at>", name: "ended_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the rep stopped. Nullable, and a null is a FACT rather than a gap: it is a session nobody closed — the tab was shut, the token expired, the tablet went flat. There is no route that fills it in later, because this log is append-only; whoever records the entry records what they know.", type: "string", required: false },
  { key: "reason", option: "--reason <reason>", name: "reason", description: "Filter by the exact reason recorded. An equality over free text, so it is useful for a value a system writes and not for one a person typed.", type: "string", required: false },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.", type: "string", required: false },
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Page size (default 50, max 200). A larger value is clamped rather than refused.", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.", type: "integer", required: false },
  { key: "order", option: "--order <order>", name: "order", description: "Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.", type: "string", required: false },
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
salesRepsActingFor
  .command(`sales-reps-impersonations-list`)
  .description(`An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. This list is the answer to three different questions, each one a filter: \`?rep_code=\` is what one rep has been doing, \`?organization_id=\` is what happened inside one customer — the question a buyer asks when an order appears that nobody there remembers placing — and \`?contact_id=\` is every occasion somebody acted as one person, which is what an erasure request is served by. Sort with \`order=started_at.desc\` for the most recent first. An entry with no \`ended_at\` is a session nobody closed, which is a fact rather than a missing value.`)
  .option(`--id <id>`, `Filter to rows whose \`id\` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.`)
  .option(`--rep-code <rep-code>`, `Every occasion one rep acted for a buyer. The audit question "what has this rep been doing" is exactly this filter.`)
  .option(`--organization-id <organization-id>`, `Every occasion a rep acted inside one customer — the question a buyer asks when an order appears that nobody there remembers placing.`)
  .option(`--contact-id <contact-id>`, `Every occasion a rep acted as one particular buyer. This is the filter an erasure request is served by.`)
  .option(`--started-at <started-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When the rep began acting for the buyer. Written when the entry is recorded, and it may be sent explicitly by whatever recorded it — a system that noticed afterwards must be able to say WHEN rather than when it got round to writing it down. Defaults to the moment of the write.`)
  .option(`--ended-at <ended-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When the rep stopped. Nullable, and a null is a FACT rather than a gap: it is a session nobody closed — the tab was shut, the token expired, the tablet went flat. There is no route that fills it in later, because this log is append-only; whoever records the entry records what they know.`)
  .option(`--reason <reason>`, `Filter by the exact reason recorded. An equality over free text, so it is useful for a value a system writes and not for one a person typed.`)
  .option(`--created-at <created-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.`)
  .option(`--limit <limit>`, `Page size (default 50, max 200). A larger value is clamped rather than refused.`, parseInteger)
  .option(`--offset <offset>`, `Row offset for pagination (default 0). Page with \`page.total\` and \`page.hasMore\`.`, parseInteger)
  .option(`--order <order>`, `Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, repCode, organizationId, contactId, startedAt, endedAt, reason, createdAt, limit, offset, order, filter } = await promptForMissing(
          _options,
          salesRepsImpersonationsListSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/sales-reps/impersonations`;
        const _payload: RequestParams = {};
        if (id !== undefined) {
          _payload[`id`] = id;
        }
        if (repCode !== undefined) {
          _payload[`rep_code`] = repCode;
        }
        if (organizationId !== undefined) {
          _payload[`organization_id`] = organizationId;
        }
        if (contactId !== undefined) {
          _payload[`contact_id`] = contactId;
        }
        if (startedAt !== undefined) {
          _payload[`started_at`] = startedAt;
        }
        if (endedAt !== undefined) {
          _payload[`ended_at`] = endedAt;
        }
        if (reason !== undefined) {
          _payload[`reason`] = reason;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        if (order !== undefined) {
          _payload[`order`] = order;
        }
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(salesRepsActingFor.commands.at(-1)!, salesRepsImpersonationsListSpecs, { method: "get" });
const salesRepsImpersonationsCreateSpecs: PromptSpec[] = [
  { key: "contactId", option: "--contact-id <contact-id>", name: "contact_id", description: "WHICH buyer the rep acted as — the contact in the organization, as the customers app knows them. It is the buyer and not the rep: the session that will be minted for this is a BUYER session, so on every other app the resulting order looks exactly as though this contact placed it. That is the reason this table exists at all.", type: "string", required: true },
  { key: "organizationId", option: "--organization-id <organization-id>", name: "organization_id", description: "WHICH customer, as the customers app knows the organization. Nothing here checks that the organization exists — it lives in another app, and a call on every write would fail a whole import for one organization somebody archived.", type: "string", required: true },
  { key: "repCode", option: "--rep-code <rep-code>", name: "rep_code", description: "WHICH rep this row is about, by their `code` rather than by their row id. The code is what an ERP already holds, so an import can write this row before it has ever read an id out of this app. There is no foreign key behind it: the check is a membership test against the rep table on every write, and a code that names no rep is refused with 400 `unknown_rep`. It is also why a rep's code cannot be renamed and why a rep carrying rows here cannot be deleted.", type: "string", required: true },
  { key: "endedAt", option: "--ended-at <ended-at>", name: "ended_at", description: "When the rep stopped. Nullable, and a null is a FACT rather than a gap: it is a session nobody closed — the tab was shut, the token expired, the tablet went flat. There is no route that fills it in later, because this log is append-only; whoever records the entry records what they know.", type: "string", required: false },
  { key: "reason", option: "--reason <reason>", name: "reason", description: "Why the rep acted for this buyer, in the words of whoever recorded it — \"placed a telephone order\", \"checked a price the customer disputed\". Optional and never validated: a log that refused an unfamiliar reason would be a log with a gap in it.", type: "string", required: false },
  { key: "startedAt", option: "--started-at <started-at>", name: "started_at", description: "When the rep began acting for the buyer. Written when the entry is recorded, and it may be sent explicitly by whatever recorded it — a system that noticed afterwards must be able to say WHEN rather than when it got round to writing it down. Defaults to the moment of the write.", type: "string", required: false },
];
salesRepsActingFor
  .command(`sales-reps-impersonations-create`)
  .description(`An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. ⚠ Write this BEFORE the buyer session is minted, not after. The session such a handover creates is a BUYER session, so from the moment it exists every other app sees the contact and not the rep — and an entry written afterwards is an entry that a crash in between loses, leaving an order nobody can attribute. Three fields are owed. \`started_at\` defaults to the moment of the write and may be sent explicitly, because a system that noticed afterwards has to be able to say when it really began. \`ended_at\` and \`reason\` are optional and are written HERE or never: there is no route that fills them in later.`)
  .option(`--contact-id <contact-id>`, `WHICH buyer the rep acted as — the contact in the organization, as the customers app knows them. It is the buyer and not the rep: the session that will be minted for this is a BUYER session, so on every other app the resulting order looks exactly as though this contact placed it. That is the reason this table exists at all.`)
  .option(`--organization-id <organization-id>`, `WHICH customer, as the customers app knows the organization. Nothing here checks that the organization exists — it lives in another app, and a call on every write would fail a whole import for one organization somebody archived.`)
  .option(`--rep-code <rep-code>`, `WHICH rep this row is about, by their \`code\` rather than by their row id. The code is what an ERP already holds, so an import can write this row before it has ever read an id out of this app. There is no foreign key behind it: the check is a membership test against the rep table on every write, and a code that names no rep is refused with 400 \`unknown_rep\`. It is also why a rep's code cannot be renamed and why a rep carrying rows here cannot be deleted.`)
  .option(`--ended-at <ended-at>`, `When the rep stopped. Nullable, and a null is a FACT rather than a gap: it is a session nobody closed — the tab was shut, the token expired, the tablet went flat. There is no route that fills it in later, because this log is append-only; whoever records the entry records what they know.`)
  .option(`--reason <reason>`, `Why the rep acted for this buyer, in the words of whoever recorded it — "placed a telephone order", "checked a price the customer disputed". Optional and never validated: a log that refused an unfamiliar reason would be a log with a gap in it.`)
  .option(`--started-at <started-at>`, `When the rep began acting for the buyer. Written when the entry is recorded, and it may be sent explicitly by whatever recorded it — a system that noticed afterwards must be able to say WHEN rather than when it got round to writing it down. Defaults to the moment of the write.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { contactId, organizationId, repCode, endedAt, reason, startedAt } = await promptForMissing(
          _options,
          salesRepsImpersonationsCreateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/sales-reps/impersonations`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (contactId !== undefined) {
          _payload[`contact_id`] = contactId;
        }
        if (endedAt !== undefined) {
          _payload[`ended_at`] = endedAt;
        }
        if (organizationId !== undefined) {
          _payload[`organization_id`] = organizationId;
        }
        if (reason !== undefined) {
          _payload[`reason`] = reason;
        }
        if (repCode !== undefined) {
          _payload[`rep_code`] = repCode;
        }
        if (startedAt !== undefined) {
          _payload[`started_at`] = startedAt;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(salesRepsActingFor.commands.at(-1)!, salesRepsImpersonationsCreateSpecs, { method: "post" });
const salesRepsImpersonationsDeleteSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The entry to erase.", type: "string", required: true, resource: { listPath: "/sales-reps/impersonations", hasLimit: true } },
];
salesRepsActingFor
  .command(`sales-reps-impersonations-delete`)
  .description(`An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. This route exists for ONE reason and it is not editing: \`contact_id\` names a person, so an erasure request has to be able to reach these rows. Everything else about the log is append-only — there is no update route, and this is a removal rather than a correction. Deleting an entry destroys the only record that the session happened at all, so an operator reaching for it to tidy a list is reaching for the wrong thing.`)
  .option(`--id <id>`, `The entry to erase.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          salesRepsImpersonationsDeleteSpecs,
          _command,
        );
        await confirmDestructive(`sales-reps-acting-for sales-reps-impersonations-delete`);
        const _client = await sdkForProject();
        const _apiPath = `/sales-reps/impersonations/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `delete`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(salesRepsActingFor.commands.at(-1)!, salesRepsImpersonationsDeleteSpecs, { method: "delete", destructive: true });
const salesRepsImpersonationsGetSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The entry to read.", type: "string", required: true, resource: { listPath: "/sales-reps/impersonations", hasLimit: true } },
];
salesRepsActingFor
  .command(`sales-reps-impersonations-get`)
  .description(`An impersonation entry records that a rep acted for a buyer — which rep, in which organization, as which contact, from when until when, and why. It is the only record anywhere that somebody else was behind a buyer's actions, and it is append-only. The route that turns an id back into an entry, which is what an audit trail on another record links to. What is NOT here is a route that edits it: the entry says what happened, and a log that could be corrected afterwards is an opinion.`)
  .option(`--id <id>`, `The entry to read.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          salesRepsImpersonationsGetSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/sales-reps/impersonations/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(salesRepsActingFor.commands.at(-1)!, salesRepsImpersonationsGetSpecs, { method: "get" });
