import { Command } from "commander";
import { resolveBodyParam } from "../../utils.js";
import { sdkForProject } from "../../sdks.js";
import type { RequestParams } from "../../types.js";
import {
  actionRunner,
  commandDescriptions,
  cliConfig,
  parse,
  parseBool,
  parseInteger,
} from "../../parser.js";
import {
  confirmDestructive,
  promptForMissing,
  type PromptSpec,
  registerPromptSpecs,
} from "../../interactive.js";

export const salesRepsRoster = new Command("sales-reps-roster")
  .description(
    commandDescriptions["salesRepsRoster"] ??
      `The field sales reps a merchant employs, as records this platform owns. The column that matters is \`code\`: a short identifier the ERP already holds (\`salespersonCode\` on a Business Central customer, \`Representative_Code_RAITS\` on the customer row), unique per tenant and FIXED once created, because every assignment and every impersonation entry stores it and neither has a reference this app could follow to rename. It is the deliberate difference from the IntelliShop package this replaces, where a rep is identified by their EMAIL — so an ERP import there loses the record the moment somebody changes the address and files the same person again as a stranger with no customers. Here the address is an ordinary nullable attribute two reps may share. A rep who leaves is DEACTIVATED and not deleted: the record and its assignments stay standing, because the history points at them. Nothing in this group is secret — no credential, no password and no session token is stored in this app at all — and \`platform_user_id\` is the empty bridge a login will later be hung on.`,
  )
  .configureHelp({
    helpWidth: process.stdout.columns || 80,
  });

const salesRepsRepsListSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "Filter to rows whose `id` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.", type: "string", required: false },
  { key: "code", option: "--code <code>", name: "code", description: "Look ONE rep up by the code an ERP knows them by — the read a synchronisation makes before deciding between a create and an edit, and the read a screen makes when a customer record names a salesperson code. Unique per tenant, so this answers at most one rep.", type: "string", required: false },
  { key: "name", option: "--name <name>", name: "name", description: "Filter by the exact name. It is an equality and not a search: two reps may share a name, and nothing here is unique about it.", type: "string", required: false },
  { key: "email", option: "--email <email>", name: "email", description: "Filter by address. Deliberately NOT unique — two reps may share a shared mailbox and a rep may have none — so this can answer more than one rep, which is the whole reason the address is not the identity.", type: "string", required: false },
  { key: "phone", option: "--phone <phone>", name: "phone", description: "Filter to rows whose `phone` is exactly this value. How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.", type: "string", required: false },
  { key: "territory", option: "--territory <territory>", name: "territory", description: "Filter by the patch a rep covers. An exact match on one label, because a territory here is text and not a tree — there is no \"inside\" to search.", type: "string", required: false },
  { key: "active", option: "--active <active>", name: "active", description: "Filter to the reps who are working (`true`) or the ones who have left (`false`). This is the selector a screen uses instead of deleting anybody: a deactivated rep keeps their record and their assignments.", type: "boolean", required: false },
  { key: "platformUserId", option: "--platform-user-id <platform-user-id>", name: "platform_user_id", description: "Find the rep behind a platform identity — the reverse lookup a sign-in will need. It answers nothing today, because no rep has one yet.", type: "string", required: false },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "Look a rep up by the key the system that owns them knows them by. Unique per tenant where it is set, so this answers at most one rep.", type: "string", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.", type: "string", required: false },
  { key: "createdAt", option: "--created-at <created-at>", name: "created_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.", type: "string", required: false },
  { key: "updatedAt", option: "--updated-at <updated-at>", name: "updated_at", description: "Exact equality — this API has no range filter. To bound a period, sort with `order` and page. When the row was last written. Server-set — every route that changes this row stamps it.", type: "string", required: false },
  { key: "limit", option: "--limit <limit>", name: "limit", description: "Page size (default 50, max 200). A larger value is clamped rather than refused.", type: "integer", required: false },
  { key: "offset", option: "--offset <offset>", name: "offset", description: "Row offset for pagination (default 0). Page with `page.total` and `page.hasMore`.", type: "integer", required: false },
  { key: "order", option: "--order <order>", name: "order", description: "Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.", type: "string", required: false },
  { key: "filter", option: "--filter <column=value>", name: "filter", description: "Filter rows by column equality (column=value).", type: "string", required: false },
];
salesRepsRoster
  .command(`sales-reps-reps-list`)
  .description(`A rep is one field sales person, as a record this platform owns. They are identified by a \`code\` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. This is the roster: \`?code=\` resolves the one rep an ERP or a customer record names, \`?active=false\` is the list of the ones who have left, and \`?territory=\` groups a patch. Nothing in the answer is narrowed by who is asking — this app resolves no principal of its own, so an operator and a storefront caller read the same rows. That is a stated gap rather than an oversight: the gateway injects its identity with no subject header, and a rep resolved as a principal would arrive at every other app as a buyer.`)
  .option(`--id <id>`, `Filter to rows whose \`id\` is exactly this value. The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.`)
  .option(`--code <code>`, `Look ONE rep up by the code an ERP knows them by — the read a synchronisation makes before deciding between a create and an edit, and the read a screen makes when a customer record names a salesperson code. Unique per tenant, so this answers at most one rep.`)
  .option(`--name <name>`, `Filter by the exact name. It is an equality and not a search: two reps may share a name, and nothing here is unique about it.`)
  .option(`--email <email>`, `Filter by address. Deliberately NOT unique — two reps may share a shared mailbox and a rep may have none — so this can answer more than one rep, which is the whole reason the address is not the identity.`)
  .option(`--phone <phone>`, `Filter to rows whose \`phone\` is exactly this value. How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.`)
  .option(`--territory <territory>`, `Filter by the patch a rep covers. An exact match on one label, because a territory here is text and not a tree — there is no "inside" to search.`)
  .option(
    `--active [value]`,
    `Filter to the reps who are working (\`true\`) or the ones who have left (\`false\`). This is the selector a screen uses instead of deleting anybody: a deactivated rep keeps their record and their assignments.`,
    (value: string | undefined) =>
      value === undefined ? true : parseBool(value),
  )
  .option(`--platform-user-id <platform-user-id>`, `Find the rep behind a platform identity — the reverse lookup a sign-in will need. It answers nothing today, because no rep has one yet.`)
  .option(`--external-id <external-id>`, `Look a rep up by the key the system that owns them knows them by. Unique per tenant where it is set, so this answers at most one rep.`)
  .option(`--source-synced-at <source-synced-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.`)
  .option(`--created-at <created-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.`)
  .option(`--updated-at <updated-at>`, `Exact equality — this API has no range filter. To bound a period, sort with \`order\` and page. When the row was last written. Server-set — every route that changes this row stamps it.`)
  .option(`--limit <limit>`, `Page size (default 50, max 200). A larger value is clamped rather than refused.`, parseInteger)
  .option(`--offset <offset>`, `Row offset for pagination (default 0). Page with \`page.total\` and \`page.hasMore\`.`, parseInteger)
  .option(`--order <order>`, `Sort by one column: 'column' | 'column.asc' | 'column.desc' — a bare column sorts ascending. The column has to be one this entity has; anything else is refused with 400.`)
  .option(
    `--filter <column=value>`,
    `Filter rows by column equality (repeatable).`,
    (value: string, previous: string[]) => [...previous, value],
    [] as string[],
  )
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, code, name, email, phone, territory, active, platformUserId, externalId, sourceSyncedAt, createdAt, updatedAt, limit, offset, order, filter } = await promptForMissing(
          _options,
          salesRepsRepsListSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/sales-reps/reps`;
        const _payload: RequestParams = {};
        if (id !== undefined) {
          _payload[`id`] = id;
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (name !== undefined) {
          _payload[`name`] = name;
        }
        if (email !== undefined) {
          _payload[`email`] = email;
        }
        if (phone !== undefined) {
          _payload[`phone`] = phone;
        }
        if (territory !== undefined) {
          _payload[`territory`] = territory;
        }
        if (active !== undefined) {
          _payload[`active`] = active;
        }
        if (platformUserId !== undefined) {
          _payload[`platform_user_id`] = platformUserId;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        if (createdAt !== undefined) {
          _payload[`created_at`] = createdAt;
        }
        if (updatedAt !== undefined) {
          _payload[`updated_at`] = updatedAt;
        }
        if (limit !== undefined) {
          _payload[`limit`] = limit;
        }
        if (offset !== undefined) {
          _payload[`offset`] = offset;
        }
        if (order !== undefined) {
          _payload[`order`] = order;
        }
        for (const _filter of filter as string[]) {
          const _eq = _filter.indexOf("=");
          if (_eq <= 0) {
            throw new Error(`--filter expects column=value, got "${_filter}"`);
          }
          _payload[_filter.slice(0, _eq)] = _filter.slice(_eq + 1);
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(salesRepsRoster.commands.at(-1)!, salesRepsRepsListSpecs, { method: "get" });
const salesRepsRepsCreateSpecs: PromptSpec[] = [
  { key: "code", option: "--code <code>", name: "code", description: "The rep's STABLE IDENTITY, and the deliberate difference from the IntelliShop predecessor — where a rep is identified by their email address, so an ERP import loses the record the moment somebody changes the address and files the same person again as a stranger with no customers. This is a short code the ERP already owns (`salespersonCode` on a Business Central customer, `Representative_Code_RAITS` on the customer row), unique per tenant, and FIXED once created: every assignment and every impersonation entry stores it, and neither has a reference this app could follow to rename. Letters, digits, '.', '-' and '_', starting with a letter or a digit — the case is kept rather than folded, because the ERP's codes are upper case and a column that folded them would stop matching the system it points at.", type: "string", required: true },
  { key: "name", option: "--name <name>", name: "name", description: "What the rep is called, as a person reads it — the one field every list of reps has to show. At least one character. It is the field a merchant renames after a marriage or a typo, which is precisely why it is not the identity.", type: "string", required: true },
  { key: "active", option: "--active <active>", name: "active", description: "Whether this rep is currently working. Deactivating is what 'this person has left' means here, and it is NOT a delete: the record stays, the assignments stay, and the impersonation entries that name the code keep pointing at somebody. That is the whole reason the column exists — the history has to remain answerable. Defaults to true, because a rep is created in order to work. Defaults to true.", type: "boolean", required: false },
  { key: "email", option: "--email <email>", name: "email", description: "The rep's address, and NOTHING depends on it being unique or even present. That is the point: it is the column the predecessor used as the primary key, so here it is an ordinary attribute a merchant may leave empty, change, or share between two reps who work one shared mailbox. An import that only knows a code and a name records a usable rep. What a login is bound to is `platform_user_id`, which is a different column for a reason.", type: "string", required: false },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "The key this rep has in the system that OWNS them — the ERP's own row id, as distinct from the `code` printed on a customer record. Unique per tenant where it is set. It is the second handle a feed can find a rep by: `code` is the one a human quotes and the one this app's other tables store, and this is the one a synchronisation matches on when even the code has been re-issued.", type: "string", required: false },
  { key: "externalRefs", option: "--external-refs <external-refs>", name: "external_refs", description: "Every OTHER system that knows this rep, keyed by system name. `external_id` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on `metadata`.", type: "object", required: false },
  { key: "metadata", option: "--metadata <metadata>", name: "metadata", description: "Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so `?metadata=north` is refused with 400 `invalid_value` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.", type: "object", required: false },
  { key: "phone", option: "--phone <phone>", name: "phone", description: "How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.", type: "string", required: false },
  { key: "platformUserId", option: "--platform-user-id <platform-user-id>", name: "platform_user_id", description: "The bridge to a login: the platform identity a rep signs in with, once this app has an auth surface. Null on every rep today, because nothing mints one yet — a rep created now is a RECORD, not an account. It is an id and not a secret: no credential, no password hash and no session token is stored in this app at all, which is why there is nothing here a read has to withhold. Nothing mints one yet; a value sent here is stored and acted on by nothing.", type: "string", required: false },
  { key: "sourceData", option: "--source-data <source-data>", name: "source_data", description: "What the source said about this rep, kept as it said it. Carries the ETag a write-back has to return in `If-Match`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on `metadata`.", type: "object", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.", type: "string", required: false },
  { key: "territory", option: "--territory <territory>", name: "territory", description: "The patch this rep covers, as ONE piece of text and not a tree. A hierarchy of territories is deliberately out of scope: the rows that decide what a rep actually sees are the assignments, and a territory here is a label an operator groups a list by. Nothing in this app branches on it.", type: "string", required: false },
];
salesRepsRoster
  .command(`sales-reps-reps-create`)
  .description(`A rep is one field sales person, as a record this platform owns. They are identified by a \`code\` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. Two fields are owed and no more: \`code\` and \`name\`. That is deliberate and it is the whole difference from the package this replaces — an import that knows only a salesperson code and a name records a usable rep, where an app keyed on the email address would have had to invent one. A code this tenant already holds is refused with 409 rather than merged into: the unique index \`(tenant_id, code)\` is the guard, the pre-flight read only makes the refusal readable, and two simultaneous creates are separated by the index rather than by that read. Nothing is mailed and nobody is told — creating a rep grants no access at all, because this release has no login to grant.`)
  .option(`--code <code>`, `The rep's STABLE IDENTITY, and the deliberate difference from the IntelliShop predecessor — where a rep is identified by their email address, so an ERP import loses the record the moment somebody changes the address and files the same person again as a stranger with no customers. This is a short code the ERP already owns (\`salespersonCode\` on a Business Central customer, \`Representative_Code_RAITS\` on the customer row), unique per tenant, and FIXED once created: every assignment and every impersonation entry stores it, and neither has a reference this app could follow to rename. Letters, digits, '.', '-' and '_', starting with a letter or a digit — the case is kept rather than folded, because the ERP's codes are upper case and a column that folded them would stop matching the system it points at.`)
  .option(`--name <name>`, `What the rep is called, as a person reads it — the one field every list of reps has to show. At least one character. It is the field a merchant renames after a marriage or a typo, which is precisely why it is not the identity.`)
  .option(
    `--active [value]`,
    `Whether this rep is currently working. Deactivating is what 'this person has left' means here, and it is NOT a delete: the record stays, the assignments stay, and the impersonation entries that name the code keep pointing at somebody. That is the whole reason the column exists — the history has to remain answerable. Defaults to true, because a rep is created in order to work. Defaults to true.`,
    (value: string | undefined) =>
      value === undefined ? true : parseBool(value),
  )
  .option(`--email <email>`, `The rep's address, and NOTHING depends on it being unique or even present. That is the point: it is the column the predecessor used as the primary key, so here it is an ordinary attribute a merchant may leave empty, change, or share between two reps who work one shared mailbox. An import that only knows a code and a name records a usable rep. What a login is bound to is \`platform_user_id\`, which is a different column for a reason.`)
  .option(`--external-id <external-id>`, `The key this rep has in the system that OWNS them — the ERP's own row id, as distinct from the \`code\` printed on a customer record. Unique per tenant where it is set. It is the second handle a feed can find a rep by: \`code\` is the one a human quotes and the one this app's other tables store, and this is the one a synchronisation matches on when even the code has been re-issued.`)
  .option(`--external-refs <external-refs>`, `Every OTHER system that knows this rep, keyed by system name. \`external_id\` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on \`metadata\`.`)
  .option(`--metadata <metadata>`, `Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so \`?metadata=north\` is refused with 400 \`invalid_value\` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.`)
  .option(`--phone <phone>`, `How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.`)
  .option(`--platform-user-id <platform-user-id>`, `The bridge to a login: the platform identity a rep signs in with, once this app has an auth surface. Null on every rep today, because nothing mints one yet — a rep created now is a RECORD, not an account. It is an id and not a secret: no credential, no password hash and no session token is stored in this app at all, which is why there is nothing here a read has to withhold. Nothing mints one yet; a value sent here is stored and acted on by nothing.`)
  .option(`--source-data <source-data>`, `What the source said about this rep, kept as it said it. Carries the ETag a write-back has to return in \`If-Match\`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on \`metadata\`.`)
  .option(`--source-synced-at <source-synced-at>`, `When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.`)
  .option(`--territory <territory>`, `The patch this rep covers, as ONE piece of text and not a tree. A hierarchy of territories is deliberately out of scope: the rows that decide what a rep actually sees are the assignments, and a territory here is a label an operator groups a list by. Nothing in this app branches on it.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { code, name, active, email, externalId, externalRefs, metadata, phone, platformUserId, sourceData, sourceSyncedAt, territory } = await promptForMissing(
          _options,
          salesRepsRepsCreateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/sales-reps/reps`;
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (active !== undefined) {
          _payload[`active`] = active;
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (email !== undefined) {
          _payload[`email`] = email;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (externalRefs !== undefined) {
          _payload[`external_refs`] = resolveBodyParam(externalRefs);
        }
        if (metadata !== undefined) {
          _payload[`metadata`] = resolveBodyParam(metadata);
        }
        if (name !== undefined) {
          _payload[`name`] = name;
        }
        if (phone !== undefined) {
          _payload[`phone`] = phone;
        }
        if (platformUserId !== undefined) {
          _payload[`platform_user_id`] = platformUserId;
        }
        if (sourceData !== undefined) {
          _payload[`source_data`] = resolveBodyParam(sourceData);
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        if (territory !== undefined) {
          _payload[`territory`] = territory;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `post`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(salesRepsRoster.commands.at(-1)!, salesRepsRepsCreateSpecs, { method: "post" });
const salesRepsRepsDeleteSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The rep to remove.", type: "string", required: true, resource: { listPath: "/sales-reps/reps", hasLimit: true } },
];
salesRepsRoster
  .command(`sales-reps-reps-delete`)
  .description(`A rep is one field sales person, as a record this platform owns. They are identified by a \`code\` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. Almost always the wrong call, and the refusals say so. A rep who still carries customers is a 409 naming how many, and a rep who has ever acted for a buyer is a 409 too — the log references them by code and has no reference this app could cascade, so deleting them would leave the only record that a person acted for a buyer pointing at nobody. \`PUT\` with \`active: false\` is what "this person has left" means, and it keeps everything the history needs. What this route is for is a row created by mistake: a typo in a code, a duplicate an import filed before it was fixed.`)
  .option(`--id <id>`, `The rep to remove.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          salesRepsRepsDeleteSpecs,
          _command,
        );
        await confirmDestructive(`sales-reps-roster sales-reps-reps-delete`);
        const _client = await sdkForProject();
        const _apiPath = `/sales-reps/reps/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `delete`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(salesRepsRoster.commands.at(-1)!, salesRepsRepsDeleteSpecs, { method: "delete", destructive: true });
const salesRepsRepsGetSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The rep to read.", type: "string", required: true, resource: { listPath: "/sales-reps/reps", hasLimit: true } },
];
salesRepsRoster
  .command(`sales-reps-reps-get`)
  .description(`A rep is one field sales person, as a record this platform owns. They are identified by a \`code\` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. The route that turns an id back into a rep. Note which handle goes where: this path takes the row's own \`id\`, while \`assignments\` and \`impersonations\` reference the rep by \`code\` — so a caller holding a code reads GET /sales-reps/reps?code=… instead of putting it here, where it would fail the uuid cast.`)
  .option(`--id <id>`, `The rep to read.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id } = await promptForMissing(
          _options,
          salesRepsRepsGetSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/sales-reps/reps/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `get`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(salesRepsRoster.commands.at(-1)!, salesRepsRepsGetSpecs, { method: "get" });
const salesRepsRepsUpdateSpecs: PromptSpec[] = [
  { key: "id", option: "--id <id>", name: "id", description: "The rep to edit.", type: "string", required: true, resource: { listPath: "/sales-reps/reps", hasLimit: true } },
  { key: "active", option: "--active <active>", name: "active", description: "Whether this rep is currently working. Deactivating is what 'this person has left' means here, and it is NOT a delete: the record stays, the assignments stay, and the impersonation entries that name the code keep pointing at somebody. That is the whole reason the column exists — the history has to remain answerable. Defaults to true, because a rep is created in order to work. Defaults to true.", type: "boolean", required: false },
  { key: "code", option: "--code <code>", name: "code", description: "The rep's STABLE IDENTITY, and the deliberate difference from the IntelliShop predecessor — where a rep is identified by their email address, so an ERP import loses the record the moment somebody changes the address and files the same person again as a stranger with no customers. This is a short code the ERP already owns (`salespersonCode` on a Business Central customer, `Representative_Code_RAITS` on the customer row), unique per tenant, and FIXED once created: every assignment and every impersonation entry stores it, and neither has a reference this app could follow to rename. Letters, digits, '.', '-' and '_', starting with a letter or a digit — the case is kept rather than folded, because the ERP's codes are upper case and a column that folded them would stop matching the system it points at.", type: "string", required: false },
  { key: "email", option: "--email <email>", name: "email", description: "The rep's address, and NOTHING depends on it being unique or even present. That is the point: it is the column the predecessor used as the primary key, so here it is an ordinary attribute a merchant may leave empty, change, or share between two reps who work one shared mailbox. An import that only knows a code and a name records a usable rep. What a login is bound to is `platform_user_id`, which is a different column for a reason.", type: "string", required: false },
  { key: "externalId", option: "--external-id <external-id>", name: "external_id", description: "The key this rep has in the system that OWNS them — the ERP's own row id, as distinct from the `code` printed on a customer record. Unique per tenant where it is set. It is the second handle a feed can find a rep by: `code` is the one a human quotes and the one this app's other tables store, and this is the one a synchronisation matches on when even the code has been re-issued.", type: "string", required: false },
  { key: "externalRefs", option: "--external-refs <external-refs>", name: "external_refs", description: "Every OTHER system that knows this rep, keyed by system name. `external_id` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on `metadata`.", type: "object", required: false },
  { key: "metadata", option: "--metadata <metadata>", name: "metadata", description: "Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so `?metadata=north` is refused with 400 `invalid_value` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.", type: "object", required: false },
  { key: "name", option: "--name <name>", name: "name", description: "What the rep is called, as a person reads it — the one field every list of reps has to show. At least one character. It is the field a merchant renames after a marriage or a typo, which is precisely why it is not the identity.", type: "string", required: false },
  { key: "phone", option: "--phone <phone>", name: "phone", description: "How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.", type: "string", required: false },
  { key: "platformUserId", option: "--platform-user-id <platform-user-id>", name: "platform_user_id", description: "The bridge to a login: the platform identity a rep signs in with, once this app has an auth surface. Null on every rep today, because nothing mints one yet — a rep created now is a RECORD, not an account. It is an id and not a secret: no credential, no password hash and no session token is stored in this app at all, which is why there is nothing here a read has to withhold. Nothing mints one yet; a value sent here is stored and acted on by nothing.", type: "string", required: false },
  { key: "sourceData", option: "--source-data <source-data>", name: "source_data", description: "What the source said about this rep, kept as it said it. Carries the ETag a write-back has to return in `If-Match`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on `metadata`.", type: "object", required: false },
  { key: "sourceSyncedAt", option: "--source-synced-at <source-synced-at>", name: "source_synced_at", description: "When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.", type: "string", required: false },
  { key: "territory", option: "--territory <territory>", name: "territory", description: "The patch this rep covers, as ONE piece of text and not a tree. A hierarchy of territories is deliberately out of scope: the rows that decide what a rep actually sees are the assignments, and a territory here is a label an operator groups a list by. Nothing in this app branches on it.", type: "string", required: false },
];
salesRepsRoster
  .command(`sales-reps-reps-update`)
  .description(`A rep is one field sales person, as a record this platform owns. They are identified by a \`code\` an ERP already holds — never by their email address, which is an ordinary nullable attribute here — and that code is fixed once created, because every assignment and every impersonation entry stores it. A partial update: omitted fields keep their value, and a body carrying no field at all is refused rather than answered as a no-op. ⚠ This is where a rep is DEACTIVATED, with \`active: false\`, and that is what "this person has left" means here — the record stays, the assignments stay, and the impersonation entries naming their code keep pointing at somebody, so the history stays answerable. \`code\` may be sent only unchanged: both other tables store it and neither has a reference this app could follow, so a rename would silently orphan every one of them. The provenance columns are the other ones to leave alone — \`source_data\` holds the ETag a write-back to the ERP has to return, and an edit here does not touch it.`)
  .option(`--id <id>`, `The rep to edit.`)
  .option(
    `--active [value]`,
    `Whether this rep is currently working. Deactivating is what 'this person has left' means here, and it is NOT a delete: the record stays, the assignments stay, and the impersonation entries that name the code keep pointing at somebody. That is the whole reason the column exists — the history has to remain answerable. Defaults to true, because a rep is created in order to work. Defaults to true.`,
    (value: string | undefined) =>
      value === undefined ? true : parseBool(value),
  )
  .option(`--code <code>`, `The rep's STABLE IDENTITY, and the deliberate difference from the IntelliShop predecessor — where a rep is identified by their email address, so an ERP import loses the record the moment somebody changes the address and files the same person again as a stranger with no customers. This is a short code the ERP already owns (\`salespersonCode\` on a Business Central customer, \`Representative_Code_RAITS\` on the customer row), unique per tenant, and FIXED once created: every assignment and every impersonation entry stores it, and neither has a reference this app could follow to rename. Letters, digits, '.', '-' and '_', starting with a letter or a digit — the case is kept rather than folded, because the ERP's codes are upper case and a column that folded them would stop matching the system it points at.`)
  .option(`--email <email>`, `The rep's address, and NOTHING depends on it being unique or even present. That is the point: it is the column the predecessor used as the primary key, so here it is an ordinary attribute a merchant may leave empty, change, or share between two reps who work one shared mailbox. An import that only knows a code and a name records a usable rep. What a login is bound to is \`platform_user_id\`, which is a different column for a reason.`)
  .option(`--external-id <external-id>`, `The key this rep has in the system that OWNS them — the ERP's own row id, as distinct from the \`code\` printed on a customer record. Unique per tenant where it is set. It is the second handle a feed can find a rep by: \`code\` is the one a human quotes and the one this app's other tables store, and this is the one a synchronisation matches on when even the code has been re-issued.`)
  .option(`--external-refs <external-refs>`, `Every OTHER system that knows this rep, keyed by system name. \`external_id\` is the leading system; this is the rest, and a new one costs no column. Answered and NOT filterable — see the note on \`metadata\`.`)
  .option(`--metadata <metadata>`, `Free-form data the tenant keeps on the row. No route in this app reads it; it is stored and handed back unchanged. It is answered and is NOT a query parameter: a jsonb column is compared as a WHOLE document, so \`?metadata=north\` is refused with 400 \`invalid_value\` rather than answered with an empty page, and a selector whose every plausible use fails is worse than none.`)
  .option(`--name <name>`, `What the rep is called, as a person reads it — the one field every list of reps has to show. At least one character. It is the field a merchant renames after a marriage or a typo, which is precisely why it is not the identity.`)
  .option(`--phone <phone>`, `How a customer or a colleague reaches this rep, as the merchant writes it. Free text rather than a validated number: an internal extension, a second mobile and a note in brackets are all things that really appear in this field, and refusing them would cost a merchant the information.`)
  .option(`--platform-user-id <platform-user-id>`, `The bridge to a login: the platform identity a rep signs in with, once this app has an auth surface. Null on every rep today, because nothing mints one yet — a rep created now is a RECORD, not an account. It is an id and not a secret: no credential, no password hash and no session token is stored in this app at all, which is why there is nothing here a read has to withhold. Nothing mints one yet; a value sent here is stored and acted on by nothing.`)
  .option(`--source-data <source-data>`, `What the source said about this rep, kept as it said it. Carries the ETag a write-back has to return in \`If-Match\`, and the source fields this app does not model — without it those are lost on the first edit here. Answered and NOT filterable — see the note on \`metadata\`.`)
  .option(`--source-synced-at <source-synced-at>`, `When this row was last confirmed against its source. A delta run asks for changes since it, and an operator reads it to see that a feed has gone quiet. An edit made here does not touch it: it records when the SOURCE was last seen, not when the row changed.`)
  .option(`--territory <territory>`, `The patch this rep covers, as ONE piece of text and not a tree. A hierarchy of territories is deliberately out of scope: the rows that decide what a rep actually sees are the assignments, and a territory here is a label an operator groups a list by. Nothing in this app branches on it.`)
  .action(
    actionRunner(
      async (_options, _command) => {
        const { id, active, code, email, externalId, externalRefs, metadata, name, phone, platformUserId, sourceData, sourceSyncedAt, territory } = await promptForMissing(
          _options,
          salesRepsRepsUpdateSpecs,
          _command,
        );
        const _client = await sdkForProject();
        const _apiPath = `/sales-reps/reps/{id}`.replace(`{id}`, id);
        const _payload: RequestParams = {};
        if (cliConfig.data !== undefined) {
          const body = resolveBodyParam(cliConfig.data);
          if (typeof body !== "object" || body === null || Array.isArray(body)) {
            throw new Error("--data must be a JSON object");
          }
          Object.assign(_payload, body as RequestParams);
        }
        if (active !== undefined) {
          _payload[`active`] = active;
        }
        if (code !== undefined) {
          _payload[`code`] = code;
        }
        if (email !== undefined) {
          _payload[`email`] = email;
        }
        if (externalId !== undefined) {
          _payload[`external_id`] = externalId;
        }
        if (externalRefs !== undefined) {
          _payload[`external_refs`] = resolveBodyParam(externalRefs);
        }
        if (metadata !== undefined) {
          _payload[`metadata`] = resolveBodyParam(metadata);
        }
        if (name !== undefined) {
          _payload[`name`] = name;
        }
        if (phone !== undefined) {
          _payload[`phone`] = phone;
        }
        if (platformUserId !== undefined) {
          _payload[`platform_user_id`] = platformUserId;
        }
        if (sourceData !== undefined) {
          _payload[`source_data`] = resolveBodyParam(sourceData);
        }
        if (sourceSyncedAt !== undefined) {
          _payload[`source_synced_at`] = sourceSyncedAt;
        }
        if (territory !== undefined) {
          _payload[`territory`] = territory;
        }
        const _headers: Record<string, string> = {
          "content-type": "application/json",
        };
        const _response = await _client.call(
          `put`,
          _apiPath,
          _headers,
          _payload,
        );
        parse(_response as Record<string, unknown>);
      },
    ),
  );
registerPromptSpecs(salesRepsRoster.commands.at(-1)!, salesRepsRepsUpdateSpecs, { method: "put" });
